# SOPS configuration for NixOS Quick Deploy secrets
# Age public key: age15cql25z3ss02zm6ltjssk3638ewawu0vrk3ln2nveaazunr5dpnstmh8fq
creation_rules:
  - path_regex: ai-stack/secrets/.*\.enc\.yaml$
    age: age15cql25z3ss02zm6ltjssk3638ewawu0vrk3ln2nveaazunr5dpnstmh8fq
  - path_regex: ai-stack/secrets/.*\.enc\.json$
    age: age15cql25z3ss02zm6ltjssk3638ewawu0vrk3ln2nveaazunr5dpnstmh8fq
  - path_regex: .*secrets\.sops\.yaml$
    age: age15cql25z3ss02zm6ltjssk3638ewawu0vrk3ln2nveaazunr5dpnstmh8fq
