# ArgoCD Application for AI Stack Core Services
# Manages the primary AI services via Kustomize
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-stack-core
  namespace: argocd
  labels:
    app.kubernetes.io/name: ai-stack-core
    app.kubernetes.io/part-of: hospital-ai
    hipaa-compliance: required
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: ai-stack-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ai-stack-alerts
spec:
  project: ai-stack

  source:
    repoURL: https://github.com/MasterofNull/NixOS-Dev-Quick-Deploy.git
    targetRevision: main
    path: ai-stack/kustomize/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-stack

  syncPolicy:
    automated:
      prune: false  # Don't auto-delete resources (HIPAA safety)
      selfHeal: true  # Auto-fix drift from desired state
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences in certain fields that change at runtime
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data/prometheus.yml

  # Health assessment configuration
  revisionHistoryLimit: 5
