# App-of-Apps Pattern for Hospital AI Stack
# This single Application manages all other Applications
# Deploy this to bootstrap the entire GitOps workflow
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-ai-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: hospital-ai-apps
    app.kubernetes.io/component: app-of-apps
    hipaa-compliance: required
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/MasterofNull/NixOS-Dev-Quick-Deploy.git
    targetRevision: main
    path: gitops/argocd/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
