"""
Helpers for the ai-coordinator control and delegation surfaces.

This layer turns declarative switchboard/OpenRouter configuration into concrete
runtime lanes the harness can list, schedule, and invoke without requiring
callers to hand-roll x-ai-profile usage.
"""

from __future__ import annotations

import time
from typing import Any, Dict, List

from config import Config


def _runtime_record(
    runtime_id: str,
    *,
    name: str,
    profile: str,
    runtime_class: str,
    tags: List[str],
    status: str,
    note: str = "",
    model_alias: str = "",
    now: int,
) -> Dict[str, Any]:
    record: Dict[str, Any] = {
        "runtime_id": runtime_id,
        "name": name,
        "profile": profile,
        "status": status,
        "runtime_class": runtime_class,
        "transport": "openai-chat",
        "endpoint_env_var": "SWITCHBOARD_URL",
        "tags": tags,
        "updated_at": now,
        "created_at": now,
        "source": "ai-coordinator-default",
    }
    if note:
        record["status_notes"] = [{"ts": now, "text": note}]
    if model_alias:
        record["model_alias"] = model_alias
    return record


def runtime_defaults(now: int | None = None) -> List[Dict[str, Any]]:
    now_ts = int(now if now is not None else time.time())
    remote_configured = bool(Config.SWITCHBOARD_REMOTE_URL)

    remote_free_status = "ready" if remote_configured and Config.SWITCHBOARD_REMOTE_ALIAS_FREE else (
        "degraded" if remote_configured else "offline"
    )
    remote_coding_status = "ready" if remote_configured and Config.SWITCHBOARD_REMOTE_ALIAS_CODING else (
        "degraded" if remote_configured else "offline"
    )
    remote_reasoning_status = "ready" if remote_configured and Config.SWITCHBOARD_REMOTE_ALIAS_REASONING else (
        "degraded" if remote_configured else "offline"
    )

    return [
        _runtime_record(
            "local-hybrid",
            name="Local Hybrid Coordinator",
            profile="default",
            runtime_class="local-agent",
            tags=["local", "hybrid", "harness", "repo", "default"],
            status="ready",
            note="Built-in local-first harness lane.",
            now=now_ts,
        ),
        _runtime_record(
            "openrouter-free",
            name="OpenRouter Free Agent Lane",
            profile="remote-free",
            runtime_class="remote-agent",
            tags=["remote", "openrouter", "free", "tool-calling", "planner"],
            status=remote_free_status,
            note="Uses the free remote lane for bounded delegation and planning.",
            model_alias=Config.SWITCHBOARD_REMOTE_ALIAS_FREE,
            now=now_ts,
        ),
        _runtime_record(
            "openrouter-coding",
            name="OpenRouter Coding Agent Lane",
            profile="remote-coding",
            runtime_class="remote-agent",
            tags=["remote", "openrouter", "coding", "tool-calling", "implementation"],
            status=remote_coding_status,
            note="Uses the coding-optimized remote lane for implementation-heavy delegation.",
            model_alias=Config.SWITCHBOARD_REMOTE_ALIAS_CODING,
            now=now_ts,
        ),
        _runtime_record(
            "openrouter-reasoning",
            name="OpenRouter Reasoning Agent Lane",
            profile="remote-reasoning",
            runtime_class="remote-agent",
            tags=["remote", "openrouter", "reasoning", "tool-calling", "review"],
            status=remote_reasoning_status,
            note="Uses the higher-judgment remote lane for architecture and review tasks.",
            model_alias=Config.SWITCHBOARD_REMOTE_ALIAS_REASONING,
            now=now_ts,
        ),
    ]


def merge_runtime_defaults(registry: Dict[str, Any], now: int | None = None) -> Dict[str, Any]:
    merged = {"runtimes": dict((registry or {}).get("runtimes", {}) or {})}
    for record in runtime_defaults(now=now):
        runtime_id = record["runtime_id"]
        existing = merged["runtimes"].get(runtime_id)
        if not isinstance(existing, dict):
            merged["runtimes"][runtime_id] = record
            continue
        # Refresh declarative defaults when the stored record was generated by
        # this module, but leave user-registered/custom runtimes untouched.
        if str(existing.get("source", "")).strip() == "ai-coordinator-default":
            refreshed = dict(record)
            if existing.get("created_at"):
                refreshed["created_at"] = existing["created_at"]
            merged["runtimes"][runtime_id] = refreshed
    return merged


def runtime_registry_retention_seconds() -> int:
    raw = str(getattr(Config, "AI_COORDINATOR_RUNTIME_RETENTION_SECONDS", "") or "").strip()
    if raw:
        try:
            return max(300, int(raw))
        except (TypeError, ValueError):
            pass
    return 12 * 60 * 60


def is_transient_runtime_record(record: Dict[str, Any]) -> bool:
    if not isinstance(record, dict):
        return False
    if bool(record.get("persistent")):
        return False
    source = str(record.get("source", "") or "").strip().lower()
    if source in {"ai-coordinator-default", "user-managed", "declarative"}:
        return False
    tags = {str(tag or "").strip().lower() for tag in record.get("tags", []) if str(tag or "").strip()}
    name = str(record.get("name", "") or "").strip().lower()
    runtime_id = str(record.get("runtime_id", "") or "").strip().lower()
    runtime_class = str(record.get("runtime_class", "") or "").strip().lower()
    if source in {"runtime-register", "smoke", "test", "smoke-test"}:
        return True
    if "smoke" in tags or "test" in tags:
        return True
    if name == "smoke-runtime":
        return True
    if runtime_class == "sandboxed":
        return True
    if runtime_id.startswith("smoke-"):
        return True
    return False


def prune_runtime_registry(registry: Dict[str, Any], now: int | None = None) -> Dict[str, Any]:
    current = int(now if now is not None else time.time())
    retention = runtime_registry_retention_seconds()
    merged = merge_runtime_defaults(registry, now=current)
    runtimes = dict((merged.get("runtimes", {}) or {}))
    kept: Dict[str, Dict[str, Any]] = {}
    pruned_ids: List[str] = []
    for runtime_id, record in runtimes.items():
        if not isinstance(record, dict):
            continue
        if not is_transient_runtime_record(record):
            kept[runtime_id] = record
            continue
        updated_at = int(record.get("updated_at") or record.get("created_at") or 0)
        age_s = max(0, current - updated_at) if updated_at > 0 else retention + 1
        if age_s > retention:
            pruned_ids.append(runtime_id)
            continue
        kept[runtime_id] = record
    return {
        "runtimes": kept,
        "meta": {
            "retention_seconds": retention,
            "last_pruned_at": current,
            "pruned_runtime_ids": pruned_ids,
        },
    }


def infer_profile(task: str, requested_profile: str = "") -> str:
    profile = str(requested_profile or "").strip().lower()
    if profile in {"default", "local", "local-hybrid", "continue-local"}:
        return "default"
    if profile in {"remote-free", "remote-coding", "remote-reasoning"}:
        return profile

    lowered = str(task or "").lower()
    if any(token in lowered for token in ("architecture", "review", "risk", "tradeoff", "policy", "reasoning")):
        return "remote-reasoning"
    if any(token in lowered for token in ("code", "patch", "implement", "refactor", "fix", "debug")):
        return "remote-coding"
    return "remote-free"


def default_runtime_id_for_profile(profile: str) -> str:
    mapping = {
        "default": "local-hybrid",
        "local": "local-hybrid",
        "local-hybrid": "local-hybrid",
        "continue-local": "local-hybrid",
        "remote-free": "openrouter-free",
        "remote-coding": "openrouter-coding",
        "remote-reasoning": "openrouter-reasoning",
    }
    return mapping.get(str(profile or "").strip().lower(), "openrouter-free")


def _delegation_system_prompt(profile: str) -> str:
    role = {
        "remote-coding": "implementation sub-agent",
        "remote-reasoning": "architecture/review sub-agent",
        "remote-free": "bounded research/planning sub-agent",
        "default": "local delegated sub-agent",
    }.get(str(profile or "").strip().lower(), "delegated sub-agent")
    return (
        f"You are a {role} inside the NixOS-Dev-Quick-Deploy harness.\n"
        "You are not the orchestrator.\n"
        "Execute only the assigned slice.\n"
        "Respond concisely.\n"
        "Do not invent files, commands, or validation you did not actually derive from the provided task/context.\n"
        "Return evidence-first output with concrete paths, commands, and risks when available.\n"
        "If the task cannot be completed from the provided inputs, say what is missing instead of improvising."
    )


def _normalize_list(value: Any) -> List[str]:
    if isinstance(value, list):
        out: List[str] = []
        for item in value:
            text = str(item or "").strip()
            if text:
                out.append(text)
        return out
    text = str(value or "").strip()
    return [text] if text else []


def _delegation_contract_block(task: str, profile: str, context: Dict[str, Any] | None) -> str:
    ctx = context if isinstance(context, dict) else {}
    repo_paths = _normalize_list(ctx.get("repo_paths"))
    constraints = _normalize_list(ctx.get("constraints"))
    evidence = _normalize_list(ctx.get("evidence_requirements"))
    anti_goals = _normalize_list(ctx.get("anti_goals"))
    artifact = str(ctx.get("expected_artifact") or "").strip()
    output_format = str(ctx.get("output_format") or "").strip()

    default_artifact = {
        "remote-coding": "small patch plan or implementation sketch tied to existing repo paths",
        "remote-reasoning": "design/review notes with concrete risks and recommended direction",
        "remote-free": "bounded synthesis with actionable findings",
        "default": "bounded task result with evidence",
    }.get(str(profile or "").strip().lower(), "bounded task result with evidence")
    if not artifact:
        artifact = default_artifact

    lines = [
        f"Task: {task.strip()}",
        f"Expected artifact: {artifact}",
        "Required output sections:",
        "- result",
        "- evidence",
        "- risks",
        "- rollback_or_next_step",
    ]
    if output_format:
        lines.append(f"Output format constraint: {output_format}")
    if repo_paths:
        lines.append("Allowed repo paths:")
        lines.extend(f"- {item}" for item in repo_paths[:8])
    if constraints:
        lines.append("Constraints:")
        lines.extend(f"- {item}" for item in constraints[:8])
    else:
        lines.append("Constraints:")
        lines.append("- stay within the assigned slice")
        lines.append("- do not invent repo paths or validation")
    if evidence:
        lines.append("Evidence requirements:")
        lines.extend(f"- {item}" for item in evidence[:8])
    else:
        lines.append("Evidence requirements:")
        lines.append("- cite concrete files, commands, or runtime facts when available")
    if anti_goals:
        lines.append("Anti-goals:")
        lines.extend(f"- {item}" for item in anti_goals[:8])
    return "\n".join(lines)


def build_messages(
    task: str,
    system_prompt: str = "",
    context: Dict[str, Any] | None = None,
    profile: str = "remote-free",
) -> List[Dict[str, str]]:
    messages: List[Dict[str, str]] = []
    sys_prompt = system_prompt.strip() if system_prompt.strip() else _delegation_system_prompt(profile)
    messages.append({"role": "system", "content": sys_prompt})
    body = _delegation_contract_block(str(task or ""), profile, context)
    extra_context = context.get("extra_context") if isinstance(context, dict) else None
    if extra_context:
        body += "\n\nAdditional context:\n" + str(extra_context).strip()
    messages.append({"role": "user", "content": body.strip()})
    return messages
