"""
Helpers for the ai-coordinator control and delegation surfaces.

This layer turns declarative switchboard/OpenRouter configuration into concrete
runtime lanes the harness can list, schedule, and invoke without requiring
callers to hand-roll x-ai-profile usage.
"""

from __future__ import annotations

import time
from typing import Any, Dict, List

from config import Config


def _runtime_record(
    runtime_id: str,
    *,
    name: str,
    profile: str,
    runtime_class: str,
    tags: List[str],
    status: str,
    note: str = "",
    model_alias: str = "",
    now: int,
) -> Dict[str, Any]:
    record: Dict[str, Any] = {
        "runtime_id": runtime_id,
        "name": name,
        "profile": profile,
        "status": status,
        "runtime_class": runtime_class,
        "transport": "openai-chat",
        "endpoint_env_var": "SWITCHBOARD_URL",
        "tags": tags,
        "updated_at": now,
        "created_at": now,
        "source": "ai-coordinator-default",
    }
    if note:
        record["status_notes"] = [{"ts": now, "text": note}]
    if model_alias:
        record["model_alias"] = model_alias
    return record


def runtime_defaults(now: int | None = None) -> List[Dict[str, Any]]:
    now_ts = int(now if now is not None else time.time())
    remote_configured = bool(Config.SWITCHBOARD_REMOTE_URL)

    remote_free_status = "ready" if remote_configured and Config.SWITCHBOARD_REMOTE_ALIAS_FREE else (
        "degraded" if remote_configured else "offline"
    )
    remote_coding_status = "ready" if remote_configured and Config.SWITCHBOARD_REMOTE_ALIAS_CODING else (
        "degraded" if remote_configured else "offline"
    )
    remote_reasoning_status = "ready" if remote_configured and Config.SWITCHBOARD_REMOTE_ALIAS_REASONING else (
        "degraded" if remote_configured else "offline"
    )

    return [
        _runtime_record(
            "local-hybrid",
            name="Local Hybrid Coordinator",
            profile="default",
            runtime_class="local-agent",
            tags=["local", "hybrid", "harness", "repo", "default"],
            status="ready",
            note="Built-in local-first harness lane.",
            now=now_ts,
        ),
        _runtime_record(
            "openrouter-free",
            name="OpenRouter Free Agent Lane",
            profile="remote-free",
            runtime_class="remote-agent",
            tags=["remote", "openrouter", "free", "tool-calling", "planner"],
            status=remote_free_status,
            note="Uses the free remote lane for bounded delegation and planning.",
            model_alias=Config.SWITCHBOARD_REMOTE_ALIAS_FREE,
            now=now_ts,
        ),
        _runtime_record(
            "openrouter-coding",
            name="OpenRouter Coding Agent Lane",
            profile="remote-coding",
            runtime_class="remote-agent",
            tags=["remote", "openrouter", "coding", "tool-calling", "implementation"],
            status=remote_coding_status,
            note="Uses the coding-optimized remote lane for implementation-heavy delegation.",
            model_alias=Config.SWITCHBOARD_REMOTE_ALIAS_CODING,
            now=now_ts,
        ),
        _runtime_record(
            "openrouter-reasoning",
            name="OpenRouter Reasoning Agent Lane",
            profile="remote-reasoning",
            runtime_class="remote-agent",
            tags=["remote", "openrouter", "reasoning", "tool-calling", "review"],
            status=remote_reasoning_status,
            note="Uses the higher-judgment remote lane for architecture and review tasks.",
            model_alias=Config.SWITCHBOARD_REMOTE_ALIAS_REASONING,
            now=now_ts,
        ),
    ]


def merge_runtime_defaults(registry: Dict[str, Any], now: int | None = None) -> Dict[str, Any]:
    merged = {"runtimes": dict((registry or {}).get("runtimes", {}) or {})}
    for record in runtime_defaults(now=now):
        runtime_id = record["runtime_id"]
        existing = merged["runtimes"].get(runtime_id)
        if not isinstance(existing, dict):
            merged["runtimes"][runtime_id] = record
            continue
        # Refresh declarative defaults when the stored record was generated by
        # this module, but leave user-registered/custom runtimes untouched.
        if str(existing.get("source", "")).strip() == "ai-coordinator-default":
            refreshed = dict(record)
            if existing.get("created_at"):
                refreshed["created_at"] = existing["created_at"]
            merged["runtimes"][runtime_id] = refreshed
    return merged


def infer_profile(task: str, requested_profile: str = "") -> str:
    profile = str(requested_profile or "").strip().lower()
    if profile in {"default", "local", "local-hybrid", "continue-local"}:
        return "default"
    if profile in {"remote-free", "remote-coding", "remote-reasoning"}:
        return profile

    lowered = str(task or "").lower()
    if any(token in lowered for token in ("architecture", "review", "risk", "tradeoff", "policy", "reasoning")):
        return "remote-reasoning"
    if any(token in lowered for token in ("code", "patch", "implement", "refactor", "fix", "debug")):
        return "remote-coding"
    return "remote-free"


def default_runtime_id_for_profile(profile: str) -> str:
    mapping = {
        "default": "local-hybrid",
        "local": "local-hybrid",
        "local-hybrid": "local-hybrid",
        "continue-local": "local-hybrid",
        "remote-free": "openrouter-free",
        "remote-coding": "openrouter-coding",
        "remote-reasoning": "openrouter-reasoning",
    }
    return mapping.get(str(profile or "").strip().lower(), "openrouter-free")


def build_messages(task: str, system_prompt: str = "", context: Dict[str, Any] | None = None) -> List[Dict[str, str]]:
    messages: List[Dict[str, str]] = []
    if system_prompt.strip():
        messages.append({"role": "system", "content": system_prompt.strip()})
    body = str(task or "").strip()
    if context:
        body += "\n\nContext:\n" + str(context)
    messages.append({"role": "user", "content": body.strip()})
    return messages
