#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/home/hyperd/Documents/NixOS-Dev-Quick-Deploy}"
PY_SDK="${ROOT}/ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.py"
TS_SDK="${ROOT}/ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.ts"
OUT="${ROOT}/docs/generated/HARNESS-SDK-API.md"

MODE="write"
if [[ "${1:-}" == "--check" ]]; then
  MODE="check"
elif [[ "${1:-}" == "--write" || -z "${1:-}" ]]; then
  MODE="write"
else
  echo "Usage: $0 [--write|--check]" >&2
  exit 2
fi

tmp="$(mktemp /tmp/harness-sdk-api-XXXXXX.md)"
trap 'rm -f "$tmp"' EXIT

python - "$PY_SDK" "$TS_SDK" >"$tmp" <<'PY'
import ast
import re
import sys
from pathlib import Path

py_path = Path(sys.argv[1])
ts_path = Path(sys.argv[2])


def _py_signature(fn: ast.FunctionDef) -> str:
    args = fn.args.args[1:]  # skip self
    defaults = fn.args.defaults
    default_start = len(args) - len(defaults)
    default_map = {}
    for i, d in enumerate(defaults):
        idx = default_start + i
        if idx >= 0:
            default_map[idx] = d

    parts = []
    for idx, arg in enumerate(args):
        name = arg.arg
        if idx in default_map:
            node = default_map[idx]
            if isinstance(node, ast.Constant):
                dv = repr(node.value)
            else:
                dv = "..."
            parts.append(f"{name}={dv}")
        else:
            parts.append(name)
    return f"{fn.name}({', '.join(parts)})"


def parse_python_methods(path: Path):
    mod = ast.parse(path.read_text(encoding="utf-8"))
    out = []
    for node in mod.body:
        if isinstance(node, ast.ClassDef) and node.name == "HarnessClient":
            for item in node.body:
                if isinstance(item, ast.FunctionDef) and not item.name.startswith("_"):
                    out.append(_py_signature(item))
    return out


def parse_ts_methods(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    out = []
    in_class = False
    class_depth = 0
    method_re_single = re.compile(r"^\s{2}([A-Za-z_]\w*)\(([^)]*)\)\s*:\s*Promise<[^>]+>\s*\{")
    method_start_multiline = re.compile(r"^\s{2}([A-Za-z_]\w*)\($")
    pending_name = None
    pending_params = []
    for line in lines:
        if not in_class and re.search(r"\bclass\s+HarnessClient\b", line):
            in_class = True
        if in_class:
            class_depth += line.count("{")
            class_depth -= line.count("}")
            m = method_re_single.match(line)
            if m:
                name = m.group(1)
                params = " ".join(m.group(2).split())
                out.append(f"{name}({params})")
                continue

            if pending_name is None:
                sm = method_start_multiline.match(line)
                if sm:
                    pending_name = sm.group(1)
                    pending_params = []
                    continue
            else:
                stripped = line.strip()
                if "): Promise<" in stripped:
                    params = ", ".join(" ".join(p.split()).strip() for p in pending_params if p.strip())
                    out.append(f"{pending_name}({params})")
                    pending_name = None
                    pending_params = []
                    continue
                if stripped != "":
                    pending_params.append(stripped.rstrip(","))

            if class_depth <= 0:
                break
    return out


py_methods = parse_python_methods(py_path)
ts_methods = parse_ts_methods(ts_path)

body = []
body.append("# Harness SDK API (Generated)")
body.append("")
body.append("This file is generated by `scripts/data/generate-harness-sdk-api-docs.sh`.")
body.append("Do not edit manually.")
body.append("")
body.append("## Python (`harness_sdk.py`)")
body.append("")
for m in py_methods:
    body.append(f"- `{m}`")
body.append("")
body.append("## TypeScript (`harness_sdk.ts`)")
body.append("")
for m in ts_methods:
    body.append(f"- `{m}`")
body.append("")
body.append("## Covered Endpoints")
body.append("")
body.append("- `POST /workflow/plan`")
body.append("- `POST /workflow/session/start`")
body.append("- `GET /workflow/sessions`")
body.append("- `GET /workflow/tree`")
body.append("- `GET /workflow/session/{id}`")
body.append("- `GET /workflow/session/{id}?lineage=true`")
body.append("- `POST /workflow/session/{id}/fork`")
body.append("- `POST /workflow/session/{id}/advance`")
body.append("- `POST /review/acceptance`")
body.append("- `POST /harness/eval`")
body.append("")

print("\n".join(body))
PY

mkdir -p "$(dirname "$OUT")"
if [[ "$MODE" == "write" ]]; then
  cp "$tmp" "$OUT"
  echo "Generated: $OUT"
else
  if [[ ! -f "$OUT" ]]; then
    echo "Missing generated docs: $OUT" >&2
    exit 1
  fi
  if ! diff -u "$OUT" "$tmp" >/dev/null; then
    echo "Generated SDK docs are out of date: $OUT" >&2
    echo "Run: scripts/data/generate-harness-sdk-api-docs.sh --write" >&2
    diff -u "$OUT" "$tmp" || true
    exit 1
  fi
  echo "SDK API docs are up to date: $OUT"
fi
