apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  $patch: replace
  type: ClusterIP
  selector:
    io.kompose.service: nginx
  ports:
    - name: http
      port: 8088
      targetPort: 8088
    - name: https
      port: 8443
      targetPort: 8443
