/**
  Phase 16.5.3 — SBC minimal host module.

  Imports facts.nix and applies SBC-specific overrides on top of the
  common module stack.  Hardware-configuration.nix is included when
  present (generated by nixos-generate-config on real hardware).

  To deploy on a Raspberry Pi 4:
    1. nixos-generate-config --root /mnt
    2. Copy nix/hosts/sbc-minimal/ to the target host.
    3. Place hardware-configuration.nix here.
    4. nixos-rebuild switch --flake .#sbc-minimal-ai-dev
*/
{ lib, ... }:
{
  imports = [ ./facts.nix ];
  # hardware-configuration.nix is intentionally absent in the reference config;
  # add it from nixos-generate-config for a real deployment.

  # Disable journald rate limiting — SD cards can drop messages under burst I/O.
  services.journald.extraConfig = lib.mkDefault ''
    RateLimitInterval=30s
    RateLimitBurst=500
  '';
}
