#!/usr/bin/env bash
#
# Service Endpoints Configuration
# Defines health check URLs and endpoints for all AI stack services
#
# Source this file to set service endpoint variables
# Used by parallel-health-checks.sh and other health monitoring

# Service Port Configuration
LLAMA_PORT="${LLAMA_PORT:-8080}"
LLAMA_HOST="${LLAMA_HOST:-localhost}"
LLAMA_URL="http://${LLAMA_HOST}:${LLAMA_PORT}"

EMBEDDINGS_PORT="${EMBEDDINGS_PORT:-8081}"
EMBEDDINGS_HOST="${EMBEDDINGS_HOST:-localhost}"
EMBEDDINGS_URL="http://${EMBEDDINGS_HOST}:${EMBEDDINGS_PORT}"

AIDB_PORT="${AIDB_PORT:-8002}"
AIDB_HOST="${AIDB_HOST:-localhost}"
AIDB_URL="http://${AIDB_HOST}:${AIDB_PORT}"

HYBRID_PORT="${HYBRID_PORT:-8003}"
HYBRID_HOST="${HYBRID_HOST:-localhost}"
HYBRID_URL="http://${HYBRID_HOST}:${HYBRID_PORT}"

DASHBOARD_API_PORT="${DASHBOARD_API_PORT:-8889}"
DASHBOARD_API_HOST="${DASHBOARD_API_HOST:-localhost}"
DASHBOARD_API_URL="http://${DASHBOARD_API_HOST}:${DASHBOARD_API_PORT}"

SWITCHBOARD_PORT="${SWITCHBOARD_PORT:-8085}"
SWITCHBOARD_HOST="${SWITCHBOARD_HOST:-localhost}"
SWITCHBOARD_URL="http://${SWITCHBOARD_HOST}:${SWITCHBOARD_PORT}"

RALPH_PORT="${RALPH_PORT:-8004}"
RALPH_HOST="${RALPH_HOST:-localhost}"
RALPH_URL="${RALPH_URL:-http://${RALPH_HOST}:${RALPH_PORT}}"

AIDER_WRAPPER_PORT="${AIDER_WRAPPER_PORT:-8090}"
AIDER_HOST="${AIDER_HOST:-localhost}"
AIDER_URL="${AIDER_URL:-http://${AIDER_HOST}:${AIDER_WRAPPER_PORT}}"

NIXOS_DOCS_PORT="${NIXOS_DOCS_PORT:-8096}"
NIXOS_DOCS_HOST="${NIXOS_DOCS_HOST:-localhost}"
NIXOS_DOCS_URL="${NIXOS_DOCS_URL:-http://${NIXOS_DOCS_HOST}:${NIXOS_DOCS_PORT}}"

OPEN_WEBUI_PORT="${OPEN_WEBUI_PORT:-3001}"
OPEN_WEBUI_HOST="${OPEN_WEBUI_HOST:-localhost}"
OPEN_WEBUI_URL="${OPEN_WEBUI_URL:-http://${OPEN_WEBUI_HOST}:${OPEN_WEBUI_PORT}}"

GRAFANA_PORT="${GRAFANA_PORT:-3000}"
GRAFANA_HOST="${GRAFANA_HOST:-localhost}"
GRAFANA_URL="${GRAFANA_URL:-http://${GRAFANA_HOST}:${GRAFANA_PORT}}"

PROMETHEUS_PORT="${PROMETHEUS_PORT:-9090}"
PROMETHEUS_HOST="${PROMETHEUS_HOST:-localhost}"
PROMETHEUS_URL="http://${PROMETHEUS_HOST}:${PROMETHEUS_PORT}"

# The command-center dashboard serves both UI and API from the same port in the
# active NixOS deployment. Keep DASHBOARD_URL aligned with DASHBOARD_API_URL
# unless a separate frontend port is explicitly injected.
DASHBOARD_PORT="${DASHBOARD_PORT:-${DASHBOARD_API_PORT}}"
DASHBOARD_HOST="${DASHBOARD_HOST:-${DASHBOARD_API_HOST}}"
DASHBOARD_URL="http://${DASHBOARD_HOST}:${DASHBOARD_PORT}"

REDIS_PORT="${REDIS_PORT:-6379}"
REDIS_HOST="${REDIS_HOST:-localhost}"
REDIS_URL="redis://${REDIS_HOST}:${REDIS_PORT}"

POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_DB="${POSTGRES_DB:-aidb}"
POSTGRES_URL="postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}"

# Health Check Endpoints
LLAMA_HEALTH_ENDPOINT="/health"
LLAMA_HEALTH_URL="${LLAMA_URL}${LLAMA_HEALTH_ENDPOINT}"

EMBEDDINGS_HEALTH_ENDPOINT="/health"
EMBEDDINGS_HEALTH_URL="${EMBEDDINGS_URL}${EMBEDDINGS_HEALTH_ENDPOINT}"

AIDB_HEALTH_ENDPOINT="/health"
AIDB_HEALTH_URL="${AIDB_URL}${AIDB_HEALTH_ENDPOINT}"

HYBRID_HEALTH_ENDPOINT="/health"
HYBRID_HEALTH_URL="${HYBRID_URL}${HYBRID_HEALTH_ENDPOINT}"

# Timeout Configuration
LLAMA_STARTUP_TIMEOUT="${LLAMA_STARTUP_TIMEOUT:-40}"
EMBEDDINGS_STARTUP_TIMEOUT="${EMBEDDINGS_STARTUP_TIMEOUT:-40}"
AIDB_STARTUP_TIMEOUT="${AIDB_STARTUP_TIMEOUT:-50}"
HYBRID_STARTUP_TIMEOUT="${HYBRID_STARTUP_TIMEOUT:-30}"

HEALTH_CHECK_INTERVAL="${HEALTH_CHECK_INTERVAL:-2}"
HEALTH_CHECK_TIMEOUT="${HEALTH_CHECK_TIMEOUT:-60}"
HTTP_CONNECT_TIMEOUT="${HTTP_CONNECT_TIMEOUT:-2}"
HTTP_MAX_TIME="${HTTP_MAX_TIME:-5}"

export LLAMA_URL EMBEDDINGS_URL AIDB_URL HYBRID_URL SWITCHBOARD_URL DASHBOARD_URL DASHBOARD_API_URL PROMETHEUS_URL
export RALPH_URL AIDER_URL NIXOS_DOCS_URL OPEN_WEBUI_URL GRAFANA_URL
export HEALTH_CHECK_INTERVAL HEALTH_CHECK_TIMEOUT
export LLAMA_STARTUP_TIMEOUT EMBEDDINGS_STARTUP_TIMEOUT AIDB_STARTUP_TIMEOUT HYBRID_STARTUP_TIMEOUT
