# NixOS Configuration - AIDB Development Environment
# Generated by: nixos-quick-deploy.sh v@SCRIPT_VERSION@
# Generated: @GENERATED_AT@
# Hostname: @HOSTNAME@ | User: @USER@
# Target: NixOS 25.05+ with Wayland-first, security hardening
#
# Placeholder tokens (replaced via lib/config.sh → replace_placeholder):
#   @SCRIPT_VERSION@, @GENERATED_AT@, @HOSTNAME@, @USER@
#   @GITEA_ENABLE_FLAG@, @GITEA_ADMIN_VARIABLES_BLOCK@
#   @NVIDIA_ENABLE_BLOCK@, @AMD_ENABLE_BLOCK@, etc.
# The values are derived from config/variables.sh inputs and phase detection.
# =============================================================================

{ config, pkgs, lib, nixAiToolsPackages ? {}, ... }:

let
  huggingfaceStateDirName = "huggingface";
  huggingfaceDataDir = "/var/lib/${huggingfaceStateDirName}";
  huggingfaceCacheDir = "${huggingfaceDataDir}/cache";
  huggingfaceSecretDir = "/var/lib/nixos-quick-deploy/secrets";
  huggingfaceTokenEnvFile = "${huggingfaceSecretDir}/huggingface-tgi.env";
  huggingfaceModelId = "meta-llama/Meta-Llama-3-8B-Instruct";
  huggingfaceImage = "ghcr.io/huggingface/text-generation-inference:latest";
  qdrantStateDirName = "qdrant";
  qdrantStateDir = "/var/lib/${qdrantStateDirName}";
  qdrantContainerUid = "1000";
  qdrantContainerGid = "1000";
  qdrantStartScript = pkgs.writeShellScript "qdrant-start" ''
    set -euo pipefail

    state_root="''${STATE_DIRECTORY:-${qdrantStateDir}}"
    runtime_root="''${RUNTIME_DIRECTORY:-/run}"

    exec ${pkgs.podman}/bin/podman run \
      --cidfile="''${runtime_root}/qdrant.cid" \
      --conmon-pidfile="''${runtime_root}/qdrant.pid" \
      --rm \
      --name qdrant \
      --net host \
      -v "''${state_root}/storage:/qdrant/storage:U" \
      -e QDRANT__SERVICE__HOST=127.0.0.1 \
      -e QDRANT__SERVICE__HTTP_PORT=6333 \
      -e QDRANT__SERVICE__GRPC_PORT=6334 \
      -e QDRANT__TELEMETRY_DISABLED=true \
      docker.io/qdrant/qdrant:latest
  '';
  huggingfacePrepScript = pkgs.writeShellScript "huggingface-tgi-prep" ''
    set -euo pipefail
    state_root="''${STATE_DIRECTORY:-${huggingfaceDataDir}}"
    cache_root="''${CACHE_DIRECTORY:-${huggingfaceCacheDir}}"

    ${pkgs.coreutils}/bin/mkdir -p "${huggingfaceDataDir}" "${huggingfaceCacheDir}"
    ${pkgs.coreutils}/bin/mkdir -p "''${state_root}" "''${cache_root}"

    ${pkgs.podman}/bin/podman rm -f huggingface-tgi >/dev/null 2>&1 || true
    ${pkgs.podman}/bin/podman pull ${lib.escapeShellArg huggingfaceImage}
  '';
  huggingfaceStartScript = pkgs.writeShellScript "huggingface-tgi-start" ''
    set -euo pipefail
    state_root="''${STATE_DIRECTORY:-${huggingfaceDataDir}}"
    cache_root="''${CACHE_DIRECTORY:-${huggingfaceCacheDir}}"

    ${pkgs.coreutils}/bin/mkdir -p "${huggingfaceDataDir}" "${huggingfaceCacheDir}"
    ${pkgs.coreutils}/bin/mkdir -p "''${state_root}" "''${cache_root}"

    exec ${pkgs.podman}/bin/podman run \
      --rm \
      --name huggingface-tgi \
      --net host \
      -v "''${state_root}:/data" \
      -e HF_HOME=/data \
      -e HUGGINGFACE_HUB_CACHE=/data/cache \
      -e TRANSFORMERS_CACHE=/data/cache \
      ${lib.escapeShellArg huggingfaceImage} \
      --model-id ${lib.escapeShellArg huggingfaceModelId} \
      --port 8080 \
      --num-shard 1
  '';
  huggingfaceStopScript = pkgs.writeShellScript "huggingface-tgi-stop" ''
    ${pkgs.podman}/bin/podman stop huggingface-tgi >/dev/null 2>&1 || true
  '';
  ollamaStateDir = "/var/lib/ollama";
  giteaStateDir = "/var/lib/gitea";
  giteaAppDataDir = "${giteaStateDir}/data";
  giteaRepositoriesDir = "${giteaAppDataDir}/repositories";
  giteaLfsDir = "${giteaAppDataDir}/lfs";
  giteaIssuesIndexerPath = "${giteaAppDataDir}/indexers/issues.bleve";
  giteaRepoIndexerPath = "${giteaAppDataDir}/indexers/repos.bleve";
  giteaDatabasePath = "${giteaAppDataDir}/gitea.db";
  giteaEnabled = @GITEA_ENABLE_FLAG@;
  giteaDomain = "@HOSTNAME@";
  giteaHttpPort = 3000;
  giteaSshPort = 2222;
  giteaRootUrl = "http://${giteaDomain}:${toString giteaHttpPort}/";
  giteaAdminSecrets = @GITEA_ADMIN_SECRETS_SET@;
  giteaSharedSettings = {
    server = {
      PROTOCOL = "http";
      DOMAIN = giteaDomain;
      HTTP_ADDR = "0.0.0.0";
      HTTP_PORT = giteaHttpPort;
      ROOT_URL = giteaRootUrl;
      APP_DATA_PATH = giteaAppDataDir;
      ENABLE_GZIP = true;
      LFS_START_SERVER = true;
      DISABLE_SSH = false;
      SSH_DOMAIN = giteaDomain;
      SSH_PORT = giteaSshPort;
      SSH_LISTEN_HOST = "0.0.0.0";
      SSH_LISTEN_PORT = giteaSshPort;
      START_SSH_SERVER = true;
      LANDING_PAGE = "explore";
    };
    database = {
      DB_TYPE = "sqlite3";
      PATH = giteaDatabasePath;
      LOG_SQL = false;
    };
    repository = {
      ROOT = lib.mkForce giteaRepositoriesDir;
      FORCE_PRIVATE = false;
    };
    packages.ENABLED = true;
    actions = {
      ENABLED = true;
      # Gitea 1.25+ only accepts "github"/"internal" here; https://gitea.com now fails hard.
      DEFAULT_ACTIONS_URL = "github";
    };
    indexer = {
      ISSUE_INDEXER_TYPE = "bleve";
      ISSUE_INDEXER_PATH = giteaIssuesIndexerPath;
      REPO_INDEXER_ENABLED = true;
      REPO_INDEXER_PATH = giteaRepoIndexerPath;
    };
    ui = {
      DEFAULT_THEME = "arc-green";
      THEMES = "arc-green,auto,github";
      DEFAULT_SHOW_FULL_NAME = true;
    };
    service = {
      REGISTER_EMAIL_CONFIRM = false;
      DISABLE_REGISTRATION = false;
      REQUIRE_SIGNIN_VIEW = false;
      ENABLE_NOTIFY_MAIL = false;
    };
    security = {
      INSTALL_LOCK = true;
      PASSWORD_HASH_ALGO = "argon2";
    };
    log = {
      MODE = "console";
      LEVEL = "Info";
    };
  };
  # Optional Gitea admin bootstrap (populated by installer)
  @GITEA_ADMIN_VARIABLES_BLOCK@
  commonPythonOverrides = import ./python-overrides.nix;
  overridePythonPackages = pkgSet:
    if pkgSet ? overrideScope' then
      pkgSet.overrideScope' (self: super: commonPythonOverrides self super)
    else
      pkgSet;
  pythonOverridesOverlay =
    final: prev:
      (lib.optionalAttrs (prev ? python3Packages) {
        python3Packages = overridePythonPackages prev.python3Packages;
      })
      // (lib.optionalAttrs (prev ? python311Packages) {
        python311Packages = overridePythonPackages prev.python311Packages;
      })
      // (lib.optionalAttrs (prev ? python312Packages) {
        python312Packages = overridePythonPackages prev.python312Packages;
      })
      // (lib.optionalAttrs (prev ? python313Packages) {
        python313Packages = overridePythonPackages prev.python313Packages;
      })
      // (lib.optionalAttrs (prev ? python314Packages) {
        python314Packages = overridePythonPackages prev.python314Packages;
      });
  pythonPreferLatest =
    let
      envPref = builtins.getEnv "PYTHON_PREFER_PY314";
    in
    envPref == "1" || envPref == "true";
  python14CompatibilityMask = [
    "llvmlite"
    "numba"
    "sparse"
    "dask-ml"
    "dask-glm"
  ];
  python14Masked = python14CompatibilityMask != [ ];
  pythonRuntimeWithFallback =
    let
      python14Available = (pkgs ? python314) && (pkgs ? python314Packages);
    in
    if pythonPreferLatest && python14Available && !python14Masked then pkgs.python314 else pkgs.python313;
  @GLF_OS_DEFINITIONS@
in

{
  imports = [ ./hardware-configuration.nix ];

  # ============================================================================
  # Boot Configuration (Modern EFI)
  # ============================================================================
  boot = {
    loader = {
      systemd-boot.enable = lib.mkDefault true;
      efi.canTouchEfiVariables = lib.mkDefault true;
      # Security: Timeout for boot menu
      timeout = lib.mkDefault 3;
    };

    # Prefer the tuned 6.17 series first, then fall back to other low-latency kernels or latest upstream.
    kernelPackages = lib.mkDefault (
      if pkgs ? linuxPackages_6_17 then pkgs.linuxPackages_6_17
      else if pkgs ? linuxPackages_tkg then pkgs.linuxPackages_tkg
      else if pkgs ? linuxPackages_xanmod then pkgs.linuxPackages_xanmod
      else if pkgs ? linuxPackages_lqx then pkgs.linuxPackages_lqx
      else if pkgs ? linuxPackages_zen then pkgs.linuxPackages_zen
      else if pkgs ? linuxPackages_latest then pkgs.linuxPackages_latest
      else pkgs.linuxPackages
    );

    # CPU Microcode updates (auto-detected: @CPU_VENDOR_LABEL@ CPU)
    # Critical security and performance updates from CPU vendor
    @INITRD_KERNEL_MODULES@

    # Security: Enable kernel hardening
    kernelModules = [
      # Additional modules loaded after initial boot
@KERNEL_MODULES_PLACEHOLDER@
    ];
    kernel.sysctl = {
      # Security: Disable unprivileged BPF and user namespaces
      "kernel.unprivileged_bpf_disabled" = 1;
      # Rootless containers (Podman) require unprivileged user namespaces
      "kernel.unprivileged_userns_clone" = 1;
      "net.core.bpf_jit_harden" = 2;

      # GLF OS: Low-latency scheduling and memory tuning
      "kernel.split_lock_mitigate" = 0;
      "kernel.nmi_watchdog" = 0;
      "kernel.printk" = "3 3 3 3";
      "kernel.kptr_restrict" = 2;
      "kernel.kexec_load_disabled" = 1;
      "vm.swappiness" = 10;
      "vm.vfs_cache_pressure" = 50;
      "vm.dirty_bytes" = 268435456;
      "vm.dirty_background_bytes" = 67108864;
      "vm.dirty_writeback_centisecs" = 1500;
      "vm.max_map_count" = 16777216;

      # Performance: Network tuning for low latency
      "net.core.netdev_max_backlog" = 16384;
      "net.core.somaxconn" = 8192;
      "net.ipv4.tcp_fastopen" = 3;

      # Security: Harden TCP/IP stack
      "net.ipv4.tcp_syncookies" = 1;
      "net.ipv4.conf.default.rp_filter" = 1;
      "net.ipv4.conf.all.rp_filter" = 1;
@KERNEL_SYSCTL_TUNABLES@
    };

    # Hibernation support (resume from swap)
    # Populated automatically by the generator when swap-backed hibernation is enabled.
    @RESUME_DEVICE_DIRECTIVE@

    # Kernel parameters for better memory management and performance
    @BOOT_KERNEL_PARAMETERS_BLOCK@
  };
  @MICROCODE_SECTION@

  @GPU_HARDWARE_SECTION@

  # ===========================================================================
  # System Optimizations & Storage Maintenance (GLF OS inspired)
  # ===========================================================================
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 25;
    priority = 5;
  };

  services.fstrim = {
    enable = true;
    interval = "daily";
  };

  programs.appimage = {
    enable = true;
    binfmt = true;
  };

  # ============================================================================
  # Security Hardening
  # ============================================================================
  security = {
    # Sudo security
    sudo = {
      enable = true;
      execWheelOnly = true;  # Only wheel group can sudo
      wheelNeedsPassword = true;
    };
    # Polkit for privilege escalation (required for GUI apps)
    polkit.enable = true;
    # AppArmor for mandatory access control
    apparmor.enable = true;
  };

  # ============================================================================
  # Networking (Secure defaults)
  # ============================================================================
  networking = {
    hostName = "@HOSTNAME@";
    networkmanager.enable = true;

    # Firewall enabled by default with minimal ports
    firewall = {
      enable = true;
      allowedTCPPorts = [
        3000  # Gitea HTTP interface
        2222  # Gitea built-in SSH server
        19999 # Netdata monitoring dashboard
        # Add ports only when needed:
        # 8000  # AIDB API
        # 5432  # PostgreSQL
      ];
      # Default: Block all incoming, allow all outgoing
      # Explicitly log rejected packets for security monitoring
      logRefusedConnections = lib.mkDefault false;  # Set true for debugging
    };
  };

  # ============================================================================
  # Locale & Time (User-configured during setup)
  # ============================================================================
  time.timeZone = "@SELECTED_TIMEZONE@";  # Timezone selected during installation
  i18n.defaultLocale = lib.mkDefault "@CURRENT_LOCALE@";  # Auto-detected locale

  # Console configuration (TTY settings)
  console = {
    font = "Lat2-Terminus16";
    keyMap = lib.mkDefault "us";  # Keyboard layout for console
    # useXkbConfig = true;  # Uncomment to use X11 keymap settings in console
  };

  # ============================================================================
  # Users (Secure configuration)
  # ============================================================================

  # Allow users to change their passwords with passwd command
  # Set to false for fully declarative (passwords only from config)
  users.mutableUsers = @USERS_MUTABLE@;

  users.users."@USER@" = {
    isNormalUser = true;
    description = "@USER@";

    # Password configuration (migrated from existing system or preserved automatically)
@USER_PASSWORD_BLOCK@

    # Minimal groups: only what's needed
    extraGroups = [
      "networkmanager"  # Network configuration
      "wheel"           # Sudo access
      "podman"          # Rootless containers
      "video"           # Hardware video acceleration
      "audio"           # Audio device access
      "input"           # Input device access (for Wayland)
    ];
    # Note: "docker" group removed - use podman's dockerCompat instead
    shell = pkgs.zsh;

    # Optional: Auto-login (DISABLED by default for security)
    # Uncomment to enable auto-login without password prompt
    # WARNING: Only use on single-user systems with physical security

    # Allocate subordinate UID/GID ranges automatically (required for rootless Podman per the NixOS wiki)
    autoSubUidGidRange = true;
  };

  users.groups.accounts-daemon = lib.mkDefault { };
  users.users.accounts-daemon = lib.mkDefault {
    isSystemUser = true;
    description = "Accounts Service";
    group = "accounts-daemon";
  };

  # Enable ZSH system-wide
  programs.zsh.enable = true;

  # ============================================================================
  # FHS Compatibility - nix-ld
  # ============================================================================
  # nix-ld enables running non-NixOS binaries (like pre-built AI models,
  # proprietary ML frameworks, etc.) without modification
  # Essential for AI development where many tools distribute pre-compiled binaries
  #
  # Benefits:
  # - Run pre-built LLM inference engines
  # - Use proprietary AI frameworks without patches
  # - Simpler than Docker for single binaries
  # - Transparent to applications (no wrapper needed)
  #
  # Usage: Just run the binary normally - nix-ld handles library loading

  programs.nix-ld = {
    enable = true;

    # Automatically include common libraries that AI/ML tools need
    libraries = with pkgs; [
      # C/C++ standard libraries
      stdenv.cc.cc.lib
      zlib

      # Common dependencies for AI/ML binaries
      glibc
      gcc-unwrapped.lib

      # Graphics and compute (for GPU-accelerated AI)
      mesa
      libglvnd

      # Additional common libraries
      openssl
      curl
      libxml2
      libxcrypt
    ];
  };

  # ============================================================================
  # Home Manager
  # ============================================================================

  # Home Manager integration is provided by the generated flake (see flake.nix)
  # The flake adds home-manager.nixosModules.home-manager and imports ./home.nix

  # ============================================================================
  # Nix Configuration (Modern settings)
  # ============================================================================
  nix = {
    settings = {
      # Modern features
      experimental-features = [ "nix-command" "flakes" ];

      # Build parallelism guardrail: @NIX_PARALLEL_COMMENT@
      max-jobs = @NIX_MAX_JOBS@;
      cores = @NIX_BUILD_CORES@;

      # Performance & security
      auto-optimise-store = true;
      trusted-users = [ "root" "@wheel" ];

      # Security: Restrict nix-daemon network access
      allowed-users = [ "@wheel" ];
@BINARY_CACHE_SETTINGS@
    };

    # Automatic garbage collection
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };

    # Optimize store on every build
    optimise = {
      automatic = true;
      dates = [ "weekly" ];
    };
  };

  nixpkgs.config.allowUnfree = true;
  nixpkgs.overlays = [ pythonOverridesOverlay ];

  # ============================================================================
  # Package Overrides (Fix build issues)
  # ============================================================================
  nixpkgs.config.packageOverrides = pkgs: {
    # Apply common Python overrides that disable flaky build-time tests.
    pythonAi = pythonRuntimeWithFallback.override {
      packageOverrides = commonPythonOverrides;
    };
  };

  # ============================================================================
  # AIDB: Podman Virtualization (Rootless, secure containers)
  # ============================================================================
  # Modern NixOS 25.05+ container configuration
  virtualisation = {
    containers.enable = true;  # Required for Podman per https://wiki.nixos.org/wiki/Podman
    podman = {
      enable = true;

      # Docker CLI compatibility (no docker daemon)
      dockerCompat = true;

      # Enable Podman socket for podman-compose and docker-compose
      dockerSocket.enable = true;

      # Default network DNS for container name resolution
      defaultNetwork.settings.dns_enabled = true;

      # Automatic cleanup of unused images/containers
      autoPrune = {
        enable = true;
        dates = "weekly";
        flags = [ "--all" ];  # Remove all unused images, not just dangling
      };

      # Rootless networking helper (vfs storage by default)
      extraPackages = with pkgs; [
        slirp4netns
      ];
    };
  };

  # ============================================================================
  # Podman Storage Configuration (auto-detected)
  # ============================================================================
@PODMAN_STORAGE_BLOCK@

  @GLF_GAMING_STACK_SECTION@

  # ========================================================================
  # Local AI Runtime (Hugging Face & Ollama)
  # ========================================================================

  services.ollama = {
    enable = true;
    package = pkgs.ollama;
  };

  systemd.services.ollama = {
    environment = {
      HF_HOME = huggingfaceDataDir;
      HUGGINGFACE_HUB_CACHE = huggingfaceCacheDir;
      TRANSFORMERS_CACHE = huggingfaceCacheDir;
    };
    unitConfig = {
      # Increase restart limits for large system changes
      StartLimitBurst = 10;
      StartLimitIntervalSec = 900;  # 15 minutes
    };
    serviceConfig = {
      # Increase timeouts to handle slow starts during system changes
      RestartSec = 30;
      TimeoutStartSec = 300;  # 5 minutes
      MemoryAccounting = lib.mkForce true;
      IOAccounting = lib.mkForce true;
      TasksAccounting = lib.mkForce true;
      LimitNOFILE = lib.mkForce 1048576;
      LimitNPROC = lib.mkForce 8192;
      # Hardening
      ProtectSystem = lib.mkForce "full";
      ProtectHome = lib.mkForce true;
      ProtectControlGroups = lib.mkForce true;
      ProtectKernelLogs = lib.mkForce true;
      ProtectKernelModules = lib.mkForce true;
      ProtectKernelTunables = lib.mkForce true;
      ProtectClock = lib.mkForce true;
      PrivateTmp = lib.mkForce true;
      PrivateDevices = lib.mkForce true;
      PrivateMounts = lib.mkForce true;
      NoNewPrivileges = lib.mkForce true;
      LockPersonality = lib.mkForce true;
      MemoryDenyWriteExecute = lib.mkForce true;
      RestrictAddressFamilies = lib.mkForce [ "AF_UNIX" "AF_INET" "AF_INET6" ];
      RestrictRealtime = lib.mkForce true;
      RestrictSUIDSGID = lib.mkForce true;
      SystemCallArchitectures = lib.mkForce "native";
      SystemCallFilter = lib.mkForce [ "@system-service" "~@privileged" ];
      ProcSubset = lib.mkForce "pid";
      ProtectProc = lib.mkForce "invisible";
      UMask = lib.mkForce "0077";
      ReadWritePaths = lib.mkForce [
        ollamaStateDir
      ];
    };
  };

  # ========================================================================
  # Qdrant Vector Database Service
  # ========================================================================
  # Qdrant service module doesn't exist in NixOS 25.05, so we create a custom systemd service
  systemd.services.qdrant = {
    description = "Qdrant Vector Database";
    documentation = [
      "https://qdrant.tech/documentation/"
      "https://search.nixos.org/options?channel=25.05&show=systemd.services"
    ];
    # Enabled by default so vector search is available immediately after rebuilds
    wantedBy = [ "multi-user.target" ];
    wants = [ "network-online.target" "podman.service" "podman.socket" ];
    after = [ "network-online.target" "podman.service" "podman.socket" ];
    unitConfig = {
      # Increase restart limits for large system changes
      StartLimitBurst = 10;
      StartLimitIntervalSec = 900;  # 15 minutes
    };
    environment = {
      PODMAN_SYSTEMD_UNIT = "%n";
      XDG_RUNTIME_DIR = "/run/podman";
    };
    preStart = ''
      set -euo pipefail

      state_root="''${STATE_DIRECTORY:-${qdrantStateDir}}"
      runtime_root="''${RUNTIME_DIRECTORY:-/run}"

      ${pkgs.coreutils}/bin/install -d -m 0755 /run/podman
      ${pkgs.coreutils}/bin/install -d -m 0775 "''${state_root}/storage"
      ${pkgs.coreutils}/bin/chown -R ${qdrantContainerUid}:${qdrantContainerGid} "''${state_root}/storage"
      # Remove stale runtime files from previous runs; podman exits with code 125 if
      # the cidfile or pidfile already exists.
      ${pkgs.coreutils}/bin/rm -f "''${runtime_root}/qdrant.cid" "''${runtime_root}/qdrant.pid"
    '';
    serviceConfig = {
      Type = "simple";
      ExecStartPre = [
        "${pkgs.podman}/bin/podman stop --ignore --time 10 qdrant"
        "${pkgs.podman}/bin/podman rm --ignore -f qdrant"
        "${pkgs.podman}/bin/podman pull --quiet docker.io/qdrant/qdrant:latest"
      ];
      ExecStart = qdrantStartScript;
      ExecStop = "${pkgs.podman}/bin/podman stop --ignore --time 10 qdrant";
      ExecStopPost = "${pkgs.podman}/bin/podman rm --ignore -f qdrant";
      Restart = "on-failure";
      RestartSec = 30;  # Increased from 15
      TimeoutStartSec = 300;  # Increased from 120 (5 minutes)
      TimeoutStopSec = 60;  # Increased from 30
      WorkingDirectory = qdrantStateDir;
      StateDirectory = qdrantStateDirName;
      StateDirectoryMode = "0775";
      RuntimeDirectory = "qdrant";
      MemoryAccounting = lib.mkForce true;
      IOAccounting = lib.mkForce true;
      TasksAccounting = lib.mkForce true;
      LimitNOFILE = lib.mkForce 262144;
      LimitNPROC = lib.mkForce 16384;
      # Podman needs access to cgroups, /sys, and netlink sockets while launching
      # the container. Drop the aggressive sandbox toggles so the service can
      # configure networking and overlay storage without tripping permission
      # errors (systemd would otherwise block qdrant with exit code 125).
      ProtectSystem = lib.mkForce false;
      ProtectHome = lib.mkForce false;
      ProtectControlGroups = lib.mkForce false;
      ProtectKernelLogs = lib.mkForce false;
      ProtectKernelModules = lib.mkForce false;
      ProtectKernelTunables = lib.mkForce false;
      PrivateTmp = lib.mkForce false;
      PrivateMounts = lib.mkForce false;
      NoNewPrivileges = lib.mkForce false;
      LockPersonality = lib.mkForce false;
      MemoryDenyWriteExecute = lib.mkForce false;
      RestrictAddressFamilies = lib.mkForce [ "AF_UNIX" "AF_INET" "AF_INET6" "AF_NETLINK" "AF_PACKET" ];
      RestrictRealtime = lib.mkForce false;
      RestrictSUIDSGID = lib.mkForce false;
      ProtectProc = lib.mkForce "default";
      UMask = lib.mkForce "0027";
      ReadWritePaths = lib.mkForce [
        qdrantStateDir
        "/var/lib/containers"
        "/run/libpod"
        "/run/podman"
        "/run/qdrant"
      ];
    };
  };

  systemd.services.huggingface-tgi = {
    description = "Hugging Face Text Generation Inference";
    documentation = [
      "https://huggingface.co/docs/text-generation-inference/en/index"
      "https://search.nixos.org/options?channel=25.05&show=systemd.services"
    ];
    # Disabled by default - enable manually with: sudo systemctl enable --now huggingface-tgi
    # wantedBy = [ "multi-user.target" ];
    wants = [ "network-online.target" "podman.service" "podman.socket" ];
    after = [ "network-online.target" "podman.service" "podman.socket" ];
    restartTriggers = [ huggingfaceStartScript huggingfacePrepScript huggingfaceStopScript ];
    unitConfig = {
      # Increase restart limits for large system changes
      StartLimitBurst = 10;
      StartLimitIntervalSec = 900;  # 15 minutes
    };
    serviceConfig = {
      Type = "simple";
      ExecStartPre = [ huggingfacePrepScript ];
      ExecStart = huggingfaceStartScript;
      ExecStop = huggingfaceStopScript;
      Restart = "on-failure";
      RestartSec = 30;  # Increased from 15
      TimeoutStartSec = 900;  # Increased from 600 (15 minutes for large models)
      TimeoutStopSec = 120;  # Increased from 90
      WorkingDirectory = "%S/${huggingfaceStateDirName}";
      StateDirectory = huggingfaceStateDirName;
      MemoryAccounting = lib.mkForce true;
      IOAccounting = lib.mkForce true;
      TasksAccounting = lib.mkForce true;
      LimitNOFILE = lib.mkForce 262144;
      LimitNPROC = lib.mkForce 16384;
      ProtectSystem = lib.mkForce "full";
      ProtectHome = lib.mkForce true;
      ProtectControlGroups = lib.mkForce true;
      ProtectKernelLogs = lib.mkForce true;
      ProtectKernelModules = lib.mkForce true;
      ProtectKernelTunables = lib.mkForce true;
      ProtectClock = lib.mkForce true;
      PrivateTmp = lib.mkForce true;
      PrivateMounts = lib.mkForce true;
      NoNewPrivileges = lib.mkForce true;
      LockPersonality = lib.mkForce true;
      MemoryDenyWriteExecute = lib.mkForce true;
      RestrictAddressFamilies = lib.mkForce [ "AF_UNIX" "AF_INET" "AF_INET6" ];
      RestrictRealtime = lib.mkForce true;
      RestrictSUIDSGID = lib.mkForce true;
      SystemCallArchitectures = lib.mkForce "native";
      ProcSubset = lib.mkForce "pid";
      ProtectProc = lib.mkForce "invisible";
      UMask = lib.mkForce "0077";
      ReadWritePaths = lib.mkForce [
        huggingfaceDataDir
        huggingfaceCacheDir
        huggingfaceSecretDir
        "/var/lib/containers"
        "/run/libpod"
        "/run/podman"
      ];
      EnvironmentFile = [ "-${huggingfaceTokenEnvFile}" ];
    };
    environment = {
      HF_HOME = "%S/${huggingfaceStateDirName}";
      HUGGINGFACE_HUB_CACHE = "%S/${huggingfaceStateDirName}/cache";
      TRANSFORMERS_CACHE = "%S/${huggingfaceStateDirName}/cache";
    };
  };

  # ========================================================================
  # Self-hosted Git Service (Gitea)
  # ========================================================================

  services.gitea = lib.mkIf giteaEnabled {
    enable = true;
    appName = "AIDB Gitea";
    package = pkgs.gitea;
    user = "gitea";
    group = "gitea";
    lfs = {
      enable = true;
      contentDir = giteaLfsDir;
    };
    # NixOS 25.05+: stateDir is managed automatically, don't set it explicitly
    # The state directory will be /var/lib/gitea by default
    database = {
      type = "sqlite3";
      path = giteaDatabasePath;
    };
    # NixOS 25.05+: repositoryRoot is deprecated, use settings.repository.ROOT instead
    # NixOS 25.05+: Use settings.server for HTTP configuration (see giteaSharedSettings)
    # Deprecated options removed: rootUrl, httpAddress, httpPort, disableRegistration, stateDir, repositoryRoot
    # SSH configuration moved to settings.server (see giteaSharedSettings above)
    # NixOS 25.05+ uses freeform settings instead of structured ssh block
    # All service settings configured via settings attribute (see giteaSharedSettings)
    settings = giteaSharedSettings;
  };

  # Systemd service overrides for gitea to handle large system changes
  systemd.services.gitea = lib.mkIf giteaEnabled {
    unitConfig = {
      # Increase restart limits for large system changes
      # Gitea may need multiple restart attempts after major system updates
      StartLimitBurst = 10;
      StartLimitIntervalSec = 900;  # 15 minutes
    };
    serviceConfig = {
      # Increase timeouts and resource accounting
      RestartSec = 30;  # Wait 30 seconds between restart attempts
      TimeoutStartSec = 300;  # Allow up to 5 minutes for service to start
      TimeoutStopSec = 60;  # Allow up to 1 minute for service to stop
      MemoryAccounting = lib.mkForce true;
      IOAccounting = lib.mkForce true;
      TasksAccounting = lib.mkForce true;
      MemoryHigh = lib.mkForce "85%";
      # Harden the application surface
      ProtectSystem = lib.mkForce "strict";
      ProtectHome = lib.mkForce true;
      ProtectControlGroups = lib.mkForce true;
      ProtectKernelModules = lib.mkForce true;
      ProtectKernelLogs = lib.mkForce true;
      ProtectKernelTunables = lib.mkForce true;
      ProtectClock = lib.mkForce true;
      PrivateTmp = lib.mkForce true;
      PrivateMounts = lib.mkForce true;
      PrivateDevices = lib.mkForce true;
      NoNewPrivileges = lib.mkForce true;
      LockPersonality = lib.mkForce true;
      MemoryDenyWriteExecute = lib.mkForce true;
      RestrictAddressFamilies = lib.mkForce [ "AF_UNIX" "AF_INET" "AF_INET6" ];
      RestrictRealtime = lib.mkForce true;
      RestrictSUIDSGID = lib.mkForce true;
      SystemCallArchitectures = lib.mkForce "native";
      SystemCallFilter = lib.mkForce [ "@system-service" "~@privileged" ];
      ProcSubset = lib.mkForce "pid";
      ProtectProc = lib.mkForce "invisible";
      UMask = lib.mkForce "0027";
      CapabilityBoundingSet = lib.mkForce [ "" ];
      AmbientCapabilities = lib.mkForce [ ];
      ReadWritePaths = lib.mkForce [
        giteaStateDir
        giteaAppDataDir
        giteaRepositoriesDir
        giteaLfsDir
      ];
    };
  };

  @GITEA_ADMIN_SERVICE_BLOCK@

  # ============================================================================
  # COSMIC Desktop Environment (Wayland-native)
  # ============================================================================
  # NixOS 25.05+ modern configuration
  # 100% Wayland-native - No X11/XWayland needed for this configuration
  # All applications configured for native Wayland support

  services.desktopManager.cosmic = {
    enable = true;

    # Optional: XWayland support for legacy X11 applications (DISABLED)
    # Uncomment ONLY if you need to run proprietary X11-only software
    # Examples: Some game launchers, proprietary CAD software, older apps
    # Note: Adds security risk (X11 less secure than Wayland)
    # xwayland.enable = false;

    # Optional: Exclude default COSMIC applications (NixOS 25.11+)
    # COSMIC desktop automatically includes: cosmic-settings, cosmic-notification-daemon,
    # cosmic-files, cosmic-edit, cosmic-terminal, and other core applications
    # Uncomment the section below in NixOS 25.11+ to prevent duplicates in application menu
    #
    # NOTE: This option is NOT available in NixOS 25.05
    # If using 25.05 and experiencing duplicate apps, upgrade to 25.11 or later
    #
    # excludePackages = with pkgs; [
    #   cosmic-settings
    #   cosmic-notification-daemon
    #   cosmic-launcher
    #   cosmic-files
    #   cosmic-edit
    #   cosmic-terminal
    # ];
  };

  services.displayManager = {
    # COSMIC Greeter (Wayland-native login screen)
    cosmic-greeter.enable = true;

    # Optional: Set default desktop session (DISABLED - not needed)
    # Uncomment ONLY if you install multiple desktop environments
    # Ensures COSMIC loads by default instead of others (GNOME, KDE, etc)
    # Since only COSMIC is installed, this setting is redundant
    # defaultSession = "cosmic";

    # Optional: Auto-login to skip password prompt (DISABLED for security)
    # Uncomment to boot directly to desktop without login screen
    # WARNING: Only use on single-user systems with physical security!
    # Bypasses password authentication - creates security risk
    # autoLogin = {
    #   enable = true;
    #   user = "@USER@";
    # };
  };

  # Provide a bleeding-edge tiling Wayland session alongside COSMIC.
  programs.hyprland = {
    enable = true;
    package = pkgs.hyprland;
    portalPackage = pkgs.xdg-desktop-portal-hyprland;
  };

  # Ensure Wayland portals stay current for COSMIC + Hyprland workflows.
  xdg.portal = {
    enable = true;
    extraPortals =
      [ pkgs.xdg-desktop-portal-hyprland pkgs.xdg-desktop-portal-gnome ]
      ++ lib.optionals (pkgs ? xdg-desktop-portal-cosmic) [ pkgs.xdg-desktop-portal-cosmic ];
  };

  # Wayland-specific optimizations and COSMIC configuration
  environment.sessionVariables = {
    # Force Wayland for Qt apps
    QT_QPA_PLATFORM = "wayland";
    # Force Wayland for SDL2 apps
    SDL_VIDEODRIVER = "wayland";
    # Firefox Wayland
    MOZ_ENABLE_WAYLAND = "1";
    # Electron apps (VSCodium, etc)
    NIXOS_OZONE_WL = "1";

    # COSMIC-specific: Enable clipboard functionality
    # Required for cosmic-clipboard to work with wl-clipboard
    COSMIC_DATA_CONTROL_ENABLED = "1";
    STEAM_EXTRA_COMPAT_TOOLS_PATHS = "$HOME/.steam/root/compatibilitytools.d";
    MANGOHUD = if glfMangoHudInjectsIntoApps then "1" else "0";
    MANGOHUD_CONFIG = glfMangoHudConfig;
    MANGOHUD_DESKTOP_MODE = if glfMangoHudDesktopMode then "1" else "0";
    @GPU_SESSION_VARIABLES@
  };

  @LACT_SERVICE_BLOCK@

  # ============================================================================
  # System Packages (System-level only)
  # ============================================================================
  # Note: Development tools (git, vim, etc.) are installed via home-manager
  # This prevents package collisions and allows per-user customization
  #
  # IMPORTANT: COSMIC desktop apps (cosmic-edit, cosmic-files, cosmic-term, etc.)
  # are AUTOMATICALLY included when services.desktopManager.cosmic.enable = true
  # DO NOT add them here - it creates duplicates!
  #
  # USER CUSTOMIZATION ENTRY POINT:
  #   - Adjust the lists below to tailor global system packages
  #   - Keep GUI/desktop apps in home-manager or Flatpak unless required system-wide
  #   - Leave jq (and other preflight CLIs) enabled so deployment phases succeed
  environment.systemPackages = with pkgs;
    [
      # COSMIC App Store (not auto-included, needs explicit installation)
      cosmic-store

      # COSMIC Settings (explicitly included to ensure settings daemon is available)
      # This fixes issues with cosmic-settings-daemon not being found during startup
    ]
    ++ lib.optionals (pkgs ? cosmic-settings) [ pkgs.cosmic-settings ]
    ++ lib.optional (lib.hasAttr "default" nixAiToolsPackages)
      nixAiToolsPackages.default  # Provide CLI helpers from numtide/nix-ai-tools when available
    ++ @GPU_DRIVER_PACKAGES@
    ++ glfSystemUtilities
    ++ glfGamingPackages
    ++ [
      # Preflight CLI dependencies (available before Home Manager activation)
      jq

      # Container tools (system-level for rootless podman)
      podman
      podman-compose
      buildah
      skopeo
      crun
      slirp4netns

      # Hardware detection tools (for GPU detection in deployment script)
      pciutils  # Provides lspci for hardware detection

      # Essential system utilities only
      # All other tools installed via home-manager to prevent collisions
    ];

  # ============================================================================
  # Shell Configuration
  # ============================================================================
  # Add shells to /etc/shells to allow chsh to set them as login shells
  environment.shells = with pkgs; [
    bash
    zsh
  ];

  # ============================================================================
  # Fonts (Required for Cosmic and development)
  # ============================================================================
  fonts.packages = with pkgs; [
    nerd-fonts.meslo-lg
    nerd-fonts.fira-code
    nerd-fonts.jetbrains-mono
    nerd-fonts.hack
    font-awesome
    powerline-fonts
  ];

  # ============================================================================
  # Audio (Modern PipeWire - NixOS 25.05+)
  # ============================================================================
  # PipeWire: Modern, low-latency audio/video routing
  # Replaces PulseAudio and JACK with better Wayland integration

  # Disable legacy audio systems (NixOS 25.05+ uses services.pulseaudio)
  services.pulseaudio.enable = false;

  # Enable real-time audio scheduling (required for low latency)
  security.rtkit.enable = true;

  services.pipewire = {
    enable = true;

    # ALSA support (direct hardware access)
    alsa = {
      enable = true;
      support32Bit = true;  # For 32-bit games/apps
    };

    # PulseAudio compatibility layer
    pulse.enable = true;

    # JACK audio (professional audio production)
    jack.enable = true;

    # WirePlumber: Modern session manager for PipeWire
    wireplumber.enable = true;
  };

  # ============================================================================
  # Printing
  # ============================================================================
  services.printing.enable = true;
  systemd.sockets.cups.listenStreams = lib.mkForce [
    "/run/cups/cups.sock"
    "127.0.0.1:631"
  ];

  # ============================================================================
  # Flatpak (Required for COSMIC App Store)
  # ============================================================================
  services.flatpak.enable = true;

  # Note: After system rebuild, run this command as your user to add Flathub:
  # flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  # ============================================================================
  # System Monitoring Tools (GNOME-like Features)
  # ============================================================================
  # Resources: Modern system monitor similar to GNOME Settings
  #   - CPU, GPU, RAM, disk monitoring
  #   - Network statistics
  #   - Sensor readings (temperature, fan speed)
  #   - Process information (like GNOME Task Manager)
  #   - Clean, modern GTK 4 interface with libadwaita
  #
  # Installation: Available via Flatpak home-manager
  #   Uncomment in ~/.config/home-manager/home.nix:
  #   "net.nokyan.Resources"  # System resource monitor
  #
  # Alternative system monitoring services (optional - commented out):

  # GNOME Shell (for extensions like system monitor bar)
  # Uncomment if you want GNOME Shell in addition to COSMIC:
  # services.displayManager.gdm.enable = false;  # Disable if using COSMIC only
  # services.gnome.core-utilities.enable = false;

  # Dbus (Required for many system services and monitor integration)
  services.dbus.enable = true;

  # UPower (Power management and battery monitoring - integrated with monitors)
  services.upower.enable = true;

  # Bluetooth (For wireless device monitoring)
  services.blueman.enable = true;

  # Thermald (Intel thermal management - auto-thermal throttling)
  # Enabled automatically on Intel systems for temperature management
  services.thermald.enable = true;

  # ============================================================================
  # Geolocation Services (For COSMIC auto day/night theme)
  # ============================================================================
  # GeoClue2: Provides geolocation services for automatic timezone/theme
  # Used by COSMIC for:
  # - Automatic day/night theme switching based on sunrise/sunset
  # - Location-aware timezone detection
  # - Weather information (if installed)
  services.geoclue2 = {
    enable = true;
    enableWifi = true;
    
    # Location services can access your geolocation - configure privacy:
    # Allow only specific applications to access location
    geoProviderUrl = "https://api.beacondb.net/v1/geolocate";
    submitData = false;
    appConfig = {  
        # Allow COSMIC Settings to access location for theme switching
        #"cosmic-settings" = {
        #  isAllowed = true;
        #  isSystem = true;
      #};
    };
  };

  # ============================================================================
  # Memory Management & Swap
  # ============================================================================
@SWAP_AND_HIBERNATION_BLOCK@

  # ============================================================================
  # Additional Services (Code Review Recommendations)
  # ============================================================================

  # Netdata - Real-time Performance Monitoring
  # Lightweight, zero-config monitoring with beautiful dashboards
  # Resource usage: ~100-150MB RAM, <3% CPU
  # Features: Auto-discovery, ML anomaly detection, built-in alerts
  # Access: http://localhost:19999 (after enabling)
  services.netdata = {
    enable = true;
    package = pkgs.netdata;

    config = {
      global = {
        # Memory mode: Use dbengine for persistent metrics storage
        "memory mode" = "dbengine";

        # Database engine settings (optimized for development workstation)
        "page cache size" = "32";           # RAM cache in MB (32MB is good for single node)
        "dbengine disk space" = "256";      # Disk space for metrics in MB (256MB = ~1 day retention)

        # Update frequency (1 second = real-time monitoring)
        "update every" = "1";

        # History retention in RAM (3600 seconds = 1 hour)
        "history" = "3600";
      };

      web = {
        # Bind to localhost only (change to 0.0.0.0 if accessing from network)
        "bind to" = "127.0.0.1";

        # Default port
        "default port" = "19999";
      };

      # Plugin configuration
      plugins = {
        # Enable all plugins for comprehensive monitoring
        "checks" = "yes";
        "apps" = "yes";
        "cgroups" = "yes";
        "proc" = "yes";
        "diskspace" = "yes";
      };
    };
  };

  systemd.services."accounts-daemon" = {
    serviceConfig = {
      StateDirectory = "AccountsService";
      RuntimeDirectory = "AccountsService";
      MemoryAccounting = lib.mkForce true;
      IOAccounting = lib.mkForce true;
      TasksAccounting = lib.mkForce true;
      ProtectSystem = lib.mkForce "strict";
      ProtectHome = lib.mkForce true;
      ProtectKernelLogs = lib.mkForce true;
      ProtectKernelTunables = lib.mkForce true;
      ProtectClock = lib.mkForce true;
      PrivateTmp = lib.mkForce true;
      NoNewPrivileges = lib.mkForce true;
      LockPersonality = lib.mkForce true;
      MemoryDenyWriteExecute = lib.mkForce true;
      RestrictAddressFamilies = lib.mkForce [ "AF_UNIX" ];
      RestrictRealtime = lib.mkForce true;
      RestrictSUIDSGID = lib.mkForce true;
      SystemCallArchitectures = lib.mkForce "native";
      ProcSubset = lib.mkForce "pid";
      ProtectProc = lib.mkForce "invisible";
      UMask = lib.mkForce "0077";
      ReadWritePaths = lib.mkForce [
        "/var/lib/AccountsService"
      ];
    };
  };

  systemd.services.netdata.serviceConfig = {
    StateDirectory = "netdata";
    RuntimeDirectory = "netdata";
    CacheDirectory = "netdata";
    LogsDirectory = "netdata";
  };

  systemd.tmpfiles.rules = lib.mkAfter (
    [
      "d /run/podman 0755 root root -"
      "d ${huggingfaceSecretDir} 0700 root root -"
      "Z /var/lib/AccountsService 0750 accounts-daemon accounts-daemon -"
      "Z /var/lib/AccountsService/icons 0750 accounts-daemon accounts-daemon -"
      "Z ${giteaStateDir} 0750 gitea gitea -"
      "Z ${giteaStateDir}/custom 0750 gitea gitea -"
      "Z ${giteaStateDir}/custom/conf 0750 gitea gitea -"
      "z ${giteaStateDir}/custom/conf/app.ini 0640 gitea gitea -"
      ''f ${giteaStateDir}/custom/conf/secret_key 0600 gitea gitea - "@GITEA_SECRET_KEY@"''
      ''f ${giteaStateDir}/custom/conf/internal_token 0600 gitea gitea - "@GITEA_INTERNAL_TOKEN@"''
      ''f ${giteaStateDir}/custom/conf/oauth2_jwt_secret 0600 gitea gitea - "@GITEA_JWT_SECRET@"''
      ''f ${giteaStateDir}/custom/conf/lfs_jwt_secret 0600 gitea gitea - "@GITEA_LFS_JWT_SECRET@"''
    ]
    ++ lib.optionals giteaEnabled [
      "d /var/lib/gitea 0750 gitea gitea -"
      "d /var/lib/gitea/custom 0750 gitea gitea -"
      "d /var/lib/gitea/custom/conf 0750 gitea gitea -"
    ]
  );

  # PostgreSQL for production-grade AI applications
  # Disabled by default - enable with: sudo systemctl enable --now postgresql
  services.postgresql = {
    enable = false;  # Set to true to enable
    package = pkgs.postgresql_16;
    enableTCPIP = true;
    authentication = pkgs.lib.mkOverride 10 ''
      local all all trust
      host all all 127.0.0.1/32 scram-sha-256
      host all all ::1/128 scram-sha-256
    '';
    settings = {
      shared_buffers = "256MB";
      effective_cache_size = "1GB";
      work_mem = "16MB";
      maintenance_work_mem = "128MB";
      max_connections = 100;
    };
    initialScript = pkgs.writeText "postgres-init.sql" ''
      CREATE DATABASE aidb;
      CREATE USER aidb WITH PASSWORD 'changeme';
      GRANT ALL PRIVILEGES ON DATABASE aidb TO aidb;
    '';
  };

  # Redis for caching and message queues
  # Disabled by default - enable with: sudo systemctl enable --now redis
  services.redis.servers."default" = {
    enable = false;  # Set to true to enable
    port = 6379;
    bind = "127.0.0.1";
    save = [
      [900 1]    # Save after 900 sec if at least 1 key changed
      [300 10]   # Save after 300 sec if at least 10 keys changed
      [60 10000] # Save after 60 sec if at least 10000 keys changed
    ];
    settings = {
      maxmemory = "512mb";
      maxmemory-policy = "allkeys-lru";
    };
  };

  # Nginx for reverse proxy and static file serving
  # Disabled by default - configure as needed for your AI services
  services.nginx = {
    enable = false;  # Set to true to enable
    recommendedProxySettings = true;
    recommendedTlsSettings = true;
    recommendedOptimisation = true;
    recommendedGzipSettings = true;

    # Example configuration for proxying AI services
    virtualHosts."localhost" = {
      locations."/" = {
        proxyPass = "http://127.0.0.1:8000";  # Example: Your AI API
        proxyWebsockets = true;
      };
      # locations."/ollama/" = {
      #   proxyPass = "http://127.0.0.1:11434";
      # };
    };
  };

  # Prometheus for monitoring
  # Disabled by default - enable for production monitoring
  services.prometheus = {
    enable = false;  # Set to true to enable
    port = 9090;
    exporters = {
      node = {
        enable = false;  # Set to true to enable
        enabledCollectors = [ "systemd" "processes" "cpu" "meminfo" "diskstats" ];
        port = 9100;
      };
    };
    scrapeConfigs = [
      {
        job_name = "node";
        static_configs = [{
          targets = [ "localhost:9100" ];
        }];
      }
    ];
  };

  # Grafana for metrics visualization
  # Disabled by default - enable for monitoring dashboards
  services.grafana = {
    enable = false;  # Set to true to enable
    settings = {
      server = {
        http_addr = "127.0.0.1";
        http_port = 3001;  # Gitea uses 3000
        domain = "localhost";
      };
      analytics.reporting_enabled = false;
      security = {
        admin_user = "admin";
        admin_password = "changeme";  # Change this!
      };
    };
    provision = {
      enable = true;
      datasources.settings.datasources = [
        {
          name = "Prometheus";
          type = "prometheus";
          url = "http://localhost:9090";
          isDefault = true;
        }
      ];
    };
  };

  # Fail2ban for SSH protection
  # Disabled by default - enable for enhanced security
  services.fail2ban = {
    enable = false;  # Set to true to enable
    maxretry = 3;
    bantime = "1h";
    ignoreIP = [
      "127.0.0.1"
      "::1"
      "192.168.1.0/24"  # Adjust for your local network
    ];
    jails = {
      sshd = ''
        enabled = true
        port = ssh
        filter = sshd
        logpath = /var/log/auth.log
        maxretry = 3
      '';
    };
  };

  # Automatic system updates
  # Disabled by default - enable for automatic security updates
  system.autoUpgrade = {
    enable = false;  # Set to true to enable
    allowReboot = false;  # Set to true for servers
    channel = "https://nixos.org/channels/nixos-@NIXOS_VERSION@";
    dates = "weekly";
    randomizedDelaySec = "1h";
  };

  # ============================================================================
  # System & Home Manager Version
  # ============================================================================
  system.stateVersion = "@STATE_VERSION@";
}
