#!/usr/bin/env python3
"""GENERATED by scripts/ai/gen-api-client.py — do not edit by hand.

Typed client for the Command Center dashboard API (OpenAPI-first, WS6).
Regenerate with: python3 scripts/ai/gen-api-client.py
"""
from __future__ import annotations
import json as _json
import urllib.parse as _urlparse
import urllib.request as _urlreq
from typing import Any


class AqDashboardClient:
    """Generated typed client. One method per /api GET route."""

    def __init__(self, base_url: str = "http://127.0.0.1:8889", timeout: float = 10.0):
        self.base_url = base_url.rstrip('/')
        self.timeout = timeout

    def _get(self, path: str, params: dict | None = None) -> Any:
        url = self.base_url + path
        if params:
            url += '?' + _urlparse.urlencode({k: v for k, v in params.items() if v is not None})
        with _urlreq.urlopen(url, timeout=self.timeout) as r:
            return _json.loads(r.read())

    def get_actions(self) -> Any:
        """List Actions"""
        return self._get("/api/actions/")

    def get_adk_discoveries(self) -> Any:
        """Get Discoveries"""
        return self._get("/api/adk/discoveries")

    def get_adk_gaps(self) -> Any:
        """Get Gaps"""
        return self._get("/api/adk/gaps")

    def get_adk_integrations(self) -> Any:
        """Get Integrations"""
        return self._get("/api/adk/integrations")

    def get_adk_parity(self) -> Any:
        """Get Parity Status"""
        return self._get("/api/adk/parity")

    def get_adk_roadmap_impact(self) -> Any:
        """Get Roadmap Impact"""
        return self._get("/api/adk/roadmap-impact")

    def get_adk_status(self) -> Any:
        """Get Status"""
        return self._get("/api/adk/status")

    def get_advanced_runtime_summary(self) -> Any:
        """Get Advanced Runtime Summary"""
        return self._get("/api/advanced/runtime-summary")

    def get_affective_state(self) -> Any:
        """Proxy Affective State"""
        return self._get("/api/affective/state")

    def get_agent_ops_status(self) -> Any:
        """Proxy Agent Ops Status"""
        return self._get("/api/agent-ops/status")

    def get_agent_runs(self) -> Any:
        """List Agent Runs"""
        return self._get("/api/agent-runs")

    def get_agent_runs_race(self) -> Any:
        """Get Agent Runs Race"""
        return self._get("/api/agent-runs/race")

    def get_agent_runs_swimlane(self) -> Any:
        """Get Agent Runs Swimlane"""
        return self._get("/api/agent-runs/swimlane")

    def get_agent_runs_run_id(self, run_id: str) -> Any:
        """Get Agent Run Replay"""
        return self._get(f"/api/agent-runs/{run_id}")

    def get_agent_tasks_active(self) -> Any:
        """Get Active Agent Tasks"""
        return self._get("/api/agent-tasks/active")

    def get_agent_collab_state(self) -> Any:
        """Get Agent Collab State"""
        return self._get("/api/agent/collab-state")

    def get_ai_consensus_history(self) -> Any:
        """Get Consensus History"""
        return self._get("/api/ai/consensus/history")

    def get_ai_health_rag(self) -> Any:
        """Proxy Rag Health"""
        return self._get("/api/ai/health/rag")

    def get_ai_homeostasis_events(self) -> Any:
        """Proxy Homeostasis Events"""
        return self._get("/api/ai/homeostasis/events")

    def get_ai_memory_status(self) -> Any:
        """Proxy Memory Status"""
        return self._get("/api/ai/memory/status")

    def get_ai_metrics(self) -> Any:
        """Get Ai Metrics"""
        return self._get("/api/ai/metrics")

    def get_ai_metrics_hybrid(self) -> Any:
        """Proxy Hybrid Metrics"""
        return self._get("/api/ai/metrics/hybrid")

    def get_ai_remediation_latest(self) -> Any:
        """Get Latest Remediation"""
        return self._get("/api/ai/remediation/latest")

    def get_aidb_health_probe(self, probe: str) -> Any:
        """Proxy Aidb Health"""
        return self._get(f"/api/aidb/health/{probe}")

    def get_aidb_metrics(self) -> Any:
        """Proxy Aidb Metrics"""
        return self._get("/api/aidb/metrics")

    def get_aistack_advanced_runtime_summary(self) -> Any:
        """Get Advanced Runtime Summary"""
        return self._get("/api/aistack/advanced/runtime-summary")

    def get_aistack_affective_state(self) -> Any:
        """Proxy Affective State"""
        return self._get("/api/aistack/affective/state")

    def get_aistack_agent_ops_status(self) -> Any:
        """Proxy Agent Ops Status"""
        return self._get("/api/aistack/agent-ops/status")

    def get_aistack_agent_runs(self) -> Any:
        """List Agent Runs"""
        return self._get("/api/aistack/agent-runs")

    def get_aistack_agent_runs_race(self) -> Any:
        """Get Agent Runs Race"""
        return self._get("/api/aistack/agent-runs/race")

    def get_aistack_agent_runs_swimlane(self) -> Any:
        """Get Agent Runs Swimlane"""
        return self._get("/api/aistack/agent-runs/swimlane")

    def get_aistack_agent_runs_run_id(self, run_id: str) -> Any:
        """Get Agent Run Replay"""
        return self._get(f"/api/aistack/agent-runs/{run_id}")

    def get_aistack_agent_tasks_active(self) -> Any:
        """Get Active Agent Tasks"""
        return self._get("/api/aistack/agent-tasks/active")

    def get_aistack_agent_collab_state(self) -> Any:
        """Get Agent Collab State"""
        return self._get("/api/aistack/agent/collab-state")

    def get_aistack_ai_consensus_history(self) -> Any:
        """Get Consensus History"""
        return self._get("/api/aistack/ai/consensus/history")

    def get_aistack_ai_health_rag(self) -> Any:
        """Proxy Rag Health"""
        return self._get("/api/aistack/ai/health/rag")

    def get_aistack_ai_homeostasis_events(self) -> Any:
        """Proxy Homeostasis Events"""
        return self._get("/api/aistack/ai/homeostasis/events")

    def get_aistack_ai_memory_status(self) -> Any:
        """Proxy Memory Status"""
        return self._get("/api/aistack/ai/memory/status")

    def get_aistack_ai_metrics(self) -> Any:
        """Get Ai Metrics"""
        return self._get("/api/aistack/ai/metrics")

    def get_aistack_ai_metrics_hybrid(self) -> Any:
        """Proxy Hybrid Metrics"""
        return self._get("/api/aistack/ai/metrics/hybrid")

    def get_aistack_ai_remediation_latest(self) -> Any:
        """Get Latest Remediation"""
        return self._get("/api/aistack/ai/remediation/latest")

    def get_aistack_aidb_health_probe(self, probe: str) -> Any:
        """Proxy Aidb Health"""
        return self._get(f"/api/aistack/aidb/health/{probe}")

    def get_aistack_aidb_metrics(self) -> Any:
        """Proxy Aidb Metrics"""
        return self._get("/api/aistack/aidb/metrics")

    def get_aistack_aistack_candidate_pipeline(self) -> Any:
        """Get Candidate Pipeline"""
        return self._get("/api/aistack/aistack/candidate-pipeline")

    def get_aistack_alerts_status(self) -> Any:
        """Get Alerts Status"""
        return self._get("/api/aistack/alerts/status")

    def get_aistack_approvals_pending(self) -> Any:
        """Get Pending Approvals"""
        return self._get("/api/aistack/approvals/pending")

    def get_aistack_aq_qa_run_phase(self, phase: str) -> Any:
        """Run Aq Qa Phase"""
        return self._get(f"/api/aistack/aq-qa/run/{phase}")

    def get_aistack_budget_policy(self) -> Any:
        """Proxy Budget Policy"""
        return self._get("/api/aistack/budget/policy")

    def get_aistack_candidate_pipeline(self) -> Any:
        """Get Candidate Pipeline"""
        return self._get("/api/aistack/candidate-pipeline")

    def get_aistack_collaboration_locks(self) -> Any:
        """Get Collaboration Locks"""
        return self._get("/api/aistack/collaboration/locks")

    def get_aistack_context_lifecycle_status(self) -> Any:
        """Proxy Clm Status"""
        return self._get("/api/aistack/context/lifecycle/status")

    def get_aistack_coordinator_ai_status(self) -> Any:
        """Proxy Coordinator Ai Status"""
        return self._get("/api/aistack/coordinator/ai-status")

    def get_aistack_discovery_signals(self) -> Any:
        """Get Discovery Signals"""
        return self._get("/api/aistack/discovery/signals")

    def get_aistack_drops_status(self) -> Any:
        """Get Drops Status"""
        return self._get("/api/aistack/drops/status")

    def get_aistack_effectiveness_scorecard(self) -> Any:
        """Get Effectiveness Scorecard"""
        return self._get("/api/aistack/effectiveness/scorecard")

    def get_aistack_eval_trend(self) -> Any:
        """Proxy Eval Trend"""
        return self._get("/api/aistack/eval/trend")

    def get_aistack_fleet_status(self) -> Any:
        """Get Fleet Status"""
        return self._get("/api/aistack/fleet/status")

    def get_aistack_fleet_summary(self) -> Any:
        """Proxy Fleet Summary"""
        return self._get("/api/aistack/fleet/summary")

    def get_aistack_graph_vector(self) -> Any:
        """Get Vector Graph"""
        return self._get("/api/aistack/graph/vector")

    def get_aistack_graph_vectorization(self) -> Any:
        """Get Vectorization Posture"""
        return self._get("/api/aistack/graph/vectorization")

    def get_aistack_graph_workflow(self) -> Any:
        """Get Workflow Graph"""
        return self._get("/api/aistack/graph/workflow")

    def get_aistack_hardware_state(self) -> Any:
        """Proxy Hardware State"""
        return self._get("/api/aistack/hardware/state")

    def get_aistack_harness(self) -> Any:
        """Get Harness Legacy Alias"""
        return self._get("/api/aistack/harness")

    def get_aistack_harness_overview(self) -> Any:
        """Get Harness Overview"""
        return self._get("/api/aistack/harness/overview")

    def get_aistack_harness_scorecard(self) -> Any:
        """Get Harness Scorecard"""
        return self._get("/api/aistack/harness/scorecard")

    def get_aistack_harness_stats(self) -> Any:
        """Get Harness Stats"""
        return self._get("/api/aistack/harness/stats")

    def get_aistack_health_aggregate(self) -> Any:
        """Get Health Aggregate"""
        return self._get("/api/aistack/health/aggregate")

    def get_aistack_health_audit(self) -> Any:
        """Get System Audit Log"""
        return self._get("/api/aistack/health/audit")

    def get_aistack_health_probe(self) -> Any:
        """Probe Health"""
        return self._get("/api/aistack/health/probe")

    def get_aistack_hints_active(self) -> Any:
        """Proxy Hints Active"""
        return self._get("/api/aistack/hints/active")

    def get_aistack_hints_report(self) -> Any:
        """Proxy Hints Report"""
        return self._get("/api/aistack/hints/report")

    def get_aistack_hints_stats(self) -> Any:
        """Proxy Hints Stats"""
        return self._get("/api/aistack/hints/stats")

    def get_aistack_insights_tools_heatmap(self) -> Any:
        """Get Tool Execution Heatmap"""
        return self._get("/api/aistack/insights/tools/heatmap")

    def get_aistack_knowledge_graph_fact_chain(self) -> Any:
        """Get Fact Chain"""
        return self._get("/api/aistack/knowledge/graph/fact-chain")

    def get_aistack_knowledge_observatory(self) -> Any:
        """Knowledge Observatory"""
        return self._get("/api/aistack/knowledge/observatory")

    def get_aistack_lesson_registry(self) -> Any:
        """Proxy Lesson Registry"""
        return self._get("/api/aistack/lesson-registry")

    def get_aistack_local_agent_monitor(self) -> Any:
        """Get Local Agent Monitor"""
        return self._get("/api/aistack/local-agent/monitor")

    def get_aistack_local_insights_latest(self) -> Any:
        """Get Local Insights Latest"""
        return self._get("/api/aistack/local-insights/latest")

    def get_aistack_loop_status(self) -> Any:
        """Get Loop Status"""
        return self._get("/api/aistack/loop/status")

    def get_aistack_mcp_v2_tools(self) -> Any:
        """Get Mcp V2 Tools"""
        return self._get("/api/aistack/mcp/v2/tools")

    def get_aistack_memory_broker_status(self) -> Any:
        """Proxy Memory Broker Status"""
        return self._get("/api/aistack/memory/broker/status")

    def get_aistack_memory_crystalline_status(self) -> Any:
        """Proxy Memory Crystalline Status"""
        return self._get("/api/aistack/memory/crystalline/status")

    def get_aistack_memory_facts(self) -> Any:
        """Proxy Memory Facts"""
        return self._get("/api/aistack/memory/facts")

    def get_aistack_memory_stats(self) -> Any:
        """Proxy Memory Stats"""
        return self._get("/api/aistack/memory/stats")

    def get_aistack_memory_supersede_history(self) -> Any:
        """Proxy Memory Supersede History"""
        return self._get("/api/aistack/memory/supersede/history")

    def get_aistack_metrics(self) -> Any:
        """Get Aistack Metrics"""
        return self._get("/api/aistack/metrics")

    def get_aistack_model_optimization_finetuning_jobs(self) -> Any:
        """Get Finetuning Jobs"""
        return self._get("/api/aistack/model-optimization/finetuning/jobs")

    def get_aistack_model_optimization_performance(self) -> Any:
        """Get Model Performance"""
        return self._get("/api/aistack/model-optimization/performance")

    def get_aistack_model_optimization_readiness(self) -> Any:
        """Get Model Optimization Readiness"""
        return self._get("/api/aistack/model-optimization/readiness")

    def get_aistack_model_optimization_training_data_stats(self) -> Any:
        """Get Training Data Stats"""
        return self._get("/api/aistack/model-optimization/training-data/stats")

    def get_aistack_operator_intelligence(self) -> Any:
        """Get Operator Intelligence"""
        return self._get("/api/aistack/operator/intelligence")

    def get_aistack_orchestration_arbiter_session_id(self, session_id: str) -> Any:
        """Get Arbiter History"""
        return self._get(f"/api/aistack/orchestration/arbiter/{session_id}")

    def get_aistack_orchestration_evaluations_trends(self) -> Any:
        """Get Evaluation Trends"""
        return self._get("/api/aistack/orchestration/evaluations/trends")

    def get_aistack_orchestration_events(self) -> Any:
        """Get Orchestration Events"""
        return self._get("/api/aistack/orchestration/events")

    def get_aistack_orchestration_sessions(self) -> Any:
        """Get Orchestration Sessions"""
        return self._get("/api/aistack/orchestration/sessions")

    def get_aistack_orchestration_team_session_id(self, session_id: str) -> Any:
        """Get Orchestration Team"""
        return self._get(f"/api/aistack/orchestration/team/{session_id}")

    def get_aistack_parity_scorecard(self) -> Any:
        """Proxy Parity Scorecard"""
        return self._get("/api/aistack/parity/scorecard")

    def get_aistack_policy_tool_deny_stats(self) -> Any:
        """Proxy Tool Deny Stats"""
        return self._get("/api/aistack/policy/tool-deny-stats")

    def get_aistack_ports_registry(self) -> Any:
        """Get Port Registry"""
        return self._get("/api/aistack/ports/registry")

    def get_aistack_prometheus_query(self) -> Any:
        """Proxy Prometheus Query"""
        return self._get("/api/aistack/prometheus/query")

    def get_aistack_prsi_actions(self) -> Any:
        """Get Prsi Actions"""
        return self._get("/api/aistack/prsi/actions")

    def get_aistack_query_traces(self) -> Any:
        """Query Traces"""
        return self._get("/api/aistack/query/traces")

    def get_aistack_ralph_integration_health(self) -> Any:
        """Get Integration Health"""
        return self._get("/api/aistack/ralph/integration-health")

    def get_aistack_ralph_stats(self) -> Any:
        """Get Ralph Stats"""
        return self._get("/api/aistack/ralph/stats")

    def get_aistack_ralph_tasks(self) -> Any:
        """Get Ralph Tasks"""
        return self._get("/api/aistack/ralph/tasks")

    def get_aistack_reasoning_profiles(self) -> Any:
        """Proxy Reasoning Profiles"""
        return self._get("/api/aistack/reasoning/profiles")

    def get_aistack_routing_decisions(self) -> Any:
        """Get Routing Decisions"""
        return self._get("/api/aistack/routing/decisions")

    def get_aistack_routing_lane_failures(self) -> Any:
        """Get Routing Lane Failures"""
        return self._get("/api/aistack/routing/lane-failures")

    def get_aistack_routing_summary(self) -> Any:
        """Get Routing Summary"""
        return self._get("/api/aistack/routing/summary")

    def get_aistack_scheduler_queue(self) -> Any:
        """Get Scheduler Queue"""
        return self._get("/api/aistack/scheduler/queue")

    def get_aistack_scheduler_status(self) -> Any:
        """Proxy Scheduler Status"""
        return self._get("/api/aistack/scheduler/status")

    def get_aistack_security_audit(self) -> Any:
        """Get Security Audit"""
        return self._get("/api/aistack/security/audit")

    def get_aistack_stats_circuit_breakers(self) -> Any:
        """Get Circuit Breakers"""
        return self._get("/api/aistack/stats/circuit-breakers")

    def get_aistack_stats_delegate(self) -> Any:
        """Get Delegate Stats"""
        return self._get("/api/aistack/stats/delegate")

    def get_aistack_stats_delegate_timeseries(self) -> Any:
        """Get Delegate Timeseries"""
        return self._get("/api/aistack/stats/delegate/timeseries")

    def get_aistack_stats_delegation_feedback_health(self) -> Any:
        """Get Delegation Feedback Health"""
        return self._get("/api/aistack/stats/delegation/feedback-health")

    def get_aistack_stats_learning(self) -> Any:
        """Get Learning Stats"""
        return self._get("/api/aistack/stats/learning")

    def get_aistack_stats_memory_collections(self) -> Any:
        """Get Memory Collections"""
        return self._get("/api/aistack/stats/memory/collections")

    def get_aistack_stats_ragas(self) -> Any:
        """Get Ragas Scores"""
        return self._get("/api/aistack/stats/ragas")

    def get_aistack_stats_telemetry_event_distribution(self) -> Any:
        """Get Event Distribution"""
        return self._get("/api/aistack/stats/telemetry/event-distribution")

    def get_aistack_stats_tools_performance(self) -> Any:
        """Get Tool Performance"""
        return self._get("/api/aistack/stats/tools/performance")

    def get_aistack_stats_training_dataset_health(self) -> Any:
        """Get Training Dataset Health"""
        return self._get("/api/aistack/stats/training/dataset-health")

    def get_aistack_switchboard_profiles(self) -> Any:
        """Get Switchboard Profiles"""
        return self._get("/api/aistack/switchboard/profiles")

    def get_aistack_system_navigator(self) -> Any:
        """Get System Navigator"""
        return self._get("/api/aistack/system-navigator")

    def get_aistack_task_classification_stats(self) -> Any:
        """Get Task Classification Stats"""
        return self._get("/api/aistack/task-classification/stats")

    def get_aistack_telemetry_anomalies(self) -> Any:
        """Get Telemetry Anomalies"""
        return self._get("/api/aistack/telemetry/anomalies")

    def get_aistack_trace_trace_id(self, trace_id: str) -> Any:
        """Get Trace"""
        return self._get(f"/api/aistack/trace/{trace_id}")

    def get_aistack_traces_drift(self) -> Any:
        """Proxy Traces Drift"""
        return self._get("/api/aistack/traces/drift")

    def get_aistack_traces_summary(self) -> Any:
        """Proxy Traces Summary"""
        return self._get("/api/aistack/traces/summary")

    def get_aistack_training_health(self) -> Any:
        """Get Training Health"""
        return self._get("/api/aistack/training/health")

    def get_aistack_verify_self_results(self) -> Any:
        """Get Verify Self Results"""
        return self._get("/api/aistack/verify-self/results")

    def get_alerts_status(self) -> Any:
        """Get Alerts Status"""
        return self._get("/api/alerts/status")

    def get_approvals_pending(self) -> Any:
        """Get Pending Approvals"""
        return self._get("/api/approvals/pending")

    def get_aq_qa_run_phase(self, phase: str) -> Any:
        """Run Aq Qa Phase"""
        return self._get(f"/api/aq-qa/run/{phase}")

    def get_audit_operator_events(self) -> Any:
        """Get Operator Audit Events"""
        return self._get("/api/audit/operator/events")

    def get_audit_operator_integrity(self) -> Any:
        """Get Operator Audit Integrity"""
        return self._get("/api/audit/operator/integrity")

    def get_audit_operator_summary(self) -> Any:
        """Get Operator Audit Summary"""
        return self._get("/api/audit/operator/summary")

    def get_budget_policy(self) -> Any:
        """Proxy Budget Policy"""
        return self._get("/api/budget/policy")

    def get_candidate_pipeline(self) -> Any:
        """Get Candidate Pipeline"""
        return self._get("/api/candidate-pipeline")

    def get_collaboration_consensus_session_id(self, session_id: str) -> Any:
        """Get Consensus Session"""
        return self._get(f"/api/collaboration/consensus/{session_id}")

    def get_collaboration_context_team_id(self, team_id: str) -> Any:
        """Get Context"""
        return self._get(f"/api/collaboration/context/{team_id}")

    def get_collaboration_locks(self) -> Any:
        """Get Collaboration Locks"""
        return self._get("/api/collaboration/locks")

    def get_collaboration_messages_queue_agent_id(self, agent_id: str) -> Any:
        """Get Queue Status"""
        return self._get(f"/api/collaboration/messages/queue/{agent_id}")

    def get_collaboration_messages_receive_agent_id(self, agent_id: str) -> Any:
        """Receive Message"""
        return self._get(f"/api/collaboration/messages/receive/{agent_id}")

    def get_collaboration_metrics_comparison(self) -> Any:
        """Get Performance Comparison"""
        return self._get("/api/collaboration/metrics/comparison")

    def get_collaboration_metrics_composition(self) -> Any:
        """Get Composition Analysis"""
        return self._get("/api/collaboration/metrics/composition")

    def get_collaboration_metrics_cost_benefit(self) -> Any:
        """Get Cost Benefit"""
        return self._get("/api/collaboration/metrics/cost-benefit")

    def get_collaboration_metrics_summary(self) -> Any:
        """Get Metrics Summary"""
        return self._get("/api/collaboration/metrics/summary")

    def get_collaboration_patterns(self) -> Any:
        """Get Patterns"""
        return self._get("/api/collaboration/patterns")

    def get_collaboration_plans_plan_id(self, plan_id: str) -> Any:
        """Get Plan"""
        return self._get(f"/api/collaboration/plans/{plan_id}")

    def get_collaboration_teams_team_id(self, team_id: str) -> Any:
        """Get Team"""
        return self._get(f"/api/collaboration/teams/{team_id}")

    def get_config(self) -> Any:
        """Get Runtime Config"""
        return self._get("/api/config")

    def get_config_graphs_repo_structure(self) -> Any:
        """Get Repo Structure Graph"""
        return self._get("/api/config/graphs/repo-structure")

    def get_config_graphs_workflow_blueprints(self) -> Any:
        """Get Workflow Blueprint Graph"""
        return self._get("/api/config/graphs/workflow-blueprints")

    def get_config_file_name(self, file_name: str) -> Any:
        """Get Config"""
        return self._get(f"/api/config/{file_name}")

    def get_configs_config_key_impact_timeline(self, config_key: str) -> Any:
        """Get Config Impact Timeline"""
        return self._get(f"/api/configs/{config_key}/impact-timeline")

    def get_containers(self) -> Any:
        """List Containers"""
        return self._get("/api/containers")

    def get_containers_container_id_logs(self, container_id: str) -> Any:
        """Get Container Logs"""
        return self._get(f"/api/containers/{container_id}/logs")

    def get_context_lifecycle_status(self) -> Any:
        """Proxy Clm Status"""
        return self._get("/api/context/lifecycle/status")

    def get_coordinator_ai_status(self) -> Any:
        """Proxy Coordinator Ai Status"""
        return self._get("/api/coordinator/ai-status")

    def get_deployments_active(self) -> Any:
        """Get Active Deployments"""
        return self._get("/api/deployments/active")

    def get_deployments_approvals_pending(self) -> Any:
        """Get Pending Deployment Approvals"""
        return self._get("/api/deployments/approvals/pending")

    def get_deployments_graph(self) -> Any:
        """Get Deployment Graph"""
        return self._get("/api/deployments/graph")

    def get_deployments_history(self) -> Any:
        """Get Deployment History"""
        return self._get("/api/deployments/history")

    def get_deployments_search(self) -> Any:
        """Search Deployments"""
        return self._get("/api/deployments/search")

    def get_deployments_search_context(self) -> Any:
        """Search Deployment Context"""
        return self._get("/api/deployments/search/context")

    def get_deployments_search_status(self) -> Any:
        """Get Deployment Search Status"""
        return self._get("/api/deployments/search/status")

    def get_deployments_deployment_id(self, deployment_id: str) -> Any:
        """Get Deployment"""
        return self._get(f"/api/deployments/{deployment_id}")

    def get_deployments_deployment_id_causality(self, deployment_id: str) -> Any:
        """Get Deployment Causality"""
        return self._get(f"/api/deployments/{deployment_id}/causality")

    def get_deployments_deployment_id_configs(self, deployment_id: str) -> Any:
        """Get Deployment Configs"""
        return self._get(f"/api/deployments/{deployment_id}/configs")

    def get_deployments_deployment_id_logs(self, deployment_id: str) -> Any:
        """Get Deployment Logs"""
        return self._get(f"/api/deployments/{deployment_id}/logs")

    def get_deployments_deployment_id_services(self, deployment_id: str) -> Any:
        """Get Deployment Services"""
        return self._get(f"/api/deployments/{deployment_id}/services")

    def get_discovery_signals(self) -> Any:
        """Get Discovery Signals"""
        return self._get("/api/discovery/signals")

    def get_drops_status(self) -> Any:
        """Get Drops Status"""
        return self._get("/api/drops/status")

    def get_effectiveness_scorecard(self) -> Any:
        """Get Effectiveness Scorecard"""
        return self._get("/api/effectiveness/scorecard")

    def get_eval_trend(self) -> Any:
        """Proxy Eval Trend"""
        return self._get("/api/eval/trend")

    def get_firewall_audit_log(self) -> Any:
        """Get Firewall Audit Log"""
        return self._get("/api/firewall/audit-log")

    def get_firewall_captive_portal_status(self) -> Any:
        """Get Captive Portal Status"""
        return self._get("/api/firewall/captive-portal/status")

    def get_firewall_crowdsec_decisions(self) -> Any:
        """Get Crowdsec Decisions"""
        return self._get("/api/firewall/crowdsec/decisions")

    def get_firewall_crowdsec_status(self) -> Any:
        """Get Crowdsec Bouncer Status"""
        return self._get("/api/firewall/crowdsec/status")

    def get_firewall_rules(self) -> Any:
        """Get Firewall Rules"""
        return self._get("/api/firewall/rules")

    def get_firewall_status(self) -> Any:
        """Get Firewall Status"""
        return self._get("/api/firewall/status")

    def get_fleet_status(self) -> Any:
        """Get Fleet Status"""
        return self._get("/api/fleet/status")

    def get_fleet_summary(self) -> Any:
        """Proxy Fleet Summary"""
        return self._get("/api/fleet/summary")

    def get_graph_vector(self) -> Any:
        """Get Vector Graph"""
        return self._get("/api/graph/vector")

    def get_graph_vectorization(self) -> Any:
        """Get Vectorization Posture"""
        return self._get("/api/graph/vectorization")

    def get_graph_workflow(self) -> Any:
        """Get Workflow Graph"""
        return self._get("/api/graph/workflow")

    def get_hardware_state(self) -> Any:
        """Proxy Hardware State"""
        return self._get("/api/hardware/state")

    def get_harness(self) -> Any:
        """Get Harness Legacy Alias"""
        return self._get("/api/harness")

    def get_harness_overview(self) -> Any:
        """Get Harness Overview"""
        return self._get("/api/harness/overview")

    def get_harness_scorecard(self) -> Any:
        """Get Harness Scorecard"""
        return self._get("/api/harness/scorecard")

    def get_harness_stats(self) -> Any:
        """Get Harness Stats"""
        return self._get("/api/harness/stats")

    def get_health(self) -> Any:
        """Health Check"""
        return self._get("/api/health")

    def get_health_aggregate(self) -> Any:
        """Get Aggregate Health"""
        return self._get("/api/health/aggregate")

    def get_health_alerts(self) -> Any:
        """Get Alerts"""
        return self._get("/api/health/alerts")

    def get_health_alerts_by_severity_severity(self, severity: str) -> Any:
        """Get Alerts By Severity"""
        return self._get(f"/api/health/alerts/by-severity/{severity}")

    def get_health_alerts_config(self) -> Any:
        """Get Alert Configuration"""
        return self._get("/api/health/alerts/config")

    def get_health_alerts_history(self) -> Any:
        """Get Alert History"""
        return self._get("/api/health/alerts/history")

    def get_health_alerts_remediation_status_alert_id(self, alert_id: str) -> Any:
        """Get Remediation Status"""
        return self._get(f"/api/health/alerts/remediation-status/{alert_id}")

    def get_health_audit(self) -> Any:
        """Get System Audit Log"""
        return self._get("/api/health/audit")

    def get_health_categories(self) -> Any:
        """List Categories"""
        return self._get("/api/health/categories")

    def get_health_categories_category(self, category: str) -> Any:
        """Get Category Health"""
        return self._get(f"/api/health/categories/{category}")

    def get_health_layered(self) -> Any:
        """Get Layered Health"""
        return self._get("/api/health/layered")

    def get_health_probe(self) -> Any:
        """Probe Health"""
        return self._get("/api/health/probe")

    def get_health_services_all(self) -> Any:
        """Get All Services Health"""
        return self._get("/api/health/services/all")

    def get_health_services_service_id(self, service_id: str) -> Any:
        """Get Service Health"""
        return self._get(f"/api/health/services/{service_id}")

    def get_hints_active(self) -> Any:
        """Proxy Hints Active"""
        return self._get("/api/hints/active")

    def get_hints_report(self) -> Any:
        """Proxy Hints Report"""
        return self._get("/api/hints/report")

    def get_hints_stats(self) -> Any:
        """Proxy Hints Stats"""
        return self._get("/api/hints/stats")

    def get_insights_actions_recommendations(self) -> Any:
        """Get Structured Actions"""
        return self._get("/api/insights/actions/recommendations")

    def get_insights_agents_lessons(self) -> Any:
        """Get Agent Lessons"""
        return self._get("/api/insights/agents/lessons")

    def get_insights_cache_analytics(self) -> Any:
        """Get Cache Analytics"""
        return self._get("/api/insights/cache/analytics")

    def get_insights_deployments_readiness(self) -> Any:
        """Get Deployment Pipeline Readiness"""
        return self._get("/api/insights/deployments/readiness")

    def get_insights_experiments_readiness(self) -> Any:
        """Get Experimentation Readiness"""
        return self._get("/api/insights/experiments/readiness")

    def get_insights_hints_effectiveness(self) -> Any:
        """Get Hint Effectiveness"""
        return self._get("/api/insights/hints/effectiveness")

    def get_insights_improvements_candidates(self) -> Any:
        """Get Improvement Candidates"""
        return self._get("/api/insights/improvements/candidates")

    def get_insights_improvements_readiness(self) -> Any:
        """Get Improvement Automation Readiness"""
        return self._get("/api/insights/improvements/readiness")

    def get_insights_improvements_reviews(self) -> Any:
        """Get Code Review Summary"""
        return self._get("/api/insights/improvements/reviews")

    def get_insights_metrics_ai_specific(self) -> Any:
        """Get Ai Specific Metrics"""
        return self._get("/api/insights/metrics/ai-specific")

    def get_insights_observability_readiness(self) -> Any:
        """Get Unified Observability Readiness"""
        return self._get("/api/insights/observability/readiness")

    def get_insights_patterns_readiness(self) -> Any:
        """Get Agentic Pattern Library Readiness"""
        return self._get("/api/insights/patterns/readiness")

    def get_insights_performance_hotspots(self) -> Any:
        """Get Performance Hotspots"""
        return self._get("/api/insights/performance/hotspots")

    def get_insights_performance_profiling(self) -> Any:
        """Get Performance Profiling Readiness"""
        return self._get("/api/insights/performance/profiling")

    def get_insights_queries_complexity(self) -> Any:
        """Get Query Complexity"""
        return self._get("/api/insights/queries/complexity")

    def get_insights_report_full(self) -> Any:
        """Get Full Insights Report"""
        return self._get("/api/insights/report/full")

    def get_insights_roadmap_readiness(self) -> Any:
        """Get Roadmap Readiness"""
        return self._get("/api/insights/roadmap/readiness")

    def get_insights_routing_analytics(self) -> Any:
        """Get Routing Analytics"""
        return self._get("/api/insights/routing/analytics")

    def get_insights_security_compliance(self) -> Any:
        """Get Security Compliance"""
        return self._get("/api/insights/security/compliance")

    def get_insights_system_health(self) -> Any:
        """Get System Health"""
        return self._get("/api/insights/system/health")

    def get_insights_testing_readiness(self) -> Any:
        """Get Testing Validation Readiness"""
        return self._get("/api/insights/testing/readiness")

    def get_insights_tools_heatmap(self) -> Any:
        """Get Tool Execution Heatmap"""
        return self._get("/api/insights/tools/heatmap")

    def get_insights_tools_performance(self) -> Any:
        """Get Tool Performance"""
        return self._get("/api/insights/tools/performance")

    def get_insights_workflows_a2a_readiness(self) -> Any:
        """Get A2A Readiness"""
        return self._get("/api/insights/workflows/a2a-readiness")

    def get_insights_workflows_compliance(self) -> Any:
        """Get Workflow Compliance"""
        return self._get("/api/insights/workflows/compliance")

    def get_insights_workflows_phase_4_acceptance(self) -> Any:
        """Get Phase 4 Acceptance"""
        return self._get("/api/insights/workflows/phase-4-acceptance")

    def get_knowledge_graph_fact_chain(self) -> Any:
        """Get Fact Chain"""
        return self._get("/api/knowledge/graph/fact-chain")

    def get_knowledge_observatory(self) -> Any:
        """Knowledge Observatory"""
        return self._get("/api/knowledge/observatory")

    def get_lesson_registry(self) -> Any:
        """Proxy Lesson Registry"""
        return self._get("/api/lesson-registry")

    def get_local_agent_monitor(self) -> Any:
        """Get Local Agent Monitor"""
        return self._get("/api/local-agent/monitor")

    def get_local_insights_latest(self) -> Any:
        """Get Local Insights Latest"""
        return self._get("/api/local-insights/latest")

    def get_loop_status(self) -> Any:
        """Get Loop Status"""
        return self._get("/api/loop/status")

    def get_mcp_v2_tools(self) -> Any:
        """Get Mcp V2 Tools"""
        return self._get("/api/mcp/v2/tools")

    def get_memory_broker_status(self) -> Any:
        """Proxy Memory Broker Status"""
        return self._get("/api/memory/broker/status")

    def get_memory_crystalline_status(self) -> Any:
        """Proxy Memory Crystalline Status"""
        return self._get("/api/memory/crystalline/status")

    def get_memory_facts(self) -> Any:
        """Proxy Memory Facts"""
        return self._get("/api/memory/facts")

    def get_memory_stats(self) -> Any:
        """Proxy Memory Stats"""
        return self._get("/api/memory/stats")

    def get_memory_supersede_history(self) -> Any:
        """Proxy Memory Supersede History"""
        return self._get("/api/memory/supersede/history")

    def get_metrics(self) -> Any:
        """Get Aistack Metrics"""
        return self._get("/api/metrics")

    def get_metrics_health_score(self) -> Any:
        """Get Health Score"""
        return self._get("/api/metrics/health-score")

    def get_metrics_history_metric(self, metric: str) -> Any:
        """Get Metric History"""
        return self._get(f"/api/metrics/history/{metric}")

    def get_metrics_system(self) -> Any:
        """Get System Metrics"""
        return self._get("/api/metrics/system")

    def get_model_optimization_finetuning_jobs(self) -> Any:
        """Get Finetuning Jobs"""
        return self._get("/api/model-optimization/finetuning/jobs")

    def get_model_optimization_performance(self) -> Any:
        """Get Model Performance"""
        return self._get("/api/model-optimization/performance")

    def get_model_optimization_readiness(self) -> Any:
        """Get Model Optimization Readiness"""
        return self._get("/api/model-optimization/readiness")

    def get_model_optimization_training_data_stats(self) -> Any:
        """Get Training Data Stats"""
        return self._get("/api/model-optimization/training-data/stats")

    def get_models(self) -> Any:
        """List Models"""
        return self._get("/api/models")

    def get_models_active(self) -> Any:
        """Get Active Model"""
        return self._get("/api/models/active")

    def get_models_model_id(self, model_id: str) -> Any:
        """Get Model"""
        return self._get(f"/api/models/{model_id}")

    def get_models_model_id_download_stream(self, model_id: str) -> Any:
        """Download Progress Stream"""
        return self._get(f"/api/models/{model_id}/download/stream")

    def get_models_model_id_llama_args(self, model_id: str) -> Any:
        """Get Model Llama Args"""
        return self._get(f"/api/models/{model_id}/llama-args")

    def get_models_model_id_promote_stream(self, model_id: str) -> Any:
        """Promote Progress Stream"""
        return self._get(f"/api/models/{model_id}/promote/stream")

    def get_operator_intelligence(self) -> Any:
        """Get Operator Intelligence"""
        return self._get("/api/operator/intelligence")

    def get_orchestration_arbiter_session_id(self, session_id: str) -> Any:
        """Get Arbiter History"""
        return self._get(f"/api/orchestration/arbiter/{session_id}")

    def get_orchestration_evaluations_trends(self) -> Any:
        """Get Evaluation Trends"""
        return self._get("/api/orchestration/evaluations/trends")

    def get_orchestration_events(self) -> Any:
        """Get Orchestration Events"""
        return self._get("/api/orchestration/events")

    def get_orchestration_sessions(self) -> Any:
        """Get Orchestration Sessions"""
        return self._get("/api/orchestration/sessions")

    def get_orchestration_team_session_id(self, session_id: str) -> Any:
        """Get Orchestration Team"""
        return self._get(f"/api/orchestration/team/{session_id}")

    def get_parity_scorecard(self) -> Any:
        """Proxy Parity Scorecard"""
        return self._get("/api/parity/scorecard")

    def get_policy_tool_deny_stats(self) -> Any:
        """Proxy Tool Deny Stats"""
        return self._get("/api/policy/tool-deny-stats")

    def get_ports_registry(self) -> Any:
        """Get Port Registry"""
        return self._get("/api/ports/registry")

    def get_prometheus_query(self) -> Any:
        """Proxy Prometheus Query"""
        return self._get("/api/prometheus/query")

    def get_prsi_actions(self) -> Any:
        """Get Prsi Actions"""
        return self._get("/api/prsi/actions")

    def get_query_traces(self) -> Any:
        """Query Traces"""
        return self._get("/api/query/traces")

    def get_ralph_integration_health(self) -> Any:
        """Get Integration Health"""
        return self._get("/api/ralph/integration-health")

    def get_ralph_stats(self) -> Any:
        """Get Ralph Stats"""
        return self._get("/api/ralph/stats")

    def get_ralph_tasks(self) -> Any:
        """Get Ralph Tasks"""
        return self._get("/api/ralph/tasks")

    def get_reasoning_profiles(self) -> Any:
        """Proxy Reasoning Profiles"""
        return self._get("/api/reasoning/profiles")

    def get_routing_decisions(self) -> Any:
        """Get Routing Decisions"""
        return self._get("/api/routing/decisions")

    def get_routing_lane_failures(self) -> Any:
        """Get Routing Lane Failures"""
        return self._get("/api/routing/lane-failures")

    def get_routing_summary(self) -> Any:
        """Get Routing Summary"""
        return self._get("/api/routing/summary")

    def get_scheduler_queue(self) -> Any:
        """Get Scheduler Queue"""
        return self._get("/api/scheduler/queue")

    def get_scheduler_status(self) -> Any:
        """Proxy Scheduler Status"""
        return self._get("/api/scheduler/status")

    def get_security_audit(self) -> Any:
        """Get Security Audit"""
        return self._get("/api/security/audit")

    def get_services(self) -> Any:
        """List Services"""
        return self._get("/api/services")

    def get_services_service_name_health_timeline(self, service_name: str) -> Any:
        """Get Service Health Timeline"""
        return self._get(f"/api/services/{service_name}/health-timeline")

    def get_stats_circuit_breakers(self) -> Any:
        """Get Circuit Breakers"""
        return self._get("/api/stats/circuit-breakers")

    def get_stats_delegate(self) -> Any:
        """Get Delegate Stats"""
        return self._get("/api/stats/delegate")

    def get_stats_delegate_timeseries(self) -> Any:
        """Get Delegate Timeseries"""
        return self._get("/api/stats/delegate/timeseries")

    def get_stats_delegation_feedback_health(self) -> Any:
        """Get Delegation Feedback Health"""
        return self._get("/api/stats/delegation/feedback-health")

    def get_stats_learning(self) -> Any:
        """Get Learning Stats"""
        return self._get("/api/stats/learning")

    def get_stats_memory_collections(self) -> Any:
        """Get Memory Collections"""
        return self._get("/api/stats/memory/collections")

    def get_stats_ragas(self) -> Any:
        """Get Ragas Scores"""
        return self._get("/api/stats/ragas")

    def get_stats_telemetry_event_distribution(self) -> Any:
        """Get Event Distribution"""
        return self._get("/api/stats/telemetry/event-distribution")

    def get_stats_tools_performance(self) -> Any:
        """Get Tool Performance"""
        return self._get("/api/stats/tools/performance")

    def get_stats_training_dataset_health(self) -> Any:
        """Get Training Dataset Health"""
        return self._get("/api/stats/training/dataset-health")

    def get_switchboard_profiles(self) -> Any:
        """Get Switchboard Profiles"""
        return self._get("/api/switchboard/profiles")

    def get_system_navigator(self) -> Any:
        """Get System Navigator"""
        return self._get("/api/system-navigator")

    def get_task_classification_stats(self) -> Any:
        """Get Task Classification Stats"""
        return self._get("/api/task-classification/stats")

    def get_telemetry_anomalies(self) -> Any:
        """Get Telemetry Anomalies"""
        return self._get("/api/telemetry/anomalies")

    def get_testing_executions(self) -> Any:
        """List Testing Executions"""
        return self._get("/api/testing/executions")

    def get_testing_executions_execution_id(self, execution_id: str) -> Any:
        """Get Testing Execution"""
        return self._get(f"/api/testing/executions/{execution_id}")

    def get_testing_suites(self) -> Any:
        """List Testing Suites"""
        return self._get("/api/testing/suites")

    def get_topology(self) -> Any:
        """Get Topology"""
        return self._get("/api/topology")

    def get_topology_flow(self) -> Any:
        """Get Topology Flow"""
        return self._get("/api/topology/flow")

    def get_trace_trace_id(self, trace_id: str) -> Any:
        """Get Trace"""
        return self._get(f"/api/trace/{trace_id}")

    def get_traces_drift(self) -> Any:
        """Proxy Traces Drift"""
        return self._get("/api/traces/drift")

    def get_traces_summary(self) -> Any:
        """Proxy Traces Summary"""
        return self._get("/api/traces/summary")

    def get_training_health(self) -> Any:
        """Get Training Health"""
        return self._get("/api/training/health")

    def get_verify_self_results(self) -> Any:
        """Get Verify Self Results"""
        return self._get("/api/verify-self/results")

    def get_workflows_agents(self) -> Any:
        """Get Workflow Agents"""
        return self._get("/api/workflows/agents")

    def get_workflows_executions_execution_id(self, execution_id: str) -> Any:
        """Get Execution Status"""
        return self._get(f"/api/workflows/executions/{execution_id}")

    def get_workflows_executions_execution_id_graph(self, execution_id: str) -> Any:
        """Get Execution Graph"""
        return self._get(f"/api/workflows/executions/{execution_id}/graph")

    def get_workflows_executions_execution_id_logs(self, execution_id: str) -> Any:
        """Get Execution Logs"""
        return self._get(f"/api/workflows/executions/{execution_id}/logs")

    def get_workflows_history(self) -> Any:
        """Get Workflow History"""
        return self._get("/api/workflows/history")

    def get_workflows_statistics(self) -> Any:
        """Get Statistics"""
        return self._get("/api/workflows/statistics")

    def get_workflows_templates(self) -> Any:
        """List Templates"""
        return self._get("/api/workflows/templates")

    def get_workflows_templates_template_id(self, template_id: str) -> Any:
        """Get Template"""
        return self._get(f"/api/workflows/templates/{template_id}")

    def get_workflows_yaml_graph(self) -> Any:
        """Get Yaml Workflow Graph"""
        return self._get("/api/workflows/yaml/graph")

