"""Derived spec-variant packs for controlled agent spec experiments.

Markdown/YAML remains canonical. HTML and visual HTML files generated by this
module are read-only implementation briefs for experiments and must carry the
canonical source hash so drift is detectable.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "maeah.spec-variant-pack.v1"
GENERATOR = "spec_variant_packs.py"
VARIANTS = ("markdown", "html", "visual_html")


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def sha256_file(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _slug(path: Path) -> str:
    return path.stem.lower().replace(" ", "-")


def _derived_label(variant: str) -> str:
    return {
        "markdown": "Derived Markdown experiment view, not canonical",
        "html": "Derived HTML experiment view, not canonical",
        "visual_html": "Derived visual HTML experiment view, not canonical",
    }[variant]


def _html_document(title: str, body: str, *, visual: bool, canonical_path: Path, canonical_hash: str, mockup_assets: list[str]) -> str:
    mockups = ""
    if visual:
        if mockup_assets:
            items = "\n".join(
                f'<li><code>{html.escape(asset)}</code></li>'
                for asset in mockup_assets
            )
            mockups = f"<section><h2>Mockup Assets</h2><ul>{items}</ul></section>"
        else:
            mockups = "<section><h2>Mockup Assets</h2><p>No mockup assets supplied for this generated visual spec.</p></section>"
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{html.escape(title)}</title>
  <meta name="derived-from" content="{html.escape(str(canonical_path))}">
  <meta name="source-hash" content="{html.escape(canonical_hash)}">
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; line-height: 1.5; }}
    .notice {{ border: 2px solid #b45309; padding: 0.75rem; background: #fffbeb; }}
    pre {{ white-space: pre-wrap; background: #f8fafc; padding: 1rem; border: 1px solid #cbd5e1; }}
  </style>
</head>
<body>
  <div class="notice">Derived view, not canonical. Edit the Markdown source and regenerate this artifact.</div>
  <dl>
    <dt>Canonical source</dt><dd><code>{html.escape(str(canonical_path))}</code></dd>
    <dt>Source hash</dt><dd><code>{html.escape(canonical_hash)}</code></dd>
  </dl>
  {mockups}
  <main>
    <h1>{html.escape(title)}</h1>
    <pre>{html.escape(body)}</pre>
  </main>
</body>
</html>
"""


def build_spec_variant_pack(
    canonical_path: Path,
    output_dir: Path,
    *,
    variants: tuple[str, ...] = VARIANTS,
    mockup_assets: list[str] | None = None,
    write_artifacts: bool = True,
) -> dict[str, Any]:
    canonical_path = canonical_path.resolve()
    output_dir = output_dir.resolve()
    mockup_assets = list(mockup_assets or [])
    if not canonical_path.exists():
        raise FileNotFoundError(canonical_path)
    unknown = sorted(set(variants) - set(VARIANTS))
    if unknown:
        raise ValueError(f"unknown variants: {', '.join(unknown)}")

    source = canonical_path.read_text(encoding="utf-8")
    canonical_hash = sha256_file(canonical_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = _slug(canonical_path)

    variant_records: list[dict[str, Any]] = []
    for variant in variants:
        if variant == "markdown":
            derived_path = output_dir / f"{stem}.derived.md"
            content = (
                "<!-- Derived view, not canonical. "
                f"canonical={canonical_path} source_hash={canonical_hash} -->\n\n"
                + source
            )
        elif variant == "html":
            derived_path = output_dir / f"{stem}.derived.html"
            content = _html_document(stem, source, visual=False, canonical_path=canonical_path, canonical_hash=canonical_hash, mockup_assets=[])
        else:
            derived_path = output_dir / f"{stem}.visual.derived.html"
            content = _html_document(stem, source, visual=True, canonical_path=canonical_path, canonical_hash=canonical_hash, mockup_assets=mockup_assets)

        if write_artifacts:
            derived_path.write_text(content, encoding="utf-8")
            derived_hash = sha256_file(derived_path)
        else:
            derived_hash = "sha256:" + hashlib.sha256(content.encode("utf-8")).hexdigest()

        variant_records.append(
            {
                "variant": variant,
                "derived_path": str(derived_path),
                "derived_hash": derived_hash,
                "canonical_hash": canonical_hash,
                "label": _derived_label(variant),
                "canonical": False,
                "mockup_assets": mockup_assets if variant == "visual_html" else [],
                "provenance": {
                    "generator": GENERATOR,
                    "canonical_path": str(canonical_path),
                },
            }
        )

    pack = {
        "schema_version": SCHEMA_VERSION,
        "pack_id": f"spec-pack:{stem}:{canonical_hash.removeprefix('sha256:')[:12]}",
        "canonical_path": str(canonical_path),
        "canonical_hash": canonical_hash,
        "generated_at": now_iso(),
        "generator": GENERATOR,
        "variants": variant_records,
    }
    validate_spec_variant_pack(pack, current_canonical_hash=canonical_hash)
    return pack


def validate_spec_variant_pack(pack: dict[str, Any], *, current_canonical_hash: str | None = None) -> None:
    required = ("schema_version", "pack_id", "canonical_path", "canonical_hash", "generated_at", "generator", "variants")
    missing = [key for key in required if key not in pack]
    if missing:
        raise ValueError(f"spec variant pack missing required fields: {', '.join(missing)}")
    if pack["schema_version"] != SCHEMA_VERSION:
        raise ValueError(f"invalid schema_version: {pack['schema_version']}")
    if current_canonical_hash and pack["canonical_hash"] != current_canonical_hash:
        raise ValueError("canonical source hash drift detected")
    variants = pack.get("variants")
    if not isinstance(variants, list) or not variants:
        raise ValueError("variants must be a non-empty list")
    seen: set[str] = set()
    for item in variants:
        variant = item.get("variant")
        if variant not in VARIANTS:
            raise ValueError(f"invalid variant: {variant}")
        if variant in seen:
            raise ValueError(f"duplicate variant: {variant}")
        seen.add(variant)
        if item.get("canonical") is not False:
            raise ValueError("derived variants must not be canonical")
        if item.get("canonical_hash") != pack["canonical_hash"]:
            raise ValueError(f"{variant}: canonical hash mismatch")
        if not str(item.get("derived_hash") or "").startswith("sha256:"):
            raise ValueError(f"{variant}: missing derived hash")
        if "not canonical" not in str(item.get("label") or "").lower():
            raise ValueError(f"{variant}: derived label must state not canonical")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate derived spec variant pack metadata.")
    parser.add_argument("canonical_path", type=Path)
    parser.add_argument("--output-dir", type=Path, default=Path(".agents/spec-variants"))
    parser.add_argument("--mockup-asset", action="append", default=[])
    args = parser.parse_args()
    pack = build_spec_variant_pack(args.canonical_path, args.output_dir, mockup_assets=args.mockup_asset)
    print(json.dumps(pack, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
