#!/usr/bin/env python3
"""trace — distributed tracing on the A2A event bus (WS5). One trace per intent.

A trace is the set of events sharing a trace_id; spans nest via
parent_span_id. Built on the append-only event log (no OTel collector required
— local-first), with OPTIONAL OTLP export when OTEL_EXPORTER_OTLP_ENDPOINT is
set. Exit criterion: any run is diagnosable from its trace alone.

Propagation across processes (CLI -> delegate -> dispatch -> model):
  - AQ_TRACE_ID  : the intent's trace id (generated by the first span if unset)
  - AQ_SPAN_ID   : the current span id (becomes a child's parent)
Child processes read these from the environment and continue the trace.

Usage:
    from trace import span, current_trace_id
    with span("dispatch.local", agent="claude", attrs={"task_id": tid}) as s:
        ...                      # nested spans auto-parent to s
        s.set_status("ok")       # or "error" with s.record_error(exc)

    reconstruct(trace_id) -> list[SpanNode]   # tree for aq-event trace
"""

from __future__ import annotations

import contextlib
import os
import sys
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Iterator, Optional

_LIB = os.path.dirname(os.path.abspath(__file__))
if _LIB not in sys.path:
    sys.path.insert(0, _LIB)

import event_log  # noqa: E402


def _gen_id(n: int = 16) -> str:
    return uuid.uuid4().hex[:n]


def current_trace_id() -> Optional[str]:
    return os.environ.get("AQ_TRACE_ID") or None


def current_span_id() -> Optional[str]:
    return os.environ.get("AQ_SPAN_ID") or None


def ensure_trace_id() -> str:
    """Return the ambient trace id, generating + exporting one to env if absent."""
    tid = os.environ.get("AQ_TRACE_ID")
    if not tid:
        tid = _gen_id(32)
        os.environ["AQ_TRACE_ID"] = tid
    return tid


@dataclass
class Span:
    name: str
    agent: str
    trace_id: str
    span_id: str
    parent_span_id: Optional[str]
    start_ts: float
    attrs: dict[str, Any] = field(default_factory=dict)
    status: str = "unset"
    error: Optional[str] = None

    def set_status(self, status: str) -> None:
        self.status = status

    def set_attr(self, key: str, value: Any) -> None:
        self.attrs[key] = value

    def record_error(self, exc: BaseException) -> None:
        self.status = "error"
        self.error = f"{type(exc).__name__}: {exc}"


@contextlib.contextmanager
def span(name: str, *, agent: str = "harness", attrs: Optional[dict[str, Any]] = None) -> Iterator[Span]:
    """Open a span: emits trace.span.start now and trace.span.end on exit.

    trace_id/parent inherit from the ambient env (AQ_TRACE_ID/AQ_SPAN_ID). The
    new span_id is exported to AQ_SPAN_ID for nested/child-process spans, then
    restored on exit.
    """
    trace_id = ensure_trace_id()
    parent = current_span_id()
    sid = _gen_id(16)
    s = Span(name=name, agent=agent, trace_id=trace_id, span_id=sid,
             parent_span_id=parent, start_ts=time.time(), attrs=dict(attrs or {}))

    _emit("trace.span.start", s)
    prev_span = os.environ.get("AQ_SPAN_ID")
    os.environ["AQ_SPAN_ID"] = sid
    try:
        yield s
        if s.status == "unset":
            s.status = "ok"
    except BaseException as exc:  # noqa: BLE001 — record then re-raise
        s.record_error(exc)
        raise
    finally:
        if prev_span is None:
            os.environ.pop("AQ_SPAN_ID", None)
        else:
            os.environ["AQ_SPAN_ID"] = prev_span
        s.set_attr("duration_s", round(time.time() - s.start_ts, 3))
        _emit("trace.span.end", s)
        _otlp_export(s)


def _emit(kind: str, s: Span) -> None:
    """Append a span event carrying trace fields on the envelope itself."""
    from contracts.events import Envelope

    env = Envelope(
        agent=s.agent, type=kind, subject=s.name,
        payload={"attrs": s.attrs, "status": s.status, "error": s.error, "start_ts": s.start_ts},
        trace_id=s.trace_id, span_id=s.span_id, parent_span_id=s.parent_span_id,
    )
    event_log.append(env)


# ── reconstruction ───────────────────────────────────────────────────────────

@dataclass
class SpanNode:
    span_id: str
    parent_span_id: Optional[str]
    name: str
    agent: str
    status: str
    duration_s: Optional[float]
    error: Optional[str]
    start_ts: float
    children: list["SpanNode"] = field(default_factory=list)


def reconstruct(trace_id: str) -> list[SpanNode]:
    """Return root SpanNodes for a trace (children nested), ordered by start."""
    ends: dict[str, SpanNode] = {}
    starts: dict[str, float] = {}
    for ev in event_log.read_all():
        if ev.trace_id != trace_id or not ev.span_id:
            continue
        if ev.type == "trace.span.start":
            starts[ev.span_id] = ev.payload.get("start_ts", ev.ts)
        elif ev.type == "trace.span.end":
            ends[ev.span_id] = SpanNode(
                span_id=ev.span_id, parent_span_id=ev.parent_span_id,
                name=ev.subject or "?", agent=ev.agent,
                status=ev.payload.get("status", "unset"),
                duration_s=(ev.payload.get("attrs") or {}).get("duration_s"),
                error=ev.payload.get("error"),
                start_ts=ev.payload.get("start_ts", ev.ts),
            )
    # Fill start-only spans (still running / crashed before end).
    for sid, st in starts.items():
        if sid not in ends:
            ends[sid] = SpanNode(sid, None, "?(incomplete)", "?", "incomplete", None, None, st)
    roots: list[SpanNode] = []
    for node in ends.values():
        parent = ends.get(node.parent_span_id) if node.parent_span_id else None
        if parent is not None:
            parent.children.append(node)
        else:
            roots.append(node)
    for node in ends.values():
        node.children.sort(key=lambda n: n.start_ts)
    roots.sort(key=lambda n: n.start_ts)
    return roots


def render_tree(trace_id: str) -> str:
    """ASCII trace waterfall for aq-event trace / CLI diagnosis."""
    lines: list[str] = [f"trace {trace_id}"]

    def _walk(node: SpanNode, depth: int) -> None:
        dur = f"{node.duration_s:.3f}s" if node.duration_s is not None else "…"
        mark = {"ok": "✓", "error": "✗", "incomplete": "⋯"}.get(node.status, "•")
        line = f"{'  ' * depth}{mark} {node.name} [{node.agent}] {dur}"
        if node.error:
            line += f"  ERROR: {node.error}"
        lines.append(line)
        for c in node.children:
            _walk(c, depth + 1)

    roots = reconstruct(trace_id)
    if not roots:
        return f"trace {trace_id}: no spans found"
    for r in roots:
        _walk(r, 1)
    return "\n".join(lines)


def _otlp_export(s: Span) -> None:
    """Optional OTLP export. No-op unless OTEL endpoint + SDK are present."""
    if not os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT"):
        return
    try:  # pragma: no cover - optional path
        from opentelemetry import trace as _ot  # type: ignore  # noqa: F401
        # Full OTLP wiring is a follow-up; presence check keeps the hook honest.
    except Exception:
        pass


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "show":
        print(render_tree(sys.argv[2]))
    else:
        print("usage: trace.py show <trace_id>")
