#!/usr/bin/env python3
"""gen-api-client — generate a typed Python client from the dashboard OpenAPI spec.

god-tier prompt 9 (WS6): the Command Center rebuild is OpenAPI-first. FastAPI
already publishes /openapi.json; this turns it into a GENERATED typed client so
views, CLI tools, and tests stop hand-rolling urllib against string paths. Regen
whenever the API changes — the client never drifts from the contract.

Generates scripts/ai/lib/aq_dashboard_client.py: one method per /api GET route,
path params as typed args, docstrings from the spec summary. No third-party
codegen dependency (stdlib only), so it runs anywhere in the harness.

Usage:
  gen-api-client.py                 # fetch live spec from :8889, regenerate
  gen-api-client.py --spec FILE     # from a saved openapi.json
  gen-api-client.py --check         # exit 1 if the generated client is stale
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import sys
import urllib.request
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent.parent
_OUT = _REPO / "scripts" / "ai" / "lib" / "aq_dashboard_client.py"
_DEFAULT_URL = "http://127.0.0.1:8889/openapi.json"


def _method_name(path: str, verb: str) -> str:
    # /api/scheduler/queue -> get_scheduler_queue ; /api/trace/{trace_id} -> get_trace
    parts = [p for p in re.split(r"[/{}]", path) if p and p != "api"]
    name = "_".join(parts)
    name = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    ident = f"{verb}_{name}".strip("_").lower()
    if keyword.iskeyword(ident):
        ident += "_"
    return ident


def _path_params(path: str) -> list[str]:
    return re.findall(r"\{([^}]+)\}", path)


def generate(spec: dict) -> str:
    paths = spec.get("paths", {})
    api_gets = sorted(
        (p, m) for p, methods in paths.items()
        for m in methods if m == "get" and p.startswith("/api")
    )
    lines = [
        "#!/usr/bin/env python3",
        '"""GENERATED by scripts/ai/gen-api-client.py — do not edit by hand.',
        "",
        "Typed client for the Command Center dashboard API (OpenAPI-first, WS6).",
        "Regenerate with: python3 scripts/ai/gen-api-client.py",
        '"""',
        "from __future__ import annotations",
        "import json as _json",
        "import urllib.parse as _urlparse",
        "import urllib.request as _urlreq",
        "from typing import Any",
        "",
        "",
        "class AqDashboardClient:",
        '    """Generated typed client. One method per /api GET route."""',
        "",
        "    def __init__(self, base_url: str = \"http://127.0.0.1:8889\", timeout: float = 10.0):",
        "        self.base_url = base_url.rstrip('/')",
        "        self.timeout = timeout",
        "",
        "    def _get(self, path: str, params: dict | None = None) -> Any:",
        "        url = self.base_url + path",
        "        if params:",
        "            url += '?' + _urlparse.urlencode({k: v for k, v in params.items() if v is not None})",
        "        with _urlreq.urlopen(url, timeout=self.timeout) as r:",
        "            return _json.loads(r.read())",
        "",
    ]
    for path, verb in api_gets:
        meth = _method_name(path, verb)
        params = _path_params(path)
        op = paths[path][verb]
        summary = (op.get("summary") or op.get("description") or "").strip().splitlines()[0:1]
        doc = summary[0] if summary else f"{verb.upper()} {path}"
        args = "".join(f", {p}: str" for p in params)
        # Substitute path params into an f-string-safe path.
        route = path
        for p in params:
            route = route.replace("{" + p + "}", "{" + p + "}")
        lines.append(f"    def {meth}(self{args}) -> Any:")
        lines.append(f'        """{doc}"""')
        if params:
            lines.append(f'        return self._get(f"{route}")')
        else:
            lines.append(f'        return self._get("{path}")')
        lines.append("")
    return "\n".join(lines) + "\n"


def _load_spec(args) -> dict:
    if args.spec:
        return json.loads(Path(args.spec).read_text())
    with urllib.request.urlopen(args.url, timeout=10) as r:
        return json.loads(r.read())


def main() -> int:
    ap = argparse.ArgumentParser(prog="gen-api-client.py")
    ap.add_argument("--spec", help="Path to a saved openapi.json")
    ap.add_argument("--url", default=_DEFAULT_URL)
    ap.add_argument("--check", action="store_true", help="Exit 1 if generated client is stale")
    args = ap.parse_args()

    spec = _load_spec(args)
    generated = generate(spec)

    if args.check:
        current = _OUT.read_text() if _OUT.exists() else ""
        if current.strip() != generated.strip():
            print("STALE: aq_dashboard_client.py differs from the current OpenAPI spec — "
                  "run: python3 scripts/ai/gen-api-client.py", file=sys.stderr)
            return 1
        print("OK: generated client matches the spec")
        return 0

    _OUT.write_text(generated)
    n = generated.count("    def ") - 2  # minus __init__ and _get
    print(f"wrote {_OUT.relative_to(_REPO)} ({n} typed methods)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
