#!/usr/bin/env python3
"""
Research Phase - Local LLM-Driven Pattern Discovery & Hypothesis Generation

The local LLM acts as "Research Director" analyzing system behavior patterns,
discovering optimization opportunities, and generating testable hypotheses.

This transforms the local LLM from a passive responder into an active researcher
that drives the autonomous improvement loop.
"""

import asyncio
import json
import uuid
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import aiohttp
import psycopg2
from psycopg2.extras import RealDictCursor

from trend_database import TrendDatabase, TrendAnalysis


@dataclass
class OptimizationHypothesis:
    """
    A testable hypothesis about how to improve system performance
    Generated by local LLM based on observed patterns
    """
    hypothesis_id: str
    hypothesis_type: str  # PROMPT_OPTIMIZATION, CONFIG_TUNING, ARCHITECTURE_CHANGE, etc.
    description: str
    evidence: Dict[str, Any]  # Metrics, trends, observations supporting this hypothesis
    experiment_config: Dict[str, Any]  # Baseline/variant configuration for testing
    estimated_impact: str  # Expected improvement estimate
    risk_level: str  # low, medium, high
    priority_score: float  # 0.0-1.0 for ranking
    generated_by: str  # llama-cpp-local, etc.
    generated_at: datetime

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d['generated_at'] = self.generated_at.isoformat()
        return d


class ResearchPhase:
    """
    Uses local LLM to conduct autonomous research on system performance
    """

    def __init__(
        self,
        llm_url: str = "http://localhost:8080/v1/chat/completions",
        pg_host: str = "127.0.0.1",
        pg_port: int = 5432,
        pg_user: str = "aidb",
        pg_database: str = "aidb",
        pg_password: Optional[str] = None,
    ):
        self.llm_url = llm_url
        self.pg_host = pg_host
        self.pg_port = pg_port
        self.pg_user = pg_user
        self.pg_database = pg_database
        self.pg_password = pg_password

        self.trend_db = TrendDatabase(
            pg_host=pg_host,
            pg_port=pg_port,
            pg_user=pg_user,
            pg_database=pg_database,
            pg_password=pg_password,
        )

    async def call_local_llm(
        self,
        prompt: str,
        max_tokens: int = 1000,
        temperature: float = 0.7,
        system_prompt: Optional[str] = None,
    ) -> str:
        """
        Call local LLM for research and hypothesis generation
        Higher temperature (0.7) for creative hypothesis generation
        """
        messages = []

        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        else:
            messages.append({
                "role": "system",
                "content": (
                    "You are an AI system performance researcher and optimizer. "
                    "You analyze metrics, discover patterns, generate optimization hypotheses, "
                    "and propose evidence-based experiments. Be creative but grounded in data."
                )
            })

        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": "local",
            "messages": messages,
            "max_tokens": max_tokens,
            "temperature": temperature,
        }

        async with aiohttp.ClientSession() as session:
            async with session.post(self.llm_url, json=payload, timeout=aiohttp.ClientTimeout(total=60)) as resp:
                if resp.status != 200:
                    raise Exception(f"LLM API error: {resp.status}")

                result = await resp.json()
                return result["choices"][0]["message"]["content"]

    async def analyze_anomalies(
        self,
        anomalies: List[Dict[str, Any]],
        trends: List[TrendAnalysis],
    ) -> List[OptimizationHypothesis]:
        """
        Use local LLM to analyze anomalies and trends, generate optimization hypotheses
        This is where the LLM does autonomous research
        """
        if not anomalies:
            return []

        # Build rich context for LLM analysis
        context_summary = self._build_context_summary(anomalies, trends)

        # Generate hypotheses using local LLM
        hypotheses_raw = await self._generate_hypotheses_with_llm(context_summary, anomalies)

        # Parse and validate hypotheses
        hypotheses = []
        for hyp_raw in hypotheses_raw:
            try:
                hypothesis = self._parse_hypothesis(hyp_raw, anomalies)
                if hypothesis:
                    hypotheses.append(hypothesis)
            except Exception as e:
                print(f"⚠️  Failed to parse hypothesis: {e}")
                continue

        # Rank by priority
        hypotheses.sort(key=lambda h: h.priority_score, reverse=True)

        return hypotheses

    def _build_context_summary(
        self,
        anomalies: List[Dict[str, Any]],
        trends: List[TrendAnalysis],
    ) -> Dict[str, Any]:
        """
        Build comprehensive context for LLM analysis
        """
        # Anomaly summary
        anomaly_summary = []
        for anomaly in anomalies:
            if anomaly["type"] == "degrading_trend":
                anomaly_summary.append({
                    "type": "performance_degradation",
                    "metric": anomaly["metric_name"],
                    "change": f"{anomaly['change_pct']:.1f}%",
                    "from": anomaly["baseline_value"],
                    "to": anomaly["current_value"],
                    "severity": anomaly["severity"],
                })
            elif anomaly["type"] == "high_volatility":
                anomaly_summary.append({
                    "type": "instability",
                    "metric": anomaly["metric_name"],
                    "volatility": anomaly["volatility"],
                    "current": anomaly["current_value"],
                    "severity": anomaly["severity"],
                })

        # Trend summary
        trend_summary = []
        for trend in trends:
            trend_summary.append({
                "metric": trend.metric_name,
                "direction": trend.trend_direction,
                "change": f"{trend.change_pct:.1f}%",
                "volatility": trend.volatility,
                "window": trend.time_window,
            })

        return {
            "anomalies": anomaly_summary,
            "trends": trend_summary,
            "timestamp": datetime.now().isoformat(),
        }

    async def _generate_hypotheses_with_llm(
        self,
        context: Dict[str, Any],
        anomalies: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Ask local LLM to generate optimization hypotheses based on context
        """
        prompt = f"""Analyze this AI system performance data and generate optimization hypotheses:

## Anomalies Detected:
{json.dumps(context['anomalies'], indent=2)}

## Recent Trends:
{json.dumps(context['trends'], indent=2)}

## Your Task:
Generate 3-5 specific, testable optimization hypotheses that could address these issues.

For each hypothesis, provide:
1. **Type**: PROMPT_OPTIMIZATION, CONFIG_TUNING, CACHING_STRATEGY, ROUTING_OPTIMIZATION, or ARCHITECTURE_CHANGE
2. **Description**: What to change and why (1-2 sentences)
3. **Evidence**: Which metrics/patterns support this hypothesis
4. **Experiment**: How to test it (baseline vs variant config)
5. **Estimated Impact**: Expected improvement (be specific: "15% faster", "20% fewer errors", etc.)
6. **Risk Level**: low, medium, or high
7. **Priority**: 0.0-1.0 (how important/likely to succeed)

Respond in JSON array format:
```json
[
  {{
    "type": "CONFIG_TUNING",
    "description": "Increase cache TTL from 5min to 15min to reduce recomputation overhead",
    "evidence": {{"metric": "cache_hit_rate", "observation": "drops 15% every 5min", "pattern": "high churn"}},
    "experiment": {{
      "baseline": {{"cache_ttl_seconds": 300}},
      "variant": {{"cache_ttl_seconds": 900}}
    }},
    "estimated_impact": "20% reduction in cache misses, 10% faster response times",
    "risk_level": "low",
    "priority": 0.85
  }},
  ...
]
```

Focus on hypotheses that:
- Have clear evidence in the data
- Are testable with A/B experiments
- Have measurable success criteria
- Address root causes, not just symptoms
"""

        try:
            response = await self.call_local_llm(
                prompt,
                max_tokens=2000,
                temperature=0.7,  # Higher for creative hypothesis generation
            )

            # Extract JSON from response
            if "```json" in response:
                response = response.split("```json")[1].split("```")[0].strip()
            elif "```" in response:
                response = response.split("```")[1].split("```")[0].strip()

            hypotheses = json.loads(response)

            # Validate format
            if not isinstance(hypotheses, list):
                print(f"⚠️  LLM returned non-list: {type(hypotheses)}")
                return []

            return hypotheses

        except Exception as e:
            print(f"⚠️  LLM hypothesis generation failed: {e}")
            # Fallback: generate simple hypothesis from most severe anomaly
            return self._generate_fallback_hypothesis(anomalies)

    def _generate_fallback_hypothesis(
        self,
        anomalies: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Fallback hypothesis generation if LLM fails
        """
        if not anomalies:
            return []

        # Find most severe anomaly
        primary = max(
            anomalies,
            key=lambda a: {"critical": 4, "high": 3, "medium": 2, "low": 1}.get(a.get("severity", "low"), 0)
        )

        if primary["type"] == "degrading_trend":
            return [{
                "type": "CONFIG_TUNING",
                "description": f"Investigate {primary['metric_name']} degradation and restore baseline performance",
                "evidence": {
                    "metric": primary['metric_name'],
                    "change_pct": primary['change_pct'],
                    "severity": primary['severity'],
                },
                "experiment": {
                    "baseline": {"current_config": True},
                    "variant": {"restore_previous_config": True},
                },
                "estimated_impact": f"Restore {abs(primary['change_pct']):.1f}% performance loss",
                "risk_level": "medium",
                "priority": 0.75,
            }]

        return []

    def _parse_hypothesis(
        self,
        hyp_raw: Dict[str, Any],
        anomalies: List[Dict[str, Any]],
    ) -> Optional[OptimizationHypothesis]:
        """
        Parse and validate hypothesis from LLM output
        """
        # Validate required fields
        required_fields = ["type", "description", "evidence", "experiment", "estimated_impact", "risk_level", "priority"]
        for field in required_fields:
            if field not in hyp_raw:
                print(f"⚠️  Missing required field in hypothesis: {field}")
                return None

        # Validate types
        valid_types = [
            "PROMPT_OPTIMIZATION", "CONFIG_TUNING", "ARCHITECTURE_CHANGE",
            "MODEL_SELECTION", "CACHING_STRATEGY", "ROUTING_OPTIMIZATION",
            "HINT_DIVERSITY", "MEMORY_TUNING", "OTHER"
        ]
        if hyp_raw["type"] not in valid_types:
            print(f"⚠️  Invalid hypothesis type: {hyp_raw['type']}")
            hyp_raw["type"] = "OTHER"

        # Validate risk level
        if hyp_raw["risk_level"] not in ["low", "medium", "high"]:
            hyp_raw["risk_level"] = "medium"

        # Clamp priority to 0.0-1.0
        try:
            priority = float(hyp_raw["priority"])
            priority = max(0.0, min(1.0, priority))
        except (ValueError, TypeError):
            priority = 0.5

        # Generate hypothesis ID
        hypothesis_id = f"h-{datetime.now().strftime('%Y-%m-%d')}-{str(uuid.uuid4())[:8]}"

        return OptimizationHypothesis(
            hypothesis_id=hypothesis_id,
            hypothesis_type=hyp_raw["type"],
            description=hyp_raw["description"],
            evidence=hyp_raw["evidence"],
            experiment_config=hyp_raw["experiment"],
            estimated_impact=hyp_raw["estimated_impact"],
            risk_level=hyp_raw["risk_level"],
            priority_score=priority,
            generated_by="llama-cpp-local",
            generated_at=datetime.now(),
        )

    def store_hypotheses(
        self,
        hypotheses: List[OptimizationHypothesis],
        cycle_id: Optional[str] = None,
    ) -> int:
        """
        Store hypotheses to PostgreSQL
        Returns number of hypotheses stored
        """
        if not hypotheses:
            return 0

        conn = psycopg2.connect(
            host=self.pg_host,
            port=self.pg_port,
            user=self.pg_user,
            database=self.pg_database,
            password=self.pg_password,
        )

        try:
            cursor = conn.cursor()

            for hypothesis in hypotheses:
                cursor.execute(
                    """
                    INSERT INTO optimization_hypotheses
                        (id, hypothesis_id, cycle_id, hypothesis_type, description,
                         evidence, experiment_config, estimated_impact, risk_level,
                         priority_score, generated_by, generated_at)
                    VALUES (gen_random_uuid(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (hypothesis_id) DO NOTHING
                    """,
                    (
                        hypothesis.hypothesis_id,
                        cycle_id,
                        hypothesis.hypothesis_type,
                        hypothesis.description,
                        json.dumps(hypothesis.evidence),
                        json.dumps(hypothesis.experiment_config),
                        hypothesis.estimated_impact,
                        hypothesis.risk_level,
                        hypothesis.priority_score,
                        hypothesis.generated_by,
                        hypothesis.generated_at,
                    ),
                )

            conn.commit()
            stored = cursor.rowcount
            cursor.close()

            return stored

        finally:
            conn.close()

    async def conduct_research(
        self,
        trigger_event_id: str,
    ) -> List[OptimizationHypothesis]:
        """
        Main research pipeline:
        1. Gather context (anomalies, trends, historical patterns)
        2. Use local LLM to analyze and generate hypotheses
        3. Rank hypotheses by priority
        4. Store to PostgreSQL
        5. Return top hypotheses for execution
        """
        print("🔬 Research Phase - Local LLM Pattern Discovery")
        print("=" * 60)

        # Step 1: Gather context
        print("\n📊 Step 1: Gathering system context...")
        anomalies = self.trend_db.detect_anomalies()
        print(f"   Found {len(anomalies)} anomalies")

        # Get recent trends
        trends = []
        for metric in ["cache_hit_rate", "local_routing_pct", "experiment_success_rate"]:
            for window in ["1h", "24h", "7d"]:
                trend = self.trend_db.compute_trend(metric, window)
                if trend and trend.trend_direction != "insufficient_data":
                    trends.append(trend)

        print(f"   Analyzed {len(trends)} metric trends")

        # Step 2: LLM analysis
        print("\n🤖 Step 2: Local LLM analyzing patterns...")
        hypotheses = await self.analyze_anomalies(anomalies, trends)
        print(f"   Generated {len(hypotheses)} optimization hypotheses")

        # Step 3: Display hypotheses
        print("\n📋 Step 3: Optimization Hypotheses (ranked by priority):")
        for i, hyp in enumerate(hypotheses, 1):
            print(f"\n   {i}. [{hyp.hypothesis_type}] Priority: {hyp.priority_score:.2f} | Risk: {hyp.risk_level}")
            print(f"      {hyp.description}")
            print(f"      Expected: {hyp.estimated_impact}")
            print(f"      ID: {hyp.hypothesis_id}")

        # Step 4: Store hypotheses
        print("\n💾 Step 4: Storing hypotheses to PostgreSQL...")
        stored = self.store_hypotheses(hypotheses)
        print(f"   Stored {stored} hypotheses")

        print("\n✅ Research phase complete")
        return hypotheses


async def main():
    """
    Example usage: Run research phase on current system state
    """
    # Read password from secrets
    pg_password = None
    secret_path = Path("/run/secrets/postgres_password")
    if secret_path.exists():
        pg_password = secret_path.read_text().strip()

    research = ResearchPhase(pg_password=pg_password)

    # First, sync latest metrics
    print("📊 Syncing latest metrics...")
    await research.trend_db.sync_metrics_pipeline(since_hours=24)

    # Then conduct research
    hypotheses = await research.conduct_research(trigger_event_id="manual-test")

    if hypotheses:
        print(f"\n🎯 Top hypothesis for testing:")
        top = hypotheses[0]
        print(f"   Type: {top.hypothesis_type}")
        print(f"   Description: {top.description}")
        print(f"   Priority: {top.priority_score:.2f}")
        print(f"   Risk: {top.risk_level}")
        print(f"\n   Next step: Execute experiment via autoresearch framework")
    else:
        print("\n✅ No optimization opportunities detected - system healthy")


if __name__ == "__main__":
    asyncio.run(main())
