apiVersion: apps/v1
kind: Deployment
metadata:
  name: aider
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: local-ai-aider
          stdin: true
          tty: true
          command:
            - sleep
            - infinity
