apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
spec:
  $patch: replace
  type: ClusterIP
  selector:
    io.kompose.service: grafana
  ports:
    - name: grafana
      port: 3002
      targetPort: 3000
