#!/usr/bin/env bash
set -euo pipefail

# aqos-install-vm-ai-dev-dogfood.sh — full-factory (ai-dev/aiStack-ON)
# service-TOPOLOGY harness (slice s1c,
# .agents/plans/aqos-installer-experience/END-TO-END-BARE-METAL-PLAN.md).
#
# Unlike scripts/testing/aqos-vm-dogfood.sh (golden aqos-workstation
# profile, AI OFF) and scripts/testing/aqos-install-vm-dogfood.sh (disko
# disk/install MECHANICS for that same AI-OFF profile), this harness targets
# `.#nixosConfigurations.aqos-install-vm-ai-dev` — the ai-dev/aiStack-ON
# variant of the aqos-install-vm host, auto-generated by flake.nix's host x
# profile matrix (profiles = ["ai-dev" "gaming" "minimal"]). It proves the
# DECLARATIVE CONFIG reproduces the full AI agentic factory's service
# topology in a disposable QEMU VM: llama.cpp is DECLARED (no model is
# provisioned in this VM — model files are per-deployment runtime state, not
# part of "the config reproduces"), while AIDB, hybrid-coordinator,
# switchboard, and the command-center dashboard (the service the 216/GROUP
# fix targets) must all reach systemd ACTIVE.
#
# Follows the SAME build-vm + service-health pattern as aqos-vm-dogfood.sh
# (`nix build .#nixosConfigurations.<host>.config.system.build.vm`, headless
# `-nographic` qemu, scrape /dev/console for a greppable marker line) rather
# than disko's rootless in-VM test framework — s1a already proved disk/
# install mechanics; this harness is about SERVICE HEALTH, not partitioning.
#
# Usage:
#   scripts/testing/aqos-install-vm-ai-dev-dogfood.sh          # Step A only (fast gate)
#   scripts/testing/aqos-install-vm-ai-dev-dogfood.sh --full    # Step A + Step B (build+boot)
#
# Env overrides:
#   AQOS_AI_DEV_VM_HOST           nixosConfigurations attr (default: aqos-install-vm-ai-dev)
#   AQOS_AI_DEV_VM_EVAL_TIMEOUT   seconds allowed for `nix eval` (default: 300)
#   AQOS_AI_DEV_VM_BUILD_TIMEOUT  seconds allowed for `nix build ...build.vm` (default: 2400)
#   AQOS_AI_DEV_VM_BOOT_TIMEOUT   seconds allowed for the VM to reach both boot
#                                 markers (default: 900 — AI-stack services take
#                                 longer to bind than the golden AI-off profile)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

HOST="${AQOS_AI_DEV_VM_HOST:-aqos-install-vm-ai-dev}"
FLAKE_TARGET=".#nixosConfigurations.${HOST}"
EVAL_TIMEOUT="${AQOS_AI_DEV_VM_EVAL_TIMEOUT:-300}"
BUILD_TIMEOUT="${AQOS_AI_DEV_VM_BUILD_TIMEOUT:-2400}"
BOOT_TIMEOUT="${AQOS_AI_DEV_VM_BOOT_TIMEOUT:-900}"
GOLDEN_MARKER="AQOS-INSTALL-VM-DOGFOOD-BOOT-OK"
TOPOLOGY_MARKER="AQOS-INSTALL-VM-AI-DEV-FACTORY-TOPOLOGY-OK"
TOPOLOGY_MARKER_FAIL="AQOS-INSTALL-VM-AI-DEV-FACTORY-TOPOLOGY-FAIL"

FULL=0
for arg in "$@"; do
  case "$arg" in
    --full) FULL=1 ;;
    -h|--help)
      sed -n '1,32p' "$0"
      exit 0
      ;;
    *)
      echo "[FAIL] unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

pass() { echo "[PASS] $*"; }
warn() { echo "[WARN] $*" >&2; }
info() { echo "[INFO] $*"; }
fail() { echo "[FAIL] $*" >&2; exit 1; }
skip() { echo "[SKIP] $*"; }

STEP_A_STATUS="not-run"
STEP_B_STATUS="not-run"

# ---------------------------------------------------------------------------
# Step A (cheap, always): the ai-dev/aiStack-ON variant must EVALUATE as a
# real nixosConfiguration, and the ai-stack service units must actually be
# declared in the resolved systemd units — the same discipline as
# aqos-vm-dogfood.sh's golden-package check, applied to the factory's
# service set instead of a package list.
# ---------------------------------------------------------------------------
step_a() {
  if ! command -v nix >/dev/null 2>&1; then
    skip "step A: 'nix' not found on PATH — cannot evaluate ${FLAKE_TARGET}"
    STEP_A_STATUS="skip"
    return 0
  fi

  info "step A: evaluating ${FLAKE_TARGET}.config.system.build.toplevel.drvPath (timeout ${EVAL_TIMEOUT}s)"
  local drv_path errfile
  errfile=$(mktemp)
  if ! drv_path=$(timeout "${EVAL_TIMEOUT}" nix eval --raw \
        "${FLAKE_TARGET}.config.system.build.toplevel.drvPath" 2>"${errfile}"); then
    STEP_A_STATUS="fail"
    local errtext; errtext=$(cat "${errfile}"); rm -f "${errfile}"
    fail "step A: ${FLAKE_TARGET} does NOT evaluate — a broken host is the #1 thing this gate exists to catch.
--- nix eval error ---
${errtext}
--- end error ---"
  fi
  rm -f "${errfile}"
  pass "step A: ${FLAKE_TARGET} evaluates -> ${drv_path}"

  info "step A: checking the ai-stack service units are declared in the resolved config"
  local unit_names
  errfile=$(mktemp)
  if ! unit_names=$(timeout "${EVAL_TIMEOUT}" nix eval --json \
        "${FLAKE_TARGET}.config.systemd.units" \
        --apply 'u: builtins.attrNames u' 2>"${errfile}"); then
    STEP_A_STATUS="fail"
    local errtext2; errtext2=$(cat "${errfile}"); rm -f "${errfile}"
    fail "step A: could not evaluate systemd.units for ${FLAKE_TARGET}.
--- nix eval error ---
${errtext2}
--- end error ---"
  fi
  rm -f "${errfile}"

  local required_units=(
    "ai-aidb.service"
    "ai-hybrid-coordinator.service"
    "ai-switchboard.service"
    "command-center-dashboard-api.service"
    "llama-cpp.service"
    "aqos-install-vm-ai-dev-factory-topology.service"
  )
  local missing=()
  for unit in "${required_units[@]}"; do
    if ! grep -q "\"${unit}\"" <<<"${unit_names}"; then
      missing+=("${unit}")
    fi
  done
  if [ "${#missing[@]}" -ne 0 ]; then
    STEP_A_STATUS="fail"
    fail "step A: expected ai-stack service units missing from the resolved config: ${missing[*]} — the ai-dev profile / factory-topology marker did not wire in as expected."
  fi
  pass "step A: full-factory service units declared (${required_units[*]})"
  STEP_A_STATUS="pass"
}

# ---------------------------------------------------------------------------
# Step B (heavy, --full only): build a disposable VM and boot it headless,
# scraping the console for both the golden boot marker and the factory
# service-topology marker. Never requires sudo. Skips cleanly (not a
# failure) if build-vm or qemu are unavailable.
# ---------------------------------------------------------------------------
step_b() {
  if [ "${FULL}" -ne 1 ]; then
    skip "step B: not requested (pass --full to build+boot the disposable VM)"
    STEP_B_STATUS="skip"
    return 0
  fi
  if ! command -v nix >/dev/null 2>&1; then
    skip "step B: 'nix' not found on PATH — cannot build the VM"
    STEP_B_STATUS="skip"
    return 0
  fi
  if ! command -v qemu-system-x86_64 >/dev/null 2>&1 && ! command -v qemu-kvm >/dev/null 2>&1; then
    skip "step B: no qemu binary found on PATH — cannot boot the VM"
    STEP_B_STATUS="skip"
    return 0
  fi

  local work_dir
  work_dir="$(mktemp -d "${TMPDIR:-/tmp}/aqos-install-vm-ai-dev-dogfood.XXXXXX")"
  trap 'rm -rf "${work_dir}"' RETURN

  info "step B: nix build .#nixosConfigurations.${HOST}.config.system.build.vm (timeout ${BUILD_TIMEOUT}s, no sudo)"
  local result_link="${work_dir}/result"
  if ! timeout "${BUILD_TIMEOUT}" nix build \
        ".#nixosConfigurations.${HOST}.config.system.build.vm" -o "${result_link}" \
        >"${work_dir}/build.log" 2>&1; then
    STEP_B_STATUS="fail"
    tail -n 80 "${work_dir}/build.log" >&2 || true
    fail "step B: build-vm failed or timed out — see build log above (${work_dir}/build.log)."
  fi
  pass "step B: build-vm succeeded -> ${result_link}"

  local runvm
  runvm=$(find "${result_link}/bin" -maxdepth 1 -name 'run-*-vm' | head -n1)
  if [ -z "${runvm}" ]; then
    STEP_B_STATUS="fail"
    fail "step B: build-vm produced no ./result/bin/run-*-vm script."
  fi

  info "step B: booting ${runvm} headless (-nographic), boot timeout ${BOOT_TIMEOUT}s (AI-stack services take longer to bind)"
  local vm_log="${work_dir}/vm.log"
  : >"${vm_log}"
  QEMU_OPTS="-nographic -no-reboot -m 4096" QEMU_KERNEL_PARAMS="console=ttyS0" \
    "${runvm}" >"${vm_log}" 2>&1 &
  local vm_pid=$!

  local deadline=$((SECONDS + BOOT_TIMEOUT))
  local found_golden=0 found_topology=0 topology_ok=0
  while [ "${SECONDS}" -lt "${deadline}" ]; do
    grep -q "${GOLDEN_MARKER}" "${vm_log}" 2>/dev/null && found_golden=1
    if grep -q "${TOPOLOGY_MARKER}" "${vm_log}" 2>/dev/null; then
      found_topology=1
      topology_ok=1
    elif grep -q "${TOPOLOGY_MARKER_FAIL}" "${vm_log}" 2>/dev/null; then
      found_topology=1
      topology_ok=0
    fi
    if [ "${found_golden}" -eq 1 ] && [ "${found_topology}" -eq 1 ]; then
      break
    fi
    if ! kill -0 "${vm_pid}" 2>/dev/null; then
      break
    fi
    sleep 3
  done

  kill "${vm_pid}" 2>/dev/null || true
  wait "${vm_pid}" 2>/dev/null || true

  if [ "${found_golden}" -ne 1 ]; then
    STEP_B_STATUS="fail"
    tail -n 80 "${vm_log}" >&2 || true
    fail "step B: golden boot marker '${GOLDEN_MARKER}' not observed within ${BOOT_TIMEOUT}s — see VM console log above."
  fi
  if [ "${found_topology}" -ne 1 ]; then
    STEP_B_STATUS="fail"
    tail -n 80 "${vm_log}" >&2 || true
    fail "step B: factory-topology marker not observed within ${BOOT_TIMEOUT}s (neither OK nor FAIL) — service-health check likely still retrying, or the marker service itself did not start. See VM console log above."
  fi

  info "step B: topology detail lines from console:"
  grep "^topology: " "${vm_log}" || true

  if [ "${topology_ok}" -ne 1 ]; then
    STEP_B_STATUS="fail"
    fail "step B: VM booted but the full-factory service topology did NOT come up clean — see 'topology: <unit>=<state>' lines above for which service(s) failed."
  fi

  pass "step B: VM booted, golden marker confirmed, and full-factory service topology reached ACTIVE (AIDB, hybrid-coordinator, switchboard, dashboard) with llama-cpp.service DECLARED (no model provisioned)."
  STEP_B_STATUS="pass"
}

step_a
step_b

echo "ACTIVATION-AUDIT: aqos-install-vm-ai-dev-dogfood host=${HOST} step_a=${STEP_A_STATUS} step_b=${STEP_B_STATUS} sudo=never disposable=true model_provisioned=false"
