#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

pass_count=0
fail_count=0

if command -v rg >/dev/null 2>&1; then
  SEARCH_TOOL="rg"
else
  SEARCH_TOOL="grep"
  echo "[verify] ripgrep not found; using grep fallback"
fi

check_pattern() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  local matched=1
  if [[ "$SEARCH_TOOL" == "rg" ]]; then
    if rg -n "$pattern" "$file" >/dev/null 2>&1; then
      matched=0
    fi
  else
    if grep -nE "$pattern" "$file" >/dev/null 2>&1; then
      matched=0
    fi
  fi

  if [[ $matched -eq 0 ]]; then
    printf '[PASS] %s\n' "$label"
    pass_count=$((pass_count + 1))
  else
    printf '[FAIL] %s\n' "$label"
    fail_count=$((fail_count + 1))
  fi
}

check_absent_pattern() {
  local file="$1"
  local pattern="$2"
  local label="$3"
  local matched=1
  if [[ "$SEARCH_TOOL" == "rg" ]]; then
    if rg -n "$pattern" "$file" >/dev/null 2>&1; then
      matched=0
    fi
  else
    if grep -nE "$pattern" "$file" >/dev/null 2>&1; then
      matched=0
    fi
  fi

  if [[ $matched -eq 0 ]]; then
    printf '[FAIL] %s\n' "$label"
    fail_count=$((fail_count + 1))
  else
    printf '[PASS] %s\n' "$label"
    pass_count=$((pass_count + 1))
  fi
}

check_path_absent() {
  local path="$1"
  local label="$2"
  if [[ -e "$path" ]]; then
    printf '[FAIL] %s\n' "$label"
    fail_count=$((fail_count + 1))
  else
    printf '[PASS] %s\n' "$label"
    pass_count=$((pass_count + 1))
  fi
}

echo "[verify] Flake-first roadmap completion checks"

# Flake-first orchestration guardrails (current architecture)
check_pattern "nixos-quick-deploy.sh" 'MODE="switch"' 'Flake-first deploy defaults to switch mode'
check_pattern "AGENTS.md" 'Autonomous Ops Boundary' 'Compact agent guide documents unattended operating boundary'
check_pattern "AGENTS.md" 'docs/operations/AUTONOMOUS-OPERATIONS-POLICY.md' 'Compact agent guide links to autonomous operations policy'
check_pattern "AGENTS.md" 'docs/operations/procedures/AUTONOMOUS-SUDOERS-SETUP.md' 'Compact agent guide links to unattended sudoers setup'
check_pattern "AGENTS.md" 'Batch deploy cadence' 'Compact agent guide documents batched deploy cadence'
check_pattern "docs/operations/AUTONOMOUS-OPERATIONS-POLICY.md" 'Approval-Gated Actions' 'Autonomous operations policy defines approval-gated actions'
check_pattern "docs/operations/AUTONOMOUS-OPERATIONS-POLICY.md" 'nixos-quick-deploy.sh' 'Autonomous operations policy allows unattended deploy loops'
check_pattern "docs/operations/AUTONOMOUS-OPERATIONS-POLICY.md" '## Batching Rule' 'Autonomous operations policy defines batched execution cadence'
check_pattern "docs/operations/procedures/AUTONOMOUS-SUDOERS-SETUP.md" 'templates/agentic-workflow/autonomous-ops-sudoers.example' 'Autonomous sudoers guide references the installable template'
check_pattern "templates/agentic-workflow/autonomous-ops-sudoers.example" 'NOPASSWD: AIOPS_DEPLOY, AIOPS_REBUILD, AIOPS_SYSTEMCTL, AIOPS_JOURNALCTL, AIOPS_FLATPAK' 'Autonomous sudoers template scopes passwordless access to deploy and verification commands'
check_pattern "templates/agentic-workflow/autonomous-ops-sudoers.example" 'nixos-quick-deploy\.sh \*|systemctl \*|journalctl \*|nixos-rebuild \*|flatpak \*' 'Autonomous sudoers template allows arguments for approved unattended commands'
check_pattern "nixos-quick-deploy.sh" 'run_roadmap_completion_verification\(\)' 'Roadmap verification hook exists'
check_pattern "nixos-quick-deploy.sh" 'run_readiness_analysis\(\)' 'Readiness analyzer hook exists'
check_pattern "nixos-quick-deploy.sh" 'sudo_passwordless_ready\(\)' 'Quick deploy detects scoped passwordless sudo without requiring sudo -n true'
check_pattern "nixos-quick-deploy.sh" 'sudo_passwordless_command_allowed\(\)' 'Quick deploy scopes passwordless sudo to approved commands'
check_pattern "nixos-quick-deploy.sh" '\-\-run-privileged-helper' 'Quick deploy exposes a privileged helper path for scoped unattended sudo'
check_pattern "nixos-quick-deploy.sh" 'sudo -n systemctl restart "\$\{restart_units\[@\]\}"' 'Quick deploy preserves passwordless sudo on timed repo-backed service restarts'
check_pattern "nixos-quick-deploy.sh" 'sudo -n "\$\{BASH_SOURCE\[0\]\}" --run-privileged-helper -- "\$@"' 'Quick deploy routes non-allowlisted privileged subcommands through the approved script helper'
check_pattern "nixos-quick-deploy.sh" 'Skipping imperative runtime orchestration in deploy-clean' 'Imperative runtime orchestration is explicitly skipped'
check_pattern "scripts/deploy/deploy-clean.sh" 'is deprecated; use ./nixos-quick-deploy.sh' 'deploy-clean shim is deprecated and forwards to nixos-quick-deploy'

# Host resolution and readiness checks
check_pattern "nixos-quick-deploy.sh" 'resolve_host_from_flake_if_needed\(\)' 'Deploy entrypoint has host auto-resolution helper'
check_pattern "scripts/governance/analyze-clean-deploy-readiness.sh" 'resolve_host_from_flake_if_needed\(\)' 'Readiness analyzer has host auto-resolution helper'

# Lock safety + git declarative parity
check_pattern "nixos-quick-deploy.sh" 'is_locked_password_field\(\)' 'Deploy entrypoint has explicit lock marker detector'
check_pattern "nixos-quick-deploy.sh" 'Could not read password hash state' 'Unreadable password state is non-fatal'
check_pattern "nixos-quick-deploy.sh" 'persist_home_git_credentials_declarative\(\)' 'Declarative git projection helper exists'
check_pattern "nixos-quick-deploy.sh" 'credential.helper = lib.mkDefault' 'Declarative git credential helper projection exists'

# Home/Nix wiring for host-scoped declarative overlays
check_pattern "flake.nix" 'hostDeployOptionsPath' 'Root flake includes host deploy options path'
check_pattern "flake.nix" 'hostHomeDeployOptionsPath' 'Root flake includes host home deploy options path'

# Centralized AI port registry + OTEL collector guardrails
check_pattern "nix/modules/core/options.nix" 'ports = \{' 'Centralized port registry exists'
check_pattern "nix/modules/core/options.nix" 'qdrantHttp = lib.mkOption' 'Port registry includes Qdrant HTTP'
check_pattern "nix/modules/core/options.nix" 'qdrantGrpc = lib.mkOption' 'Port registry includes Qdrant gRPC'
check_pattern "nix/modules/core/options.nix" 'otlpGrpc = lib.mkOption' 'Port registry includes OTLP gRPC'
check_pattern "nix/modules/core/options.nix" 'otlpHttp = lib.mkOption' 'Port registry includes OTLP HTTP'
check_pattern "nix/modules/core/options.nix" 'otelCollectorMetrics = lib.mkOption' 'Port registry includes OTEL collector metrics'
check_pattern "nix/modules/services/mcp-servers.nix" 'qdrantUrl = "http://127.0.0.1:\$\{toString ports.qdrantHttp\}"' 'MCP services derive Qdrant URL from port registry'
check_pattern "nix/modules/services/mcp-servers.nix" 'otlpEndpoint = "http://127.0.0.1:\$\{toString ports.otlpGrpc\}"' 'MCP services derive OTLP endpoint from port registry'
check_pattern "nix/modules/core/options.nix" 'remoteModelAliases = \{' 'Switchboard exposes declarative remote model aliases'
check_pattern "nix/modules/core/options.nix" 'remoteBudget = \{' 'Switchboard exposes declarative remote budget controls'
check_pattern "nix/modules/core/options.nix" 'addCheck lib\.types\.int \(value: value >= 0\)' 'Switchboard remote token cap uses portable non-negative int type'
check_pattern "nix/modules/core/options.nix" 'Optional local token-discipline heuristic|not a provider or subscription hard limit' 'Switchboard remote budget is documented as a local heuristic, not a hard provider limit'
check_pattern "nix/modules/core/options.nix" 'remoteLlmApiKey = lib.mkOption' 'Secrets options expose remote LLM API key name'
check_pattern "nix/modules/core/secrets.nix" 'needsRemoteLlmSecret = swb\.enable && swb\.remoteUrl != null && swb\.remoteApiKeyFile == null;' 'Remote LLM SOPS secret is only required when switchboard remote routing is configured'
check_pattern "nix/modules/core/secrets.nix" 'optionalAttrs needsRemoteLlmSecret' 'SOPS runtime secrets gate remote LLM API key exposure'
check_pattern "nix/modules/services/switchboard.nix" 'sec\.enable && remoteEnabled' 'Switchboard only defaults to declarative remote LLM secret path when remote routing is enabled'
check_pattern "nix/modules/services/switchboard.nix" 'SWB_REMOTE_DAILY_TOKEN_CAP' 'Switchboard injects remote daily token cap env'
check_pattern "nix/modules/services/switchboard.nix" 'remote-free|remote-coding|remote-reasoning' 'Switchboard exposes remote profile lanes'
check_pattern "nix/modules/services/switchboard.nix" '_remote_budget_status|remote_budget_exhausted' 'Switchboard enforces remote budget guardrails'
check_pattern "nix/modules/services/switchboard.nix" 'char_estimate = int\(\(len\(text\) \+ 3\) / 4\)' 'Switchboard token estimation keeps a character-based floor for dense prompts'
check_pattern "nix/modules/services/switchboard.nix" '_truncate_message_to_token_budget' 'Switchboard can truncate one oversized message instead of only dropping whole turns'
check_pattern "nix/modules/services/mcp-servers.nix" 'knowledgeSyncPath|ai-sync-knowledge-sources' 'Knowledge source sync service has dedicated runtime wiring'
check_pattern "nix/modules/services/mcp-servers.nix" 'PATH=\$\{knowledgeSyncPath\}' 'Knowledge source sync service gets an explicit Python-capable PATH'
check_pattern "nix/modules/services/switchboard.nix" 'unitConfig = \{' 'Switchboard declares systemd unit-level settings explicitly'
check_pattern "nix/modules/services/switchboard.nix" 'StartLimitIntervalSec = "300";' 'Switchboard sets restart rate limiting on the unit'
check_absent_pattern "scripts/governance/manage-secrets.py" 'This script is deprecated' 'Secrets manager entrypoint is active, not deprecated'
check_pattern "scripts/governance/manage-secrets.py" 'Manage external SOPS secrets for the AI stack' 'Secrets manager exposes a real CLI parser'
check_pattern "scripts/governance/manage-secrets.py" 'ensure-local-config' 'Secrets manager can refresh gitignored local host wiring'
check_pattern "scripts/governance/manage-secrets.py" 'subparsers\.add_parser\("bootstrap"' 'Secrets manager exposes delegated bootstrap flow'
check_pattern "scripts/governance/manage-secrets.py" 'subparsers\.add_parser\("doctor"' 'Secrets manager exposes readiness doctor flow'
check_pattern "scripts/governance/manage-secrets.py" 'subparsers\.add_parser\("remote-guide"' 'Secrets manager exposes remote onboarding guidance'
check_pattern "scripts/governance/manage-secrets.py" 'Requested secret set ready:' 'Secrets manager doctor reports readiness summary'
check_pattern "scripts/governance/manage-secrets.py" '"next_steps": next_steps|--format", choices=\["text", "json"\]' 'Secrets manager doctor exposes machine-readable readiness output'
check_pattern "scripts/governance/manage-secrets.py" 'print_post_action_doctor_summary\(' 'Secrets manager reuses readiness summary after mutating commands'
check_pattern "scripts/governance/manage-secrets.py" 'resolve_runtime_context\(' 'Secrets manager centralizes host/path runtime context loading'
check_pattern "scripts/governance/manage-secrets.py" 'ensure_secret_wiring\(' 'Secrets manager centralizes age+sops+local override wiring'
check_pattern "scripts/governance/manage-secrets.py" 'Core ready:|All managed secrets ready:' 'Secrets manager status distinguishes core vs full readiness'
check_pattern "scripts/governance/manage-secrets.py" 'status_parser\.add_argument\("--format", choices=\["text", "json"\]' 'Secrets manager status exposes machine-readable JSON output'
check_pattern "scripts/governance/manage-secrets.py" 'classify_missing_secrets\(|missing_by_scope' 'Secrets manager categorizes missing secrets by core, optional, and remote scope'
check_pattern "scripts/governance/manage-secrets.py" 'status_next_steps\(|"next_steps": next_steps' 'Secrets manager status exposes recommended next steps'
check_pattern "scripts/governance/manage-secrets.py" 'remote_onboarding_guide\(|remote_onboarding_config_snippet\(' 'Secrets manager builds remote-routing onboarding guidance'
check_pattern "scripts/governance/manage-secrets.py" 'arcee-ai/trinity-large-preview:free|qwen/qwen3-coder:free|nvidia/nemotron-3-super-120b-a12b:free' 'Secrets manager remote guide includes concrete OpenRouter alias examples'
check_pattern "scripts/governance/manage-secrets.py" 'missing_secret_details\(|user-supplied external credential|generated locally' 'Secrets manager explains what missing secrets are and where they come from'
check_pattern "scripts/governance/audit-deprecated-script-usage.py" 'Rank deprecated scripts by active repo references and classify keep vs archive' 'Deprecated-script auditor exists for keep-vs-archive prioritization'
check_pattern "docs/operations/deprecated-script-audit.md" '## Keep As Shim' 'Deprecated-script audit report records keep-as-shim classification'
check_pattern "docs/operations/deprecated-script-audit.md" '## Archive Or Remove' 'Deprecated-script audit report records archive-or-remove classification'
check_path_absent "scripts/governance/lint-timeouts.sh" 'Low-signal deprecated lint-timeouts shim has been removed'
check_path_absent "scripts/governance/manage-cache.sh" 'Low-signal deprecated manage-cache shim has been removed'
check_path_absent "scripts/governance/smart-config-gen.sh" 'Low-signal deprecated smart-config-gen shim has been removed'
check_path_absent "scripts/governance/smart_config_gen.sh" 'Low-signal deprecated smart_config_gen compatibility shim has been removed'
check_path_absent "scripts/testing/verify-pytorch-fix.sh" 'Low-signal deprecated verify-pytorch-fix shim has been removed'
check_path_absent "scripts/data/generate-nginx-certs.sh" 'Low-signal deprecated generate-nginx-certs shim has been removed'
check_path_absent "scripts/data/init-package-database.sh" 'Low-signal deprecated init-package-database shim has been removed'
check_path_absent "scripts/data/generate-test-telemetry.sh" 'Low-signal deprecated generate-test-telemetry shim has been removed'
check_path_absent "scripts/deploy/local-registry.sh" 'Low-signal deprecated local-registry shim has been removed'
check_path_absent "scripts/data/download-lemonade-models.sh" 'Low-signal deprecated download-lemonade-models shim has been removed'
check_path_absent "scripts/data/initialize-qdrant-collections.sh" 'Low-signal deprecated initialize-qdrant-collections shim has been removed'
check_path_absent "scripts/data/populate-knowledge-base.py" 'Low-signal deprecated populate-knowledge-base stub has been removed'
check_path_absent "scripts/data/populate-knowledge-from-web.py" 'Low-signal deprecated populate-knowledge-from-web stub has been removed'
check_path_absent "scripts/data/populate-qdrant-with-embeddings.py" 'Low-signal deprecated populate-qdrant-with-embeddings stub has been removed'
check_path_absent "scripts/data/populate-qdrant-collections.sh" 'Low-signal deprecated populate-qdrant-collections stub has been removed'
check_path_absent "scripts/data/sync-npm-ai-tools.sh" 'Low-signal deprecated sync-npm-ai-tools shim has been removed'
check_path_absent "scripts/deploy/install-lemonade-gui.sh" 'Low-signal deprecated install-lemonade-gui shim has been removed'
check_path_absent "scripts/deploy/setup-dvc-remote.sh" 'Low-signal deprecated setup-dvc-remote shim has been removed'
check_path_absent "scripts/deploy/setup-hybrid-learning.sh" 'Low-signal deprecated setup-hybrid-learning shim has been removed'
check_path_absent "scripts/governance/analyze-test-results.sh" 'Low-signal deprecated analyze-test-results shim has been removed'
check_path_absent "scripts/governance/lint-skills-podman.sh" 'Low-signal deprecated lint-skills-podman shim has been removed'
check_path_absent "scripts/automation/run-dashboard-collector-full.sh" 'Low-signal deprecated run-dashboard-collector-full shim has been removed'
check_path_absent "scripts/automation/run-dashboard-collector-lite.sh" 'Low-signal deprecated run-dashboard-collector-lite shim has been removed'
check_path_absent "scripts/deploy/fast-rebuild.sh" 'Low-signal deprecated fast-rebuild shim has been removed'
check_path_absent "scripts/governance/comprehensive-mcp-search.py" 'Low-signal deprecated comprehensive-mcp-search stub has been removed'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" '~/.local/share/nixos-quick-deploy/secrets/<host>/secrets\.sops\.yaml' 'Secrets guide documents external bundle location'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'manage-secrets\.sh bootstrap --host' 'Secrets guide documents delegated quick-deploy bootstrap flow'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'manage-secrets\.sh doctor --host' 'Secrets guide documents doctor-based readiness workflow'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'manage-secrets\.sh doctor --host nixos --format json' 'Secrets guide documents doctor JSON output for automation'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'print a readiness summary with the next commands to run|end with the same readiness summary used by `doctor`' 'Secrets guide documents post-action readiness summaries'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'core readiness for deploy-critical secrets|all-managed readiness including optional and remote-routing secrets' 'Secrets guide documents status scope distinction'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'manage-secrets\.sh status --host nixos --format json' 'Secrets guide documents status JSON output for automation'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'missing optional secrets separately from missing remote-routing secrets|missing_by_scope' 'Secrets guide documents categorized missing-secret output'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'recommended next commands for each missing scope' 'Secrets guide documents scoped next-step output'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'manage-secrets\.sh remote-guide --host nixos|remote-guide --format json' 'Secrets guide documents remote onboarding guidance'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'arcee-ai/trinity-large-preview:free|qwen/qwen3-coder:free|nvidia/nemotron-3-super-120b-a12b:free' 'Secrets guide documents concrete OpenRouter alias examples'
check_pattern "docs/development/SECRETS-MANAGEMENT-GUIDE.md" 'What "Missing" Actually Means|Provider or subscription limits are the actual hard limits' 'Secrets guide explains missing secrets and token-discipline intent clearly'
check_pattern "nix/hosts/nixos/deploy-options.nix" 'arcee-ai/trinity-large-preview:free|qwen/qwen3-coder:free|nvidia/nemotron-3-super-120b-a12b:free' 'Host deploy options document current OpenRouter alias examples'
check_pattern "docs/DASHBOARD-COLLECTORS-GUIDE.md" 'collect-ai-metrics\.sh|aq-report --since=7d --format=text' 'Dashboard collectors guide documents supported AI routing visibility commands'
check_pattern "docs/QUICK-DASHBOARD-REFERENCE.md" 'collect-ai-metrics\.sh|ai_metrics\.json|aq-report --since=7d --format=text' 'Quick dashboard reference documents supported AI metrics and routing summary paths'
check_absent_pattern "docs/QUICK-DASHBOARD-REFERENCE.md" 'Running perfectly|PID 161811|PID 162629' 'Quick dashboard reference avoids stale fixed runtime claims'
check_absent_pattern "docs/DASHBOARD-UPDATE-OPTIMIZATION.md" 'PID 161811|PID 162629|\$\{TMPDIR:-/tmp\}/run-dashboard-collector' 'Dashboard optimization guide avoids retired temp collector entrypoints and stale PIDs'
check_pattern "docs/operations/DASHBOARD-ARCHITECTURE-REFERENCE.md" 'command-center-dashboard-api\.service|manage-dashboard-collectors\.sh|collect-ai-metrics\.sh|aq-report' 'Dashboard architecture reference documents supported runtime and AI observability surfaces'
check_pattern "scripts/data/generate-api-secrets.sh" 'compatibility shim over scripts/governance/manage-secrets\.sh' 'API secret generator delegates to declarative secrets manager'
check_pattern "scripts/security/rotate-api-key.sh" 'compatibility shim over scripts/governance/manage-secrets\.sh' 'API key rotation shim delegates to declarative secrets manager'
check_pattern "scripts/data/generate-passwords.sh" 'compatibility shim over scripts/governance/manage-secrets\.sh' 'Password generator delegates to declarative secrets manager'
check_pattern "scripts/data/generate-api-key.sh" 'service_to_secret' 'Single API key generator maps services into declarative secret names'
check_pattern "scripts/security/security-scan.sh" 'compatibility shim over supported security tooling' 'Security scan shim delegates to supported audit tooling'
check_pattern "scripts/security/renew-tls-certificate.sh" 'compatibility shim for declarative ingress TLS' 'TLS renewal shim points to declarative ingress flow'
check_pattern "scripts/observability/collect-ai-metrics.sh" 'ai_metrics\.json' 'AI metrics collector refreshes the legacy dashboard cache file'
check_pattern "scripts/data/sync-flatpak-profile.sh" 'sudo -n flatpak' 'Flatpak profile sync uses passwordless sudo in non-interactive system scope'
check_pattern "scripts/data/generate-dashboard-data.sh" 'compatibility shim over collect-ai-metrics\.sh' 'Legacy dashboard data generator delegates to the supported cache refresh flow'
check_pattern "scripts/data/generate-dashboard-data-lite.sh" 'compatibility shim over generate-dashboard-data\.sh' 'Legacy lite dashboard generator delegates to the main dashboard refresh shim'
check_pattern "scripts/governance/manage-dashboard-collectors.sh" 'compatibility shim over the dashboard service and collect-ai-metrics\.sh' 'Legacy dashboard collector manager delegates to declarative service control and cache refresh'
check_pattern "scripts/governance/manage-dashboard-collectors.sh" 'show_cache_status\(|run_service_action\(|refresh_cache_if_supported\(' 'Dashboard collector manager centralizes service and cache helper logic'
check_pattern "scripts/ai/ai-metrics-auto-updater.sh" 'compatibility shim over collect-ai-metrics\.sh' 'Legacy AI metrics auto updater delegates to the supported cache refresh flow'
check_pattern "scripts/security/apply-tls-certificates.sh" 'compatibility shim over renew-tls-certificate\.sh' 'TLS apply shim delegates to the revived TLS renewal flow'
check_pattern "scripts/testing/check-ai-stack-health.sh" 'compatibility shim over ai-stack-health\.sh' 'Legacy AI stack health check delegates to declarative health tooling'
check_pattern "scripts/testing/telemetry-smoke-test.sh" 'compatibility shim over current observability smoke checks' 'Telemetry smoke shim delegates to supported observability checks'
check_pattern "scripts/testing/check-ai-stack-health-v2.py" 'Compatibility shim over the current declarative AI stack health checks|compatibility shim over check-ai-stack-health\.sh' 'Legacy AI stack health v2 shim delegates to current health tooling'
check_pattern "scripts/testing/test-ai-stack-health.sh" 'compatibility shim over check-ai-stack-health\.sh' 'Legacy AI stack health test shim delegates to current health tooling'
check_pattern "scripts/testing/check-tls-log-warnings.sh" 'compatibility shim over declarative TLS status and journal scans' 'Legacy TLS log warning check delegates to current TLS status and journald scan'
check_pattern "scripts/testing/test-container-recovery.sh" 'compatibility shim over aq-runtime-act and aq-system-act' 'Legacy container recovery test delegates to bounded runtime tooling'
check_pattern "scripts/ai/ai-model-manager.sh" 'compatibility shim over current model tooling' 'Legacy AI model manager delegates to supported model tooling'
check_pattern "scripts/ai/llama-model-cli.sh" 'compatibility shim over ai-model-manager\.sh and systemd logs' 'Legacy llama model CLI delegates to current model tooling'
check_pattern "scripts/ai/ai-stack-e2e-test.sh" 'compatibility shim over aq-qa and real-world workflow smoke tests' 'Legacy AI stack E2E test delegates to declarative validation paths'
check_pattern "scripts/ai/ai-model-setup.sh" 'compatibility shim over current declarative model tooling' 'Legacy AI model setup delegates to current model lifecycle tooling'
check_pattern "scripts/ai/ai-model-setup.sh" 'ai-model-manager\.sh status|update-llama-cpp\.sh' 'Legacy AI model setup exposes current status and update flows'
check_pattern "scripts/ai/ai-stack-feature-scenario.sh" 'compatibility shim over current feature-planning and workflow smoke tooling' 'Legacy AI feature scenario delegates to current planning and smoke tooling'
check_pattern "scripts/ai/ai-stack-feature-scenario.sh" 'aq-context-bootstrap|test-real-world-workflows\.sh' 'Legacy AI feature scenario uses bootstrap and workflow smoke tools'
check_pattern "scripts/ai/ai-stack-resume-recovery.sh" 'compatibility shim over current bounded runtime recovery tooling' 'Legacy AI resume/recovery delegates to bounded runtime tooling'
check_pattern "scripts/ai/ai-stack-resume-recovery.sh" 'aq-system-act|aq-runtime-act' 'Legacy AI resume/recovery uses current runtime recovery entrypoints'
# Phase 21.1 — OTEL exports to Tempo for distributed tracing (replaced nop exporter)
check_pattern "nix/modules/services/mcp-servers.nix" 'otlp/tempo:' 'OTEL collector exports traces to Tempo backend'
check_absent_pattern "nix/modules/services/mcp-servers.nix" 'jaeger:4317' 'No hardcoded Jaeger endpoint in declarative MCP services'
check_absent_pattern "nix/modules/services/mcp-servers.nix" 'debug:' 'No debug exporter configured in declarative OTEL collector'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/config.py" 'AI_STRICT_ENV", "true"' 'Hybrid coordinator defaults to strict env enforcement'
check_pattern "ai-stack/mcp-servers/ralph-wiggum/server.py" 'AI_STRICT_ENV", "true"' 'Ralph defaults to strict env enforcement'
check_pattern "ai-stack/mcp-servers/aidb/settings_loader.py" 'AI_STRICT_ENV", "true"' 'AIDB settings loader defaults to strict env enforcement'

# Supporting reliability improvements that were marked complete
check_pattern "lib/logging.sh" 'append_log_line\(\)' 'Safe append logging helper exists'
check_pattern "lib/validation-input.sh" 'find_existing_parent\(\)' 'Existing-parent path resolver exists'
check_pattern "lib/user-interaction.sh" 'AUTO_CONFIRM' 'Auto-confirm automation guard exists'
check_pattern "scripts/testing/validate-deploy-doc-flags.sh" 'supported quick-deploy flags' 'Deploy docs flag validator exists'

# Phase 21.2 — LLM performance metrics via llama.cpp --metrics
check_pattern "nix/modules/roles/ai-stack.nix" '"--metrics"' 'llama-server exposes Prometheus metrics endpoint'
check_pattern "nix/modules/services/monitoring.nix" 'job_name = "llama-cpp"' 'Prometheus scrapes llama-cpp inference metrics'
check_pattern "nix/modules/services/monitoring.nix" 'llamacpp_tokens_predicted_total' 'Dashboard tracks LLM token generation rate'
check_pattern "nix/modules/services/monitoring.nix" 'llamacpp_kv_cache_usage_ratio' 'Dashboard tracks KV cache utilization'
check_pattern "nix/modules/services/monitoring.nix" 'llamacpp_request_processing_seconds_bucket' 'Dashboard tracks inference latency histogram'

# Phase 21.3 — Cache intelligence with event-driven invalidation
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/metrics.py" 'EMBEDDING_CACHE_INVALIDATIONS' 'Cache invalidation counter metric defined'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/metrics.py" 'EMBEDDING_CACHE_SIZE' 'Cache size gauge metric defined'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '/cache/invalidate' 'Cache invalidation endpoint registered'
check_pattern "scripts/data/rebuild-qdrant-collections.sh" 'cache/invalidate' 'Rebuild script triggers cache invalidation'
check_pattern "nix/modules/services/monitoring.nix" 'embedding_cache_size_keys' 'Dashboard tracks embedding cache size'
check_pattern "nix/modules/services/monitoring.nix" 'embedding_cache_invalidations_total' 'Dashboard tracks cache invalidation rate'
check_pattern "scripts/automation/post-deploy-converge.sh" '/learning/process' 'Post-deploy convergence triggers learning pattern extraction'
check_pattern "scripts/automation/post-deploy-converge.sh" '/learning/export' 'Post-deploy convergence triggers fine-tuning dataset export'
check_pattern "scripts/automation/post-deploy-converge.sh" 'agent_instructions_import' 'Post-deploy convergence refreshes agent instruction imports'
check_pattern "scripts/automation/post-deploy-converge.sh" 'rag_targeted_prewarm' 'Post-deploy convergence runs bounded RAG targeted prewarm'
check_pattern "scripts/automation/post-deploy-converge.sh" 'aq_report_refresh_post_prewarm' 'Post-deploy convergence refreshes aq-report after targeted prewarm'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'prompt_coaching' 'Hints engine exposes prompt coaching guidance'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'token_discipline' 'Hints engine exposes token-discipline coaching guidance'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'outcome = "client_error"' 'HTTP audit classifies 4xx responses as client errors'
check_pattern "scripts/ai/aq-report" '"cache_prewarm": cache_prewarm' 'aq-report JSON output includes cache prewarm state'
check_pattern "scripts/ai/aq-report" "Cache prewarm: \\{cache_prewarm\\.get\\('enabled_state'" 'aq-report text output surfaces cache prewarm timer state'
check_pattern "scripts/ai/aq-report" 'Reliability context: \{_tool_reliability_context\(stats, fresh\)\}' 'aq-report reliability recommendations include failure-mix context'
check_pattern "scripts/ai/aq-report" "'OK%':>6} \{'Err':>5} \{'4xx':>5}" 'aq-report tool table exposes server and client error counts'
check_pattern "scripts/ai/aq-report" 'def recent_health_snapshot\(' 'aq-report computes a recent health snapshot for active issues'
check_pattern "scripts/ai/aq-report" '## 8\. Recent Health Snapshot|\[ 8\. Recent Health Snapshot' 'aq-report surfaces a recent health snapshot section'
check_pattern "scripts/ai/aq-report" '"recent_health": recent_health' 'aq-report JSON output includes recent health state'
check_pattern "scripts/ai/aq-report" 'Latency context: \{_tool_latency_context\(stats, fresh\)\}' 'aq-report latency recommendations include recent-window context'
check_pattern "scripts/ai/aq-report" 'Recent context: \{_autorun_block_context\(recent_semantic_autorun\)\}' 'aq-report autorun security recommendations include recent-window context'
check_pattern "scripts/ai/aq-report" 'total_injections >= 10 and recent_total >= 5' 'aq-report only promotes hint diversity recommendations when concentration is recent'
check_pattern "scripts/ai/aq-report" 'fresh is None or int\(fresh\.get\("calls", 0\) or 0\) == 0' 'aq-report suppresses historical-only slow and flaky tool recommendations when recent calls are absent'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'Objective \| Constraints \| Context \| Validation' 'Prompt coaching uses compact progressive-disclosure template by default'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" '_is_curated_stale_gap' 'Hints engine suppresses curated stale gap topics'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" '_is_synthetic_gap' 'Hints engine suppresses synthetic gap topics'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'When enough non-overused candidates exist' 'Hints engine keeps dominant hints out when enough alternatives exist'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'AI_HINTS_INCLUDE_DEBUG_METADATA' 'Hints engine gates heavy hint metadata behind explicit debug opt-in'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" '"debug_metadata"' 'Hints engine nests verbose diagnostics under debug_metadata'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'if include_debug_metadata and hint.reason' 'Hints engine only emits per-hint reasons on explicit debug opt-in'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'if include_debug_metadata and hint.tags' 'Hints engine only emits per-hint tags on explicit debug opt-in'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'if include_debug_metadata and hint.agent_hints' 'Hints engine only emits per-hint agent hints on explicit debug opt-in'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" '_compact_prompt_coaching_payload' 'Hints engine keeps default prompt coaching compact on hint surfaces'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" '_compact_missing_fields' 'Hints engine caps default missing-field coaching payloads'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'runtime_rag_low_sample' 'Hints engine surfaces low-sample RAG warmup guidance from the live report'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'runtime_memory_recall_underused' 'Hints engine surfaces underused memory-recall guidance from the live report'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'runtime_resume_memory_first' 'Hints engine surfaces continuation-specific memory-first guidance from the live report'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'runtime_resume_memory_refresh' 'Hints engine surfaces continuation-specific memory-refresh guidance when recall misses stay high'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'runtime_agent_lesson_' 'Hints engine surfaces promoted cross-agent lesson guidance from the live report'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'runtime_retrieval_breadth_optimize' 'Hints engine surfaces retrieval-breadth optimization guidance from live report'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'runtime_provider_fallback_pressure' 'Hints engine surfaces provider fallback pressure guidance from live report'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'prompt_coaching_route_selection' 'Hints engine surfaces compact route-selection guidance for local vs remote lanes'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'prompt_coaching_continue_rescue' 'Hints engine surfaces compact Continue/editor troubleshooting guidance'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'prompt_coaching_patch_review' 'Hints engine surfaces compact patch-review guidance'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" 'prompt_coaching_research_workflow' 'Hints engine surfaces compact research workflow guidance'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/hints_engine.py" '_div_repeat_cap_pct = self._parse_float_env\("AI_HINT_DIVERSITY_REPEAT_CAP_PCT", 45.0' 'Hints engine tightens hint diversity repeat cap to 45%'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'include_debug_metadata = .*debug' 'Hints HTTP endpoint exposes explicit debug metadata opt-in'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'prompt_coaching' 'Workflow plan metadata includes prompt coaching'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'result\["prompt_coaching"\]|metadata\["prompt_coaching"\]' 'Query responses expose prompt coaching guidance'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_compact_prompt_coaching_metadata' 'Hybrid HTTP surfaces compact coaching metadata instead of duplicating full payloads'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_query_prompt_coaching_response' 'Query endpoint defaults top-level prompt coaching to compact progressive-disclosure output'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"missing_count": len\(missing_fields\)' 'Query and workflow coaching metadata cap missing-field summaries'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_compact_tooling_layer_response' 'Query endpoint defaults tooling layer to compact progressive-disclosure output'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"planned_more": max\(0, len\(planned_tools\) - 3\)' 'Query tooling layer caps planned tool lists by default'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"executed_more": max\(0, len\(executed_tools\) - 3\)' 'Query tooling layer caps executed tool lists by default'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_compact_tool_security' 'Workflow and query metadata compact raw tool-security state by default'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_compact_workflow_tool_catalog' 'Workflow plans keep default tool catalog compact by endpoint-only summaries'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_phase_tool_names' 'Workflow consumers accept compact phase tool-name lists'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"tool_catalog": \(|_compact_workflow_tool_catalog' 'Workflow plans keep detailed tool metadata in one catalog instead of repeating it per phase'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'request.rel_url.query.get\("debug", "0"\)' 'Workflow plan exposes explicit debug metadata opt-in'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'memory_recall_priority' 'Workflow plan metadata exposes continuation-memory steering state'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_is_continuation_query\(' 'Hybrid query handling centralizes continuation-query detection'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'has_previous_ref and has_resume_target' 'Hybrid continuation-query detection catches prior deploy/patch context, not just exact phrases'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'semantic_tooling_memory_recall_skipped|request_context\["memory_recall"\]' 'Hybrid query autorun executes memory recall for continuation-style requests'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'memory_recall_attempted|memory_recall_miss' 'Hybrid query responses track continuation memory recall attempts and misses'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'result\["memory_recall"\]' 'Hybrid query responses surface recalled memory summaries when used'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'def _audit_internal_tool_execution\(' 'Hybrid query autorun emits dedicated tool-audit rows for internal tool usage'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'risk_tier="low"' 'Hybrid internal tool autorun audit writes include an explicit risk tier'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" '"x-ai-profile": "remote-reasoning"' 'Hybrid route synthesis uses a remote reasoning profile when escalating to switchboard'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" 'remote_4xx_local_fallback' 'Hybrid route synthesis falls back locally when switchboard rejects the remote payload with any 4xx'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"recall_agent_memory"' 'Hybrid query autorun audits internal memory recall as its own tool event'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_audit_internal_tool_execution\(' 'Hybrid query autorun audits internal hints execution as its own tool event'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'tooling_layer\["executed"\]\.append\("discovery"\)' 'Hybrid query autorun audits internal discovery execution as its own tool event'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'compact-first|retrieve-before-restating|cheap-probe-then-cache' 'Workflow token policy teaches bounded cloud/provider token usage'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'include_debug_metadata and h\.get\("reason"\)' 'Hints HTTP continue context only emits per-hint reasons on explicit debug opt-in'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'max_hints = int\(body.get\("max_hints", 4\)\)' 'Hints HTTP endpoint defaults to compact hint fan-out'
check_pattern "scripts/ai/aq-hints" 'Token plan:' 'aq-hints renders token-discipline coaching text'
check_pattern "scripts/ai/aq-hints" 'Suggested prompt:' 'aq-hints renders compact prompt coaching text'
check_pattern "scripts/ai/aq-hints" 'required_any_of' 'aq-hints keeps a compact feedback contract'
check_pattern "scripts/ai/aq-hints" '\-\-debug-meta' 'aq-hints exposes explicit debug metadata opt-in'
check_pattern "scripts/ai/aq-hints" 'default=4' 'aq-hints defaults to compact hint fan-out'
check_pattern "scripts/ai/aq-hints" 'debug_meta and reason' 'aq-hints text and continue renderers only emit per-hint reasons on explicit debug opt-in'
check_pattern "scripts/ai/aq-hints" 'if agent != "human"' 'aq-hints text output suppresses redundant agent labels on the default human path'
check_pattern "scripts/ai/aq-hints" '\[:100\]' 'aq-hints text output uses shorter compact snippet previews'
check_pattern "scripts/ai/aq-hints" 'extra_missing > 0|compact_missing \+=' 'aq-hints text output compacts long missing-field lists'
check_pattern "scripts/ai/aq-rag-prewarm" 'from-report PATH' 'aq-rag-prewarm supports report-driven bounded prewarm selection'
check_pattern "scripts/ai/aq-rag-prewarm" 'route_search_synthesis|memory_recall_contextualise|gap_detection_score' 'aq-rag-prewarm maps prewarm prompt ids into bounded seed queries'
check_pattern "scripts/ai/aq-rag-prewarm" 'prewarm_prompt_id' 'aq-rag-prewarm tags seeded queries with the prompt id source'
check_pattern "scripts/ai/aq-rag-prewarm" 'REPLAY_COUNT=2' 'aq-rag-prewarm replays candidate prompts enough to create cache reuse by default'
check_pattern "scripts/ai/aq-report" '_cache_recommendation_actionable' 'aq-report gates cache recommendations on meaningful sample size'
check_pattern "scripts/ai/aq-report" 'nixos-rag-test-probe-unique-sentinel' 'aq-report suppresses synthetic rag probe gap noise'
check_pattern "scripts/ai/aq-report" 'partially written telemetry does not understate OK%' 'aq-report ignores ambiguous audit rows without final outcomes'
check_pattern "scripts/ai/aq-report" 'Ignored client-side 4xx rows' 'aq-report exposes client-side misuse monitoring notes'
check_pattern "scripts/ai/aq-report" 'Monitoring note: hint selection is concentrated' 'aq-report exposes hint-diversity monitoring notes'
check_pattern "scripts/ai/aq-report" '_hint_diversity_recent_context\(recent_hint_diversity_stats\)' 'aq-report exposes recent context for hint-diversity metrics'
check_pattern "scripts/ai/aq-report" '"recent_hint_diversity": recent_hint_diversity_stats or \{"available": False\}' 'aq-report JSON output includes recent hint-diversity state'
check_pattern "scripts/ai/aq-report" 'def historical_hint_watchlist\(' 'aq-report computes a historical hint watchlist for non-recent concentration'
check_pattern "scripts/ai/aq-report" 'Historical Hint Watchlist' 'aq-report exposes a historical hint watchlist section in text and markdown outputs'
check_pattern "scripts/ai/aq-report" '"historical_hint_watchlist": historical_hint_watch or \{"available": False, "has_items": False\}' 'aq-report JSON output includes historical hint watchlist state'
check_pattern "scripts/ai/aq-report" 'def rag_posture\(' 'aq-report computes a compact RAG posture summary'
check_pattern "scripts/ai/aq-report" 'RAG Posture' 'aq-report exposes a RAG posture section in text and markdown outputs'
check_pattern "scripts/ai/aq-report" '"rag_posture": rag_posture_summary' 'aq-report JSON output includes rag posture state'
check_pattern "scripts/ai/aq-report" '_format_retrieval_mix' 'aq-report formats compact retrieval-mix summaries'
check_pattern "scripts/ai/aq-report" '_rag_prewarm_candidates' 'aq-report derives bounded prewarm candidates from active retrieval patterns'
check_pattern "scripts/ai/aq-report" '"retrieval_mix": \{' 'aq-report JSON output includes retrieval mix details in rag posture state'
check_pattern "scripts/ai/aq-report" 'Status: low_sample|cache sample still warming' 'aq-report distinguishes low-sample retrieval posture from healthy posture'
check_pattern "scripts/ai/aq-report" '"memory_recall_share_pct":' 'aq-report JSON output includes memory recall utilization share'
check_pattern "scripts/ai/aq-report" '"memory_recall_miss_pct":' 'aq-report JSON output includes recent memory recall miss quality'
check_pattern "scripts/ai/aq-report" 'Memory recall miss rate' 'aq-report surfaces memory recall miss rate in human-readable outputs'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'fallback_reason|fallback_status_code|fallback_original_backend' 'HTTP query audit propagates recovered fallback metadata into tool-audit rows'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" 'def _select_route_collections\(' 'Route handler centralizes bounded retrieval collection selection'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" 'retrieval_profile|collection_count' 'Route handler records retrieval profile metadata for route_search'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'retrieval_profile|retrieval_collection_count' 'HTTP query audit propagates retrieval-breadth metadata into tool-audit rows'
check_pattern "scripts/ai/aq-report" 'def route_provider_fallback_health\(' 'aq-report computes recovered provider fallback health from route_search audit rows'
check_pattern "scripts/ai/aq-report" 'def route_retrieval_breadth\(' 'aq-report computes recent route_search retrieval breadth from audit rows'
check_pattern "scripts/ai/aq-report" '"route_retrieval_breadth": retrieval_breadth' 'aq-report JSON output includes retrieval-breadth state'
check_pattern "scripts/ai/aq-report" 'def route_retrieval_breadth_windows\(' 'aq-report computes multi-window route_search retrieval breadth'
check_pattern "scripts/ai/aq-report" '"route_retrieval_breadth_windows": retrieval_breadth_windows' 'aq-report JSON output includes multi-window retrieval-breadth state'
check_pattern "scripts/ai/aq-report" 'Batch D.*Cache and Retrieval Effectiveness' 'aq-report includes Batch D cache and retrieval effectiveness improvements'
check_pattern "scripts/ai/aq-report" 'bounded prewarm heuristics for cheap recurring local queries' 'aq-report implements bounded prewarm heuristics'
check_pattern "scripts/ai/aq-report" 'Prefer local-first retrieval for recurring queries; remote spend is unnecessary' 'aq-report recommends retrieval-first when remote spend is unnecessary'
check_pattern "scripts/ai/aq-report" 'Retrieval Breadth' 'aq-report surfaces retrieval-breadth state in human-readable outputs'
check_pattern "scripts/testing/test-retrieval-breadth-history.py" 'route_retrieval_breadth_windows' 'Retrieval-breadth history test covers multi-window breadth reporting'
check_pattern "scripts/ai/aq-qa" '_aq_report_snapshot' 'aq-qa can reuse aq-report JSON for retrieval acceptance checks'
check_pattern "scripts/ai/aq-qa" 'aq-report exposes retrieval acceptance metrics' 'aq-qa surfaces retrieval acceptance metrics from aq-report'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/ai_coordinator.py" 'tool-call-only output is insufficient' 'Remote tool-calling contract forbids tool-call-only outputs'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/ai_coordinator.py" 'build_tool_call_finalization_messages' 'ai-coordinator exposes a tool-call finalization prompt builder'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/ai_coordinator.py" 'build_reasoning_finalization_messages' 'ai-coordinator exposes a reasoning finalization prompt builder'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/ai_coordinator.py" '_profile_completion_rules' 'ai-coordinator exposes profile-specific compact completion rules for delegated lanes'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/ai_coordinator.py" 'Completion rules:' 'delegation envelopes include explicit compact completion rules'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/ai_coordinator.py" 'Do not spawn, invoke, or route additional sub-agents' 'Delegated sub-agent contracts forbid nested fan-out'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'post_tool_finalization' 'Delegate endpoint supports a bounded post-tool finalization pass'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'post_reasoning_finalization' 'Delegate endpoint supports a bounded post-reasoning finalization pass'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '_coerce_orchestration_context' 'Workflow runs coerce explicit orchestrator vs sub-agent context'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"delegation_finalization_applied"' 'Delegate endpoint records finalization metadata in audit state'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"active_lesson_refs"' 'Delegate endpoint surfaces active lesson references on delegated responses'
check_pattern "scripts/ai/aq-report" '"provider_fallback_recovery": provider_fallbacks' 'aq-report JSON output includes recovered provider fallback state'
check_pattern "scripts/ai/aq-report" 'def remote_profile_utilization\(' 'aq-report computes delegated remote profile utilization'
check_pattern "scripts/ai/aq-report" '"remote_profile_utilization": remote_profile_summary' 'aq-report JSON output includes remote profile utilization state'
check_pattern "scripts/ai/aq-report" 'def remote_profile_utilization_windows\(' 'aq-report computes multi-window delegated remote profile utilization'
check_pattern "scripts/ai/aq-report" '"remote_profile_utilization_windows": remote_profile_windows' 'aq-report JSON output includes multi-window remote profile utilization state'
check_pattern "scripts/ai/aq-report" 'def route_search_latency_decomposition\(' 'aq-report computes route_search latency decomposition'
check_pattern "scripts/ai/aq-report" '"route_search_latency_decomposition": route_latency_decomposition' 'aq-report JSON output includes route_search latency decomposition state'
check_pattern "scripts/testing/test-remote-profile-utilization.py" 'remote_profile_utilization_windows|route_search_latency_decomposition' 'Remote profile utilization test covers trend windows and route latency decomposition'
check_pattern "nixos-quick-deploy.sh" 'Remote profile use \(' 'quick deploy summary surfaces remote profile utilization'
check_pattern "nixos-quick-deploy.sh" 'Remote profile trend' 'quick deploy summary surfaces remote profile trend windows'
check_pattern "nixos-quick-deploy.sh" 'Route latency \(' 'quick deploy summary surfaces route latency decomposition summary'
check_pattern "scripts/ai/aq-report" 'Provider Fallback Recovery' 'aq-report surfaces recovered provider fallback state in human-readable outputs'
check_pattern "scripts/ai/aq-report" 'Treat this as provider-budget or remote-routing pressure, not a local backend outage' 'aq-report recommendations distinguish recovered provider fallback pressure from local backend outages'
check_pattern "scripts/ai/aq-report" '"prewarm_candidates":' 'aq-report JSON output includes bounded prewarm candidates'
check_pattern "scripts/ai/aq-report" 'Candidate prewarm prompts' 'aq-report surfaces candidate prewarm prompts in text and markdown outputs'
check_pattern "scripts/ai/aq-report" '_hint_adoption_recent_context\(recent_hint_adoption\)' 'aq-report exposes recent context for hint-adoption metrics'
check_pattern "scripts/ai/aq-report" '"recent_hint_adoption": recent_hint_adoption or \{"available": False\}' 'aq-report JSON output includes recent hint-adoption state'
check_pattern "scripts/ai/aq-report" '_routing_recent_context\(recent_route\)' 'aq-report exposes recent context for routing metrics'
check_pattern "scripts/ai/aq-report" '"recent_routing": recent_route' 'aq-report JSON output includes recent routing state'
check_pattern "scripts/ai/aq-report" 'def routing_split_windows\(' 'aq-report computes multi-window routing history'
check_pattern "scripts/ai/aq-report" '"routing_windows": routing_windows' 'aq-report JSON output includes multi-window routing history'
check_pattern "scripts/testing/test-routing-history.py" 'routing_split_windows' 'Routing history test covers multi-window routing reporting'
check_pattern "scripts/ai/aq-report" 'def continue_editor_windows\(' 'aq-report computes multi-window Continue/editor history'
check_pattern "scripts/ai/aq-report" '"continue_editor_windows": continue_editor_windows' 'aq-report JSON output includes multi-window Continue/editor history'
check_pattern "scripts/testing/test-continue-editor-history.py" 'continue_editor_windows|append_continue_editor_snapshot' 'Continue/editor history test covers persisted snapshot windows'
check_pattern "scripts/ai/aq-report" 'def agent_lesson_candidates\(' 'aq-report computes compact cross-agent lesson promotion candidates'
check_pattern "scripts/ai/aq-report" '"agent_lessons": agent_lessons or \{"available": False, "candidates": \[\]\}' 'aq-report JSON output includes agent lesson candidates'
check_pattern "scripts/ai/aq-report" 'Agent Lesson Promotion Candidates' 'aq-report surfaces compact agent lesson candidates in text and markdown outputs'
check_pattern "scripts/ai/aq-report" 'def historical_watchlist\(tool_stats: Dict\[str, dict\], recent_tool_stats: Dict\[str, dict\]\)' 'aq-report computes a historical watchlist for non-recent issues'
check_pattern "scripts/ai/aq-report" '\[ 8[c-d]?\. Historical Watchlist \(\{historical_watch\.get\('"'"'window'"'"', '"'"'7d'"'"'\)\}\) \]' 'aq-report text output exposes a historical watchlist section'
check_pattern "scripts/ai/aq-report" '"historical_watchlist": historical_watch' 'aq-report JSON output includes historical watchlist state'
check_pattern "scripts/ai/aq-report" '"tool_call_basis": \{' 'aq-report JSON output documents tool call counting semantics'
check_pattern "scripts/ai/aq-report" 'outcome == "client_error"' 'aq-report counts explicit client_error audit outcomes separately from backend failures'
check_pattern "scripts/ai/aq-report" '"actionable_calls": total' 'aq-report exposes actionable backend call counts separately from total observed attempts'
check_pattern "scripts/ai/aq-report" 'invalid client requests excluded' 'aq-report reliability context distinguishes invalid client input from backend failures'
check_pattern "scripts/ai/aq-report" '_backend_reliability_summary' 'aq-report formats backend reliability with separate invalid-input context'
check_pattern "scripts/ai/aq-report" 'backend success rate is low .* valid calls' 'aq-report reliability recommendations describe backend-valid call counts explicitly'
check_pattern "scripts/ai/aq-report" 'def _cache_sample_context\(cache: Optional\[Dict\[str, Any\]\]\)' 'aq-report computes cache sample context for no-sample and low-sample windows'
check_pattern "scripts/ai/aq-report" 'return total >= 100' 'aq-report only makes cache recommendations after a meaningful sample size'
check_pattern "scripts/ai/aq-report" 'if total < 100:' 'aq-report keeps cache posture in low-sample warmup until a meaningful sample is reached'
check_pattern "scripts/ai/aq-report" 'Context: \{cache_context\}' 'aq-report text output exposes cache sample context'
check_pattern "nixos-quick-deploy.sh" 'recent_hint_diversity.window // "1h"' 'quick deploy summary reads recent hint-diversity state from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'Top hint \(historical\)' 'quick deploy summary labels historical top hints when there is no recent hint activity'
check_pattern "nixos-quick-deploy.sh" 'cache_summary="\$\{cache_hit\}% \(\$\{cache_hits\}/\$\{cache_total\}\)"' 'quick deploy summary includes semantic cache sample counts'
check_pattern "nixos-quick-deploy.sh" 'low sample' 'quick deploy summary labels low-sample semantic cache metrics'
check_pattern "nixos-quick-deploy.sh" 'cache_summary="n/a \(0/0; no samples\)"' 'quick deploy summary labels no-sample semantic cache metrics'
check_pattern "nixos-quick-deploy.sh" 'hint_adoption_label="\$\{hint_rate\}% \(historical\)"' 'quick deploy summary labels historical hint adoption when there is no recent hint activity'
check_pattern "nixos-quick-deploy.sh" 'hint_diversity_label="\$\{hint_diversity_status\} \(historical\)"' 'quick deploy summary labels historical hint diversity when there is no recent hint activity'
check_pattern "nixos-quick-deploy.sh" 'historical only; no recent route_search traffic in' 'quick deploy summary labels historical routing when there is no recent route_search traffic'
check_pattern "nixos-quick-deploy.sh" 'Routing trend' 'quick deploy summary surfaces routing trend windows'
check_pattern "nixos-quick-deploy.sh" 'generated_at // empty' 'quick deploy summary reads report generation time from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'Report freshness' 'quick deploy summary surfaces report freshness context'
check_pattern "nixos-quick-deploy.sh" 'stale \(\{age_m\}m old\)|current \(\{age_m\}m old\)' 'quick deploy summary computes freshness age labels'
check_pattern "nixos-quick-deploy.sh" 'cache_prewarm.enabled_state // "unknown"' 'quick deploy summary reads cache prewarm state from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'recent_health.healthy // false' 'quick deploy summary reads recent health status from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'Recent health' 'quick deploy summary surfaces recent health state'
check_pattern "nixos-quick-deploy.sh" 'Continue trend' 'quick deploy summary surfaces Continue/editor trend windows'
check_pattern "nixos-quick-deploy.sh" 'historical_watchlist\.has_items' 'quick deploy summary reads historical watchlist state from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'Historical watchlist \(\$\{historical_watch_window\}\)' 'quick deploy summary surfaces background watchlist items'
check_pattern "nixos-quick-deploy.sh" 'historical_hint_watchlist\.has_items' 'quick deploy summary reads historical hint watchlist state from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'Hint watchlist \(\$\{historical_hint_watch_window\}\)' 'quick deploy summary surfaces historical hint concentration debt'
check_pattern "nixos-quick-deploy.sh" 'rag_posture.status // "unknown"' 'quick deploy summary reads rag posture state from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'RAG posture' 'quick deploy summary surfaces RAG posture'
check_pattern "nixos-quick-deploy.sh" 'rag_posture.retrieval_mix.recent.route_search // 0' 'quick deploy summary reads recent retrieval mix from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'RAG mix \(1h\)' 'quick deploy summary surfaces recent retrieval mix'
check_pattern "nixos-quick-deploy.sh" 'rag_posture.memory_recall_share_pct // "n/a"' 'quick deploy summary reads memory recall utilization from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'provider_fallback_recovery.recovered_count // 0' 'quick deploy summary reads recovered provider fallback counts from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'route_retrieval_breadth.avg_collection_count // "n/a"' 'quick deploy summary reads retrieval-breadth averages from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'Retrieval breadth \(1h\)' 'quick deploy summary surfaces retrieval-breadth context'
check_pattern "nixos-quick-deploy.sh" 'Retrieval breadth trend' 'quick deploy summary surfaces retrieval-breadth trend windows'
check_pattern "nixos-quick-deploy.sh" 'Provider fallback \(\$\{provider_fallback_window\}\)' 'quick deploy summary surfaces provider fallback recovery context'
check_pattern "nixos-quick-deploy.sh" 'rag_posture.prewarm_candidates\[0\].id // empty' 'quick deploy summary reads a bounded prewarm candidate from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'agent_lessons.registry.active_lessons\[0\]' 'quick deploy summary reads active agent lessons from aq-report JSON'
check_pattern "nixos-quick-deploy.sh" 'Memory recall share' 'quick deploy summary surfaces memory recall utilization'
check_pattern "nixos-quick-deploy.sh" 'Prewarm candidate' 'quick deploy summary surfaces bounded prewarm guidance'
check_pattern "nixos-quick-deploy.sh" 'Agent lesson' 'quick deploy summary surfaces the top promoted agent lesson'
check_pattern "nixos-quick-deploy.sh" 'historical_watch_label=.*backend OK .*valid calls' 'quick deploy summary distinguishes backend reliability in historical watchlist output'
check_pattern "nixos-quick-deploy.sh" 'historical_watch_label="\$\{historical_watch_label\}; \+\$\{historical_watch_flaky_invalid\} invalid"' 'quick deploy summary surfaces invalid-input counts separately in historical watchlist output'
check_pattern "nixos-quick-deploy.sh" 'historical_watch_label=.*backend OK .*% .*valid calls' 'quick deploy summary avoids duplicated percent markers in backend watchlist output'
check_pattern "nixos-quick-deploy.sh" 'Top recommended next actions: none' 'quick deploy summary collapses no-action recommendation state into a neutral status line'
check_pattern "scripts/ai/aq-report" '\| Tool \| Valid \| P50 ms \| P95 ms \| Success % \| Err \| 4xx \|' 'aq-report markdown tool table labels backend-only calls as valid'
check_pattern "scripts/ai/aq-report" "\{'Tool':<30\} \{'Valid':>6\}" 'aq-report text tool table labels backend-only calls as valid'
check_pattern "scripts/ai/aq-report" 'Valid counts backend-attributable calls only; invalid client requests are shown in `?4xx`?' 'aq-report explains valid-call semantics inline in text and markdown outputs'
check_pattern "scripts/ai/aq-report" '_is_curated_stale_gap' 'aq-report suppresses curated stale residual gaps'
check_pattern "scripts/ai/aq-report" 'r_calls >= 5 and r_blocked == 0' 'aq-report suppresses stale tool-security warnings when recent traffic is clean'
check_pattern "scripts/ai/aq-report" '400 <= http_status < 500' 'aq-report ignores client-side 4xx misuse in tool reliability scoring'
check_pattern "scripts/ai/aq-report" 'fresh\.get\("calls", 0\) or 0\) >= 1 and float\(fresh\.get\("p95_ms"' 'aq-report suppresses stale latency warnings when recent p95 is healthy'
check_pattern "scripts/ai/aq-report" 'fresh\.get\("calls", 0\) or 0\) >= 1 and float\(fresh\.get\("success_pct"' 'aq-report suppresses stale reliability warnings when recent success is healthy'
check_pattern "config/agent-context-cards.json" 'OpenRouter-routed models|provider-side prompt caching' 'Token-discipline context card includes remote/provider budget rules'
check_pattern "scripts/data/curate-residual-gaps.sh" 'Progressive disclosure token efficiency defaults quick reference' 'Residual gap curation imports progressive-disclosure token-efficiency guidance'
check_pattern "scripts/data/curate-residual-gaps.sh" 'Workflow run start intent contract quick reference' 'Residual gap curation imports workflow intent-contract guidance'
check_pattern "scripts/data/curate-residual-gaps.sh" 'Qdrant and hybrid routing configuration quick reference' 'Residual gap curation imports qdrant and hybrid-routing guidance'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" 'Hint diversity and anti-dominance' 'Harness next-improvements roadmap captures hint diversity work'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" 'AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03\.md' 'Harness next-improvements roadmap links to the detailed implementation roadmap'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" 'Monitoring and report integrity' 'Harness next-improvements roadmap captures monitoring/reporting work'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" '## Batch Execution Model' 'Harness next-improvements roadmap defines batch execution model'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" '### Batch A — Monitoring Summary Integrity' 'Harness next-improvements roadmap queues monitoring summary batch'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" '### Batch F — Historical Debt Visibility' 'Harness next-improvements roadmap tracks historical debt visibility batch'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" '### Batch H — Agent Lesson Promotion' 'Harness next-improvements roadmap tracks agent lesson promotion batch'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" '### Batch G — RAG and Retrieval Utilization' 'Harness next-improvements roadmap tracks RAG and retrieval utilization batch'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" '### Batch I — Targeted RAG Prewarm and Continuation Memory Steering' 'Harness next-improvements roadmap tracks targeted prewarm and continuation memory steering batch'
check_pattern "docs/roadmap/AI-HARNESS-NEXT-IMPROVEMENTS-2026-03.md" 'Surface memory-recall utilization so embedded memory is developed with retrieval' 'Harness next-improvements roadmap ties embedded memory to retrieval effectiveness'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'None of the tracks below are optional' 'Detailed implementation roadmap marks major AI harness tracks as required'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'Track D — OpenRouter Agent API and Remote Delegation Utilization' 'Detailed implementation roadmap covers OpenRouter agent API integration'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'Track E — Agent Lesson Promotion and EvoSkill-Inspired Skill Evolution' 'Detailed implementation roadmap covers EvoSkill-inspired lesson promotion'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'Track F — BitNet Feasibility and Optional Runtime Integration' 'Detailed implementation roadmap covers BitNet integration planning'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'Track A — Continue and Editor-Agent Runtime Stabilization' 'Detailed implementation roadmap treats Continue/editor support as a first-class track'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'Required Foundation — Declarative Agent CLI and IDE Surface' 'Detailed implementation roadmap treats declarative agent tooling as a required foundation'
check_pattern "nix/modules/services/mcp-servers.nix" 'WORKFLOW_BLUEPRINTS_FILE=\$\{mcp\.repoPath\}/config/workflow-blueprints\.json' 'Hybrid coordinator reads workflow blueprints from the repo-backed path'
check_pattern "scripts/testing/smoke-workflow-review-contract.sh" '/workflow/run/start' 'Workflow review-contract smoke covers workflow run start'
check_pattern "scripts/testing/smoke-workflow-review-contract.sh" '/review/acceptance' 'Workflow review-contract smoke covers reviewer acceptance persistence'
check_pattern "scripts/testing/smoke-workflow-review-contract.sh" '/workflow/run/\$\{session_id\}' 'Workflow review-contract smoke covers persisted workflow run retrieval'
check_pattern "scripts/testing/smoke-workflow-review-contract.sh" 'review_type|artifact_kind|reviewed_agent|reviewed_profile|task_class' 'Workflow review-contract smoke covers classified patch-review persistence'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" '## Tracking Conventions' 'Detailed implementation roadmap defines tracking conventions'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'Track Status: `|Current Slice: `|Next Validation:' 'Detailed implementation roadmap includes live tracking fields'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" '## Execution Ledger' 'Detailed implementation roadmap records an execution ledger section'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'agent-review corrective pass' 'Detailed implementation roadmap records the latest corrective pass in the execution ledger'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" '## Active Blockers' 'Detailed implementation roadmap tracks active blockers'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" '\| .* \| (planned|in_progress|validated_local|validated_live|blocked) \| .* \| .* \|' 'Detailed implementation roadmap records active blocker rows with status and next action'
check_pattern "docs/roadmap/AI-HARNESS-IMPLEMENTATION-ROADMAP-2026-03.md" 'Continue/local web research lane|Shared skill ingestion and registry|Flagship agent CLI coverage' 'Detailed implementation roadmap records current concrete blocker evidence'
check_pattern "docs/operations/AI-AGENT-SURFACE-MATRIX.md" 'Continue CLI \(`cn`\)|Codex CLI \(`codex`\)|Qwen CLI \(`qwen`\)|Gemini CLI \(`gemini`\)|OpenRouter remote profiles' 'Agent surface matrix tracks flagship agent CLI and remote-provider surfaces'
check_pattern "docs/operations/AI-AGENT-SURFACE-MATRIX.md" 'declarative package|external binary on PATH|Declarative Nix config \+ SOPS secret' 'Agent surface matrix distinguishes declarative, external, and remote-config delivery modes'
check_pattern "scripts/ai/aq-gaps" 'No operator-actionable gaps after synthetic/curated filtering' 'aq-gaps suppresses synthetic and curated gap noise'
check_pattern "scripts/data/sync-knowledge-sources" 'SCRIPT_DIR/../\.\.' 'Knowledge source sync resolves repository root correctly'
check_pattern "scripts/governance/tier0-validation-gate.sh" 'collect_changed_files\(\)' 'Tier 0 validation gate centralizes changed-file detection'
check_pattern "scripts/governance/tier0-validation-gate.sh" 'origin/main\.\.\.HEAD' 'Tier 0 pre-deploy validation includes committed batch changes since origin/main'
check_pattern "nix/pkgs/continue-cli.nix" 'stdenvNoCC\.mkDerivation' 'Continue CLI is packaged as a declarative wrapped runtime derivation'
check_pattern "nix/pkgs/continue-cli.nix" 'makeWrapper .*node.*/bin/node' 'Continue CLI wrapper executes the bundled CLI with Node'
check_absent_pattern "nix/pkgs/continue-cli.nix" 'npmDepsHash = null' 'Continue CLI derivation no longer uses a broken null npmDepsHash'
check_pattern "nix/home/base.nix" '"__configVersion": "21\.0"' 'Continue config version tracks the current generated schema'
check_pattern "nix/home/base.nix" '"contextLength": 16384' 'Continue config matches the local llama.cpp context window instead of a stale 4k cap'
check_pattern "nix/home/base.nix" '"name": "aq-hints"' 'Continue config restores the aq-hints HTTP context provider'
check_pattern "scripts/ai/aq-qa" 'contextLength\"\) or 0\) >= 12000' 'aq-qa enforces a Continue context-window floor for agent mode'
check_pattern "scripts/ai/aq-qa" '0\.5\.5' 'aq-qa includes a continue-local oversized-input trimming check'
check_pattern "scripts/ai/aq-qa" '0\.5\.6' 'aq-qa includes a Continue editor-path smoke check'
check_pattern "scripts/ai/aq-report" 'timeout=35' 'aq-report allows the heavier Continue/editor QA batch to complete'
check_pattern "scripts/testing/smoke-continue-editor-flow.sh" '/hints' 'Continue editor smoke exercises Continue hints endpoint'
check_pattern "scripts/testing/smoke-continue-editor-flow.sh" '/workflow/plan' 'Continue editor smoke exercises workflow planning'
check_pattern "scripts/testing/smoke-continue-editor-flow.sh" '/query' 'Continue editor smoke exercises query path'
check_pattern "scripts/testing/smoke-continue-editor-flow.sh" '/feedback' 'Continue editor smoke exercises feedback path'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/mcp_handlers.py" 'name="run_qa_check"' 'Hybrid coordinator exposes MCP QA tool'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/mcp_handlers.py" '_resolve_bash_binary' 'Hybrid QA tool resolves an explicit bash binary for systemd-safe execution'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/mcp_handlers.py" '_resolve_python3_binary|_build_qa_exec_env' 'Hybrid QA tool resolves python3 and PATH for systemd-safe execution'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/mcp_handlers.py" "_write_audit\(name, 'client_error'" 'Hybrid MCP handlers audit ValueError paths as client_error'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/tooling_manifest.py" 'run_qa_check' 'Tooling manifest surfaces QA tool for validation tasks'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'qa_check", "harness_eval", "health", "learning_stats"' 'Workflow plan validate phase surfaces QA tool'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '/qa/check' 'Hybrid coordinator exposes HTTP QA endpoint'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" 'def _runtime_context_blocks\(' 'Route handler composes workflow hints, discovery, and memory into bounded runtime context blocks'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" 'Relevant prior memory:' 'Route handler injects recalled memory into synthesis context'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" 'Workflow hints:' 'Route handler injects workflow hints into synthesis context'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.py" 'def query\(' 'Python harness SDK exposes coached query client'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.ts" 'query\(' 'TypeScript harness SDK exposes coached query client'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.js" 'query\(' 'JavaScript harness SDK exposes coached query client'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.d.ts" 'query\(query: string, opts\?: QueryRequestOptions\)' 'TypeScript declaration exposes coached query client'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.py" 'def qa_check' 'Python harness SDK exposes QA check client'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.ts" 'qaCheck\(' 'TypeScript harness SDK exposes QA check client'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/harness_sdk.d.ts" 'qaCheck\(' 'TypeScript declaration exposes QA check client'
check_pattern "nix/modules/core/options.nix" 'localSystemPrompt = \{' 'Declarative local system prompt options exist'
check_pattern "nix/modules/services/mcp-servers.nix" 'AI_LOCAL_SYSTEM_PROMPT=' 'Hybrid service injects local system prompt flag'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/config.py" 'build_local_system_prompt' 'Hybrid config builds local system prompt from declarative rules'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/config.py" 'Respond concisely first and expand only when requested' 'Local system prompt encodes concise-first progressive disclosure'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/route_handler.py" '"role": "system"' 'Local route synthesis prepends a system prompt'
check_pattern "scripts/ai/aq-hints" 'parent\.parent\.parent' 'aq-hints resolves repository root correctly for local engine imports'
check_pattern "scripts/data/import-agent-instructions.sh" 'dirname "\$0"\)/\.\./\.\.' 'Agent instruction import resolves repository root correctly'

# Phase 21.5 — Post-deploy auto Phase 0 validation
check_pattern "nixos-quick-deploy.sh" 'qa_script=.*aq-qa|"\$\{qa_script\}" 0 --json' 'Deploy completion runs aq-qa phase 0 summary'
check_pattern "nixos-quick-deploy.sh" '\(\.passed // \.pass // 0\)|\(\.failed // \.fail // 0\)|\(\.skipped // \.skip // 0\)' 'Deploy completion accepts both legacy and current aq-qa summary field names'
check_pattern "nixos-quick-deploy.sh" 'manage-secrets\.sh|manage_secrets_cmd.*bootstrap --host' 'Quick deploy delegates AI secrets bootstrap to the shared secrets manager'
check_pattern "nixos-quick-deploy.sh" 'should_manage_repo_backed_ai_services\(\)' 'Quick deploy centralizes repo-backed AI runtime gating'
check_pattern "nixos-quick-deploy.sh" 'systemd_unit_declared\(\)' 'Quick deploy centralizes systemd unit declaration checks'
check_pattern "nixos-quick-deploy.sh" 'systemd_unit_enabled_or_running\(\)' 'Quick deploy centralizes systemd unit state checks'
check_pattern "nixos-quick-deploy.sh" 'should_manage_repo_backed_ai_services "service restart"' 'Quick deploy reuses repo-backed AI gating for service restarts'
check_pattern "nixos-quick-deploy.sh" 'should_manage_repo_backed_ai_services "capability verification"' 'Quick deploy reuses repo-backed AI gating for capability verification'
check_pattern "nixos-quick-deploy.sh" 'ai_service_health_targets\(\)' 'Quick deploy centralizes AI service readiness targets'
check_pattern "nixos-quick-deploy.sh" 'done < <\(ai_service_health_targets\)' 'Quick deploy iterates AI readiness checks from the shared target table'
check_pattern "nixos-quick-deploy.sh" 'run_nonfatal_postflight_check\(' 'Quick deploy centralizes non-fatal post-flight command handling'
check_pattern "nixos-quick-deploy.sh" 'run_inline_postflight_script_if_present\(' 'Quick deploy centralizes optional inline post-flight script execution'
check_pattern "nixos-quick-deploy.sh" 'run_postflight_convergence\(' 'Quick deploy centralizes post-flight convergence mode dispatch'
check_pattern "nixos-quick-deploy.sh" 'run_dashboard_runtime_postflight\(' 'Quick deploy centralizes dashboard and Prometheus post-flight handling'
check_pattern "nixos-quick-deploy.sh" 'verify_repo_backed_ai_services_are_live_if_needed\(\)' 'Deploy entrypoint verifies repo-backed AI services after restart'
check_pattern "nixos-quick-deploy.sh" '/workflow/plan' 'Deploy verification probes workflow plan capability activation'
check_pattern "nixos-quick-deploy.sh" '/qa/check' 'Deploy verification probes hybrid QA endpoint activation'
check_pattern "nixos-quick-deploy.sh" '/learning/export' 'Deploy verification probes learning export activation'
check_pattern "scripts/automation/post-deploy-converge.sh" 'aq-qa" 0 --json' 'Post-deploy convergence runs aq-qa phase 0'

# Phase 4 — Parity scorecard completion (tracks implemented status)
check_pattern "config/parity-scorecard.json" '"status": "implemented"' 'Parity scorecard has implemented tracks'
check_pattern "config/parity-scorecard.json" '"id": "distributed_tracing"' 'Parity scorecard tracks distributed tracing'
check_pattern "config/parity-scorecard.json" '"id": "llm_performance_metrics"' 'Parity scorecard tracks LLM metrics'
check_pattern "config/parity-scorecard.json" '"id": "cache_intelligence"' 'Parity scorecard tracks cache intelligence'

# Phase 5 — Model management enhancement
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/metrics.py" 'MODEL_RELOADS' 'Model reload counter metric defined'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/metrics.py" 'MODEL_RELOAD_DURATION' 'Model reload duration histogram defined'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/metrics.py" 'MODEL_ACTIVE_INFO' 'Model active info gauge defined'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '/model/status' 'Model status endpoint registered'
check_pattern "nix/modules/services/monitoring.nix" 'model_reloads_total' 'Dashboard tracks model reloads'
check_pattern "config/parity-scorecard.json" '"id": "model_management"' 'Parity scorecard tracks model management'
check_pattern "scripts/testing/test-switchboard-continue-context-window.sh" 'X-AI-Profile: continue-local' 'Continue-local oversized-input regression smoke exists'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" '"orchestration": orchestration' 'Delegated runtime responses include normalized orchestration metadata'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/delegation_feedback.py" '"handoff_requested": bool' 'Delegation feedback records coordinator handoff requests'
check_pattern "scripts/ai/aq-report" 'handoff_by_requester_role' 'aq-report summarizes coordinator handoff frequency by requester role'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'request_context\["orchestration"\] = orchestration' 'Direct query requests normalize orchestration metadata at entry'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'metadata\["orchestration"\]' 'Direct query responses expose compact orchestration metadata'
check_pattern "ai-stack/mcp-servers/hybrid-coordinator/http_server.py" 'for key in \("requesting_agent", "requester_role", "delegate_via_coordinator_only"\)' 'Internal autorun audit rows inherit query requester metadata'
check_pattern "scripts/ai/aq-report" 'top_requester_roles' 'aq-report summarizes workflow requester-role mix'
check_pattern "scripts/ai/aq-report" 'accepted_by_requester_role' 'aq-report summarizes accepted workflow reviews by requester role'
check_pattern "scripts/ai/aq-report" 'top_reviewers' 'aq-report summarizes workflow reviewer activity'
check_pattern "scripts/ai/aq-report" 'accepted_blueprints|rejected_blueprints' 'aq-report summarizes accepted and rejected workflow blueprints'
check_pattern "scripts/ai/aq-report" 'top_review_types|accepted_patch_reviews|patch_reviews_by_reviewed_agent|accepted_task_classes' 'aq-report summarizes patch-review and task-class workflow telemetry'
check_pattern "scripts/testing/test-workflow-review-gate.py" 'top_reviewers|accepted_blueprints|rejected_blueprints|accepted_patch_reviews|patch_reviews_by_reviewed_agent' 'Workflow review-gate test covers reviewer, blueprint, and patch-review aggregates'

printf '\n[verify] Summary: %d pass, %d fail\n' "$pass_count" "$fail_count"
if (( fail_count > 0 )); then
  exit 1
fi
